### ISSUE TITLE
UI: Upload multiple non-DICOM Objects

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1012]
Enable to select multiple non-DICOM Objects for upload.

Extends #653, #784 

Related [dcm4che#290](https://github.com/dcm4che/dcm4che/issues/290), [dcm4che#313](https://github.com/dcm4che/dcm4che/issues/313)

**Comment by vrindanayak** [comment]
Available in both old and new studies page
