### ISSUE TITLE
UI: In configuration view, improve the way configuration path is displayed and enable copy to clipboard function

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1070]
When documenting some configuration steps on the archive, it would be helpful if one could copy the current path in the configuration tree to clipboard i.e.:

![screenshot 11](https://user-images.githubusercontent.com/1150350/32932104-8ef8a002-cb67-11e7-92e2-3aa198f1471e.png)

Environment: 
- dcm4chee-arc-light-logstash:5.11.0.RC1
- Safari 11.0.1 (12604.3.5.1.1)

**Comment by petrkalina** [comment]
idea: the path could also be display as

**Comment by shral** [comment]
#1212
