### ISSUE TITLE
UI: series metadata storage path is not displayed correctly

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1071]
![screenshot 21](https://user-images.githubusercontent.com/1150350/32943604-f237b93a-cb8c-11e7-90fb-e4e9b971f6ac.png)

possibly affects also other path attributes

**Comment by gunterze** [comment]
The path is stored as multiple values with are displayed comma separated. Using '/' would not make sense for most other attributes containing multiple values.
