### ISSUE TITLE
SQL-Error in dcm4chee-arc-5.11.0-mysql-secure

### ISSUE THREAD

**Issue by Linuxfabrik** [dcm4che/dcm4chee-arc-light#1093]
create-mysql.sql, Line 156:
`create index UK_q7vxiaj1q6ojfxdq1g9jjxgqv on study (study_size(64));`

Error Code: 1089. Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys

**Comment by gunterze** [comment]
Fixed to
```sql
create index UK_q7vxiaj1q6ojfxdq1g9jjxgqv on study (study_size)
```
Corrected [create-mysql.sql](https://raw.githubusercontent.com/wiki/dcm4che/dcm4chee-arc-light/mysql/create-mysql.sql)
