### ISSUE TITLE
Two WildFly warnings in 5.11.0

### ISSUE THREAD

**Issue by Linuxfabrik** [dcm4che/dcm4chee-arc-light#1095]
Appearing on startup:

`WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.dcm4chee-arc-ear-5.11.0-mysql-secure.ear" is using a private module ("org.apache.cxf.impl") which may be changed or removed in future versions without notice.`

`WARN  [org.keycloak.services] (ServerService Thread Pool -- 75) KC-SERVICES0047: dcm4che-audit (org.dcm4che3.audit.keycloak.Dcm4cheEventListenerProviderFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice`

**Comment by vrindanayak** [comment]
- Regarding the Keycloak warning thrown by Keycloak's services : This warning is seen if you are using secured version of archive. The latest release of Keycloak 3.4.0 which is used for 5.11.0, does not make use of `providers` in their keycloak-install.cli script. Secured version of archive needs the `provider` along with `eventsListener` as mentioned in point 6 in [Secured Archive Installation](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation-and-Configuration#installation-and-configuration). 
- Point 6 mentioned in [Secured Archive Installation](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation-and-Configuration#installation-and-configuration) may be skipped, if audit messages for [User Authentication](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Supported-Audit-Messages-and-Events) event is not needed; which will also avoid showing the WARN message at startup.

**Comment by gunterze** [comment]
The XDS-I exporter uses Apache CXF proprietary classes to configure TLS parameters for the outgoing SOAP request (s. [XDSiExporter.java](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-export-xdsi/src/main/java/org/dcm4chee/arc/export/xdsi/XDSiExporter.java#L302))
