### ISSUE TITLE
Weasis Deployment Problems in 5.11.0

### ISSUE THREAD

**Issue by Linuxfabrik** [dcm4che/dcm4chee-arc-light#1096]
Due to a Keycloak issue I can't deploy weasis.war in WildFly 11 with Keycloak 3.4.0 Overlay and DCM4CHEE 5.11.0 (on CentOS 7).

If I try to deploy weasis.war, I get: `Cannot upload deployment: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./weasis" => "java.lang.RuntimeException: java.lang.IllegalStateException: WFLYUT0085: The required mechanism 'BASIC' is not available in mechanisms [KEYCLOAK] from the HttpAuthenticationFactory. Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: WFLYUT0085: The required mechanism 'BASIC' is not available in mechanisms [KEYCLOAK] from the HttpAuthenticationFactory. Caused by: java.lang.IllegalStateException: WFLYUT0085: The required mechanism 'BASIC' is not available in mechanisms [KEYCLOAK] from the HttpAuthenticationFactory."}}`

So if I edit `$WILDFLY_HOME/standalone/configuration/dcm4chee-arc.xml` and enhance

`                    <mechanism-configuration>
                        <mechanism mechanism-name="KEYCLOAK">
                            <mechanism-realm realm-name="KeycloakOIDCRealm" realm-mapper="keycloak-oidc-realm-mapper"/>
                        </mechanism>
                    </mechanism-configuration>`

by

`                    <mechanism-configuration>
                        <mechanism mechanism-name="KEYCLOAK">
                            <mechanism-realm realm-name="KeycloakOIDCRealm" realm-mapper="keycloak-oidc-realm-mapper"/>
                        </mechanism>
                        <mechanism mechanism-name="BASIC">
                            <mechanism-realm realm-name="Application Realm"/>
                        </mechanism>
                    </mechanism-configuration>`

then I am able to deploy - but this will raise a "Forbidden" while trying to access the dcm4chee-arc/ui2 using my browser.

**Comment by vrindanayak** [comment]
- This has been discussed already in the forum. Please refer [post](https://groups.google.com/forum/?hl=en#!topic/dcm4che/jDESEhhkWJk)
- Currently Weasis Viewer Integration may be used with unsecured version of archive
