### ISSUE TITLE
IDEA/Enhancement:  configure email alerts

### ISSUE THREAD

**Issue by doc-jay** [dcm4che/dcm4chee-arc-light#1114]
I would be very nice to be alerted via email if an export task that is scheduled by an exporter fails or goes into warning.  

I am using 4 instances of dcm4che-arc as DICOM gateways and I would like to be alerted if exports fail  or go into warning before the technologist calls because they can't find their exam on a different system.

**Comment by gunterze** [comment]
You may use the RESTful service to query for [Export Tasks](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/listExportTasks) or for [Tasks in the Export Queue](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/QUEUE-RS/listTasks) with status FAILED or WARNING by your own client and trigger any action you like.
