### ISSUE TITLE
Import Text Report received by HL7 ORU^R01 as DICOM SR 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#114]
Import Text Report received by HL7 ORU^R01 as DICOM SR using the inverse
[DICOM SR to Structured Report Export Mapping](http://ihe.net/uploadedFiles/Documents/Radiology/IHE_RAD_TF_Vol2.pdf#page=288) defined by IHE RAD-28.

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/061b6ce0017a5dd28591133aa75982b6b79cf35b
