### ISSUE TITLE
UI Patient Query:  'only with studies' filter ineffective 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1154]
If check box `only with studies` is selected, query parameter `withoutstudies=true`, instead of `withoutstudies=false`.

**Comment by shral** [comment]
Should we than change the label from "only with studies" to "without studies"?

**Comment by shral** [comment]
Changed as required. I'm leaving the issue open, so we can discuss, if we should change the filter name, so it's consistent with the label?

**Comment by shral** [comment]
It seams that it was a bug in angular 2, so that the parameters were not send, if they ware set to false.
