### ISSUE TITLE
UI: Create / Update Patients

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#116]
Using [RESTful Update Patient](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#!/IOCM-RS/updatePatient)

**Comment by vrindanayak** [comment]
Below 2 attributes need to be mandatory as per : `http://dicom.nema.org/medical/dicom/current/output/html/part03.html#sect_8.1`
Code Value  (0008,0100)  
Coding Scheme Designator (0008,0102)
