### ISSUE TITLE
UI Monitoring: Cancel/Reschedule/Delete all matching tasks from queue 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1168]
use RESTful services:
- [POST /dcm4chee-arc/queue/{queueName}/cancel](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/QUEUE-RS/cancelTasks)
- [POST /dcm4chee-arc/queue/{queueName}/reschedule](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/QUEUE-RS/rescheduleTasks)
- [DELETE /dcm4chee-arc/queue/{queueName}](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/QUEUE-RS/deleteTasks)

Cancel shall only be enabled if the filter for status is set to 
- `SCHEDULED` or
- `IN PROCESS`

Reschedule shall only be enabled if the filter for status is set to
- `COMPLETED`,
- `WARNING`,
- `FAILED` or
- `CANCELED`

and the filter for the Device Name is set to the Device Name of this archive instance.

Requires #1159, #1160, #1161

Remove *flush before* - function provided by *Delete of matching tasks*

**Comment by shral** [comment]
Implemented on the UI, need to be tested
