### ISSUE TITLE
UI Monitoring: Cancel/Reschedule/Delete all matching Retrieve Tasks

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1169]
use RESTful services:
- [POST /dcm4chee-arc/monitor/retrieve/cancel](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/RETRIEVE-RS/cancelRetrieveTasks)
- [POST /dcm4chee-arc/monitor/retrieve/reschedule](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/RETRIEVE-RS/rescheduleRetrieveTasks)
- [DELETE /dcm4chee-arc/monitor/retrieve](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/RETRIEVE-RS/deleteRetrieveTasks)

Cancel shall only be enabled if the filter for status is set to 
- `SCHEDULED` or
- `IN PROCESS`

Reschedule shall only be enabled if the filter for status is set to
- `COMPLETED`,
- `WARNING`,
- `FAILED` or
- `CANCELED`

and the filter for the Device Name is set to the Device Name of this archive instance.

Requires #1162, #1164, #1165

**Comment by shral** [comment]
Implemented on the UI, need to be tested
