### ISSUE TITLE
UI Monitoring: Cancel/Reschedule/Delete all matching Export Tasks

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1170]
use RESTful services:
- [POST /dcm4chee-arc/monitor/export/cancel](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/cancelExportTasks)
- [POST /dcm4chee-arc/monitor/export/reschedule](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/rescheduleExportTasks)
- [POST /dcm4chee-arc/monitor/export/reschedule/{newExporterID}](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/rescheduleExportTasksToExporter)
- [DELETE /dcm4chee-arc/monitor/export](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/deleteExportTasks)

Cancel shall only be enabled if the filter for status is set to 
- `SCHEDULED` or
- `IN PROCESS`

Reschedule shall only be enabled if the filter for status is set to
- `COMPLETED`,
- `WARNING`,
- `FAILED` or
- `CANCELED`

and the filter for the Device Name is set to the Device Name of this archive instance.

Requires #1163, #1166, #1167

**Comment by shral** [comment]
Implemented on the UI, need to be tested
