### ISSUE TITLE
[Wiki error] Difference between Archive UI and LDAP configuration

### ISSUE THREAD

**Issue by adreyfus** [dcm4che/dcm4chee-arc-light#1230]
In https://github.com/dcm4che/dcm4chee-arc-light/wiki/Requested-Procedures:

- Point 2. of **Using Archive UI** configures the fields `HL7 ADT Sending Application` and `HL7 ADT Receiving Application`,

- when **Using LDAP** configures the (different) fields `hl7PSUSendingApplication` and `hl7PSUReceivingApplication`

I can't correct because I don't know which fields are the right ones to configure.

**Comment by vrindanayak** [comment]
Thanks for pointing out. It's fixed.

**Comment by adreyfus** [comment]
It seems there is another error on the same page : 

in **Using LDAP** / **2. Study receive Triggered**:

It says `hl7PSUDelay: TRUE`, whereas I think `hl7PSUDelay` is a time (not a BOOLEAN).

**Comment by vrindanayak** [comment]
Fixed
