### ISSUE TITLE
UI2: in Monitoring - External Retrieve the "Instances / sec" column displays always 0

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1238]
![screenshot 339](https://user-images.githubusercontent.com/1150350/36536450-42d16eea-17cd-11e8-93b5-b74f35ba7486.png)

**Comment by shral** [comment]
Added `NumberOfInstances` calculation, I think that was missing, but I can not test it on my archive. @petrkalina pleas test it with the next release, if it's still not working pleas add some dummy response data. I'm closing the issue for now!
