### ISSUE TITLE
Retrieve URL should include port number when server does not listen to port 80

### ISSUE THREAD

**Issue by hackermd** [dcm4che/dcm4chee-arc-light#1240]
When running the dcm4chee server locally inside a Docker container the `Retrieve URL` attribute in response messages of QIDO-RS service does not include the port number:

```json
...
        "00081190": {
            "Value": [
                "http://localhost/dcm4chee-arc/aets/DCM4CHEE/rs/..."
            ],
            "vr": "UR"
        },
...
```

This leads to the following error when trying to retrieve the resource using the WADO-RS service:

```None
curl -I http://localhost/dcm4chee-arc/aets/DCM4CHEE/rs/studies/...
curl: (7) Failed to connect to localhost port 80: Connection refused
```

When including the port number, requests are successful:

```None
curl -I http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies/...
HTTP/1.1 200 OK
```

**Comment by gunterze** [comment]
I cannot reproduce the issue. Do you really run undertow in the container on 8080?

**Comment by hackermd** [comment]
That's weird! I consistently get the same error. I used the [docker compose file](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host#use-docker-compose) provided in the wiki.
