### ISSUE TITLE
UI: In Monitoring/External Retrieve, improve the response for long running background operations (XX for all matching tasks)

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1246]
If the number of tasks is big, the operation takes minutes to execute (i.e. 50K tasks for example). I noticed it is running in the background and potentially, when finished, there would be a message. Still, it is confusing.. 

Potentially, the correct behaviours would be to display message saying that the operation runs on the background and that you can continue to work.

Alternatively, you can also display "waiting for operation to finish" in the corner and change it to success after it has finished.

**Comment by gunterze** [comment]
What kind of operations takes long? Should only be rescheduling!

**Comment by petrkalina** [comment]
In my case it was rescheduling.

**Comment by shral** [comment]
Maybe it's enough only to change the loader module #1252
