### ISSUE TITLE
In Monitoring/Storage Systems the "Space(Usable/Total)" value doesn't match the value returned by the df command

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1247]
![screenshot 359](https://user-images.githubusercontent.com/1150350/36634270-5a2f7e5c-19a2-11e8-81a2-1fd5cdd9d56c.png)

vs.

```
prz-nfs.isilon.medizin.uni-leipzig.de:/Radiologie/Archiv2    10T  9.2T  873G  92% /data-prz/archive1/storage_1a2
```

**Comment by petrkalina** [comment]
this also affects the storage threshold - and the switching the storage on a different threshold than the expected one leading to i.e. nagios error.

in the observed case, the threshold was set to 100G, the switch occurred on the value that is outlined in the picture - and the nagios monitoring, set to raise alarm on 95G fired..

**Comment by gunterze** [comment]
Guess you mixed up binary and decimal units! s. https://en.wikipedia.org/wiki/Binary_prefix
s. `df -h` vs `df --si`
