### ISSUE TITLE
Little mistake on https://github.com/dcm4che/dcm4chee-arc-light/wiki/Upgrade

### ISSUE THREAD

**Issue by Linuxfabrik** [dcm4che/dcm4chee-arc-light#1250]
Section "Update WildFly Deployment" > Update DCM4CHE dcm4chee-arc-light libraries as JBoss modules.

Wrong: rm -r modules/modules/org/dcm4che

Correct: rm -r modules/org/dcm4che

**Comment by vrindanayak** [comment]
fixed
