### ISSUE TITLE
Configurable role to identify super users 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1256]
- [x] mark super users by `"su":"true"` in JSON reponse of [/dcm4chee-arc/realm service](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/REALM-RS/realm) if one of the roles of logged in user match with value of system property `super-user-role`.
- [x] Add environment variable `SUPER_USER_ROLE=admin` in Dockerfile and `<property name="super-user-role" value="${env.SUPER_USER_ROLE}"/>` in configuration file of secured version branches.
- [x] grant all permission to such users by the UI
- [x] emit an [Audit Message for Security Alert](http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_A.5.3.11) with `EventTypeCode = (110127,DCM,"Emergency Override Started")` on login of such user
- [x] emit an [Audit Message for Security Alert](http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_A.5.3.11) with `EventTypeCode = (110138,DCM,"Emergency Override Stopped")` on logout of such user

Related #1206

**Comment by vrindanayak** [comment]
4ef229c, 8272e7f, 1fe8243, 2f2b025

**Comment by vrindanayak** [comment]
https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/commit/2f2b02581018560863dd09e6dff2b6917d7d95fe
