### ISSUE TITLE
Describe support of  De-identify objects according the Basic Application Level Confidentiality Profile in DICOM Conformance Statement

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1259]
[DICOM PS3.15, E.1.3 Application Level Confidentiality Profiles, Conformance Requirements](http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_E.1.3)

Related: #1254

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-cs/commit/ef1691d9913aef61c20853724a8da0d1924ee9bf
https://github.com/dcm4che/dcm4chee-arc-cs/commit/1abdb7e4bd6b952d68c897d0b5c84374e51a8a65
https://github.com/dcm4che/dcm4chee-arc-cs/commit/f315e6269adbb16e87eb686cef3a0ce47cc410e3

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-cs/commit/d08a7c25c85bc428033343a4f90f09a70ab5b884

**Comment by vrindanayak** [comment]
http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/deidentification/deidentification.html

**Comment by gunterze** [comment]
Wrong position, should be under [8.1. Security Profiles](http://dicom.nema.org/medical/dicom/current/output/html/part02.html#sect_A.8.1)

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-cs/commit/4dc282ce5cdf5eb2f720c7a9983656f79009917c
https://github.com/dcm4che/dcm4chee-arc-cs/commit/a56595bf0871980c46d26eb557f8a66b4329677d
https://github.com/dcm4che/dcm4chee-arc-cs/commit/a61d23f74e9fe5cdd3d6da9a23caa5bf279ef0ed

**Comment by gunterze** [comment]
Missing **VR** and **Dummy Value** in *Table 7.76 Dummy values used to replace the attributes’ values*
