### ISSUE TITLE
/dcm4chee-arc/devices/{deviceName} returns invalid JSON on failures reading the Device Configuration from LDAP

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1262]
[/dcm4chee-arc/devices/{deviceName}](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/CONFIG-RS/getDevice) returns invalid JSON on failures reading the Device Configuration from LDAP - should return 500 Internal Server Error with Exception message.

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4che/commit/f030da63e2a8f1d75f53dd44653b567a73b24702
