### ISSUE TITLE
QIDO-RS: extend list of attributes to support concatenations

### ISSUE THREAD

**Issue by hackermd** [dcm4che/dcm4chee-arc-light#1297]
An instance may be broken down into multiple concatenation parts (see [PS3.3 C.7.6.16.1.3](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.html#figure_C.7.6.16-1a)). In this case, it will be essential to search for instances that belong to the same concatenation.

The minimal set of attributes that would be needed to identify concatenation parts are:

* Concatenation UID
* SOP Instance UID of Concatenation Source

For more information see [PS3.3 C.7.6.16](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.html#table_C.7.6.16-1).

It would be great if these attributes could be added for [SearchForInstances](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/qido-rs/qido-rs.html#instanceattributesmatching).

**Comment by gunterze** [comment]
You may just add the two attributes in the Instance Attribute Filter in the archive configuration:
![concatenationuid](https://user-images.githubusercontent.com/400095/37841207-71979110-2ebf-11e8-8d93-5b8a3dd967d5.png)

**Comment by hackermd** [comment]
Nice, I wasn't aware of this feature. Thank you!
