### ISSUE TITLE
QIDO-RS: extend list of attributes to support specimen

### ISSUE THREAD

**Issue by hackermd** [dcm4che/dcm4chee-arc-light#1298]
The imaged object may be a specimen (see [PS3.3 C.7.6.22.1](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.22.html#sect_C.7.6.22.1)). In this case, it will be essential to search for instances that where acquired for the same specimen.

The set of attributes that would be required to identify specimens and/or their corresponding containers are:

* Container Identifier
* Alternate Container Identifier Sequence
* Issuer of the Container Identifier Sequence
* Specimen UID
* Specimen Identifier
* Issuer of the Specimen Identifier Sequence

For more information see [PS3.3 C.7.6.22](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.22.html).

It would be great if these attributes could be added for [SearchForInstances](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/qido-rs/qido-rs.html#instanceattributesmatching).

**Comment by gunterze** [comment]
You may just add the 6 attributes in the Instance Attribute Filter in the archive configuration. Will be configured by default in 5.13.0.

**Comment by hackermd** [comment]
Great! Thank you!
