### ISSUE TITLE
UI: Configuratior - If you change the AE title and that AET is some where else referenced (e.g. Device Extension->Archive Device->Rejection Note Storage AE title), the reference is not updated

### ISSUE THREAD

**Issue by shral** [dcm4che/dcm4chee-arc-light#1325]
Rename of Network AE shall implicitly also rename matching Archive Device Attributes:

Name | JSON property
-- | --
Reject Expired Studies AE Title | dcmRejectExpiredStudiesAETitle
Storage Verification AE Title | dcmStorageVerificationAETitle
External Retrieve AE Destination | dcmExternalRetrieveAEDestination
XDS-I Imaging Document Source AE Title | dcmXDSiImagingDocumentSourceAETitle
Rejection Note Storage AET | dcmRejectionNoteStorageAET

**Comment by gunterze** [comment]
Shall be solved more general by #1673
