### ISSUE TITLE
Some of the problems that arise when you join hadoop.

### ISSUE THREAD

**Issue by JBingSheng** [dcm4che/dcm4chee-arc-light#1336]
The author hello

**Comment by JBingSheng** [comment]
This project is in the filesystem package, and I want to change the storage to hadoop storage.

**Comment by JBingSheng** [comment]
But as long as the pom.xml with hadoop package will be an error, I have already solved some, but in the end point error are jars have conflict, I don't know whether the original project what packages and hadoop

**Comment by bmllx** [comment]
Hello, Sir, when I changed the storage function of the project, I came up with the problem of adding dependency error. I intended to change the storage to hadoop, but now I dependency  error too much, and I hope to teach me!

**Comment by shral** [comment]
Pleas post your questions in the [community google group](https://groups.google.com/forum/#!forum/dcm4che)
