### ISSUE TITLE
Problem with ElasticSearch (in Docker installtion)

### ISSUE THREAD

**Issue by lsoeot** [dcm4che/dcm4chee-arc-light#1353]
We have problem with elastic dashboard in ui2 , first there was a problem  interface look's for a elasticsearch:9200 url , but we change it to  fqdn  in archive attributes second problem is CORS problem , we solve it too but now there is a problem like in screen ... 

![elastic problem](https://user-images.githubusercontent.com/38498348/38933334-f34c1e3e-4318-11e8-8e42-4aabcfd196e6.PNG)

**Comment by shral** [comment]
Hi, @lsoeot  where did you get this version of the archive? There is no elasticsearch support in the open source version of ui/archive only in the pro version of the ui.

**Comment by lsoeot** [comment]
from docker like in this url https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-all-archive-services-with-secured-UI-and-storing-System-and-Audit-logs-to-Elastic-Stack-on-a-single-host#use-docker-compose

**Comment by shral** [comment]
It seams that we made a mistake on building process, @gunterze would you look on this?

**Comment by shral** [comment]
@lsoeot as Gunter (gunterze) is in connectathon this week, you could try in the mean time to change the name of the arc image in docker-compose.yml file from `dcm4che/dcm4chee-arc-psql:5.13.0-logstash-secure-ui` to `dcm4che/dcm4chee-arc-psql:5.13.0-secure-ui` and try again (and hope that that version is not effected too).

**Comment by lsoeot** [comment]
the same ... and what is PRO version of UI ?

**Comment by shral** [comment]
Then we have to wait for Gunter until next week! 
If you hiring j4care (The company that Payes our( cor team) salary), [j4care](http://web.j4care.com/dcm4chepro) will install for you pro (paid and with some more features as the open source) version of UI/Archive in your sistems.

**Comment by gunterze** [comment]
I pushed new images for 5.13.0 to hub.docker.com
