### ISSUE TITLE
LDAP objectClass dcmWebApp absent from schema

### ISSUE THREAD

**Issue by jcarlallen** [dcm4che/dcm4chee-arc-light#1354]
Load of default-config.ldif errors on absence of schema for dcmWebApp.  Scan and search of sources indicate perhaps schema updates may have not been included in recent update(s) #1330.

**Comment by gunterze** [comment]
It's [present](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-conf/dcm4che-conf-ldap-schema/src/main/resources/ldap/schema/dcm4che.schema#L665)!
