### ISSUE TITLE
Installation guide: OpenLDAP with dynamic runtime configuration

### ISSUE THREAD

**Issue by mkauzlar** [dcm4che/dcm4chee-arc-light#136]
The guide states that to setup slapd you need:

> sudo ldapadd -Y EXTERNAL -H ldapi:/// -f $DCM4CHEE_ARC/ldap/slapd/dicom.ldif
> sudo ldapadd -Y EXTERNAL -H ldapi:/// -f $DCM4CHEE_ARC/ldap/slapd/dcm4che.ldif
> sudo ldapadd -Y EXTERNAL -H ldapi:/// -f $DCM4CHEE_ARC/ldap/slapd/dcm4chee-archive.ldif

however $DCM4CHEE_ARC/ldap/slapd/dicom.ldif and $DCM4CHEE_ARC/ldap/slapd/dcm4che.ldif files do not exist. 
the file ldap/slapd/dcm4chee-archive.ldif is located in $DCM4CHEE_ARC/dcm4chee-arc-assembly/src/main/resources/

**Comment by gunterze** [comment]
The guide is written for using the binary distribution ZIP, not from the
sources in the GIT repository!
