### ISSUE TITLE
 UI:Monitoring->Export: To Schedule incorrectly shows '0' when there are exports waiting to be scheduled

### ISSUE THREAD

**Issue by doc-jay** [dcm4che/dcm4chee-arc-light#1372]
I have never seen this report back anything other than '0'.  I have a clinic that has dcm4chee v5.13.0 and its export descriptor is set with a scheudule of 'hour=22-7 dayOfWeek=*' and the studies are sent successfully between that time.  

Under the export tab under monitoring, 'TO SCHEDULED' never reflects how many are waiting to be sent.

**Comment by vrindanayak** [comment]
This will be resolved in next release. #1362
