### ISSUE TITLE
How to increase the speed of uploading dcm4che-arc-ligth5 data to S3 object store 

### ISSUE THREAD

**Issue by yongliangZhang** [dcm4che/dcm4chee-arc-light#1376]
I use dcm4chee-arc-light5 as an archiving service, but I compared the use of local storage and S3 object storage, the same check data volume [test sample: 1.39G, 24 patient check], the local receiving efficiency is received by the S3 object 30 times, how to improve the S3 Object's transmission speed.

**Comment by gunterze** [comment]
Please use https://groups.google.com/forum/#!forum/dcm4che , and not the issue tracker for asking questions. With 5.13.1 it will be possible to configure a file system based receive cache, from which a configurable number of threads copies received instances to an S3 based nearline storage (#590).
