### ISSUE TITLE
no versioned package in repository http://www.dcm4che.org/maven2 except 5.0.1

### ISSUE THREAD

**Issue by angelo-chan** [dcm4che/dcm4chee-arc-light#138]

**Comment by gunterze** [comment]
I only deployed the EAR ( s. http://www.dcm4che.org/maven2/org/dcm4che/dcm4chee-arc/dcm4chee-arc-ear/ ) for building the Docker image ( https://hub.docker.com/r/dcm4che/dcm4chee-arc-psql/ )

**Comment by angelo-chan** [comment]
could you please deploy all the libs in the repository since we already use 5.0.1 for our project and want to upgrade to 5.3.X

**Comment by angelo-chan** [comment]
@gunterze do you have plan to release all those dcm4che and dcm4chee library in your maven repo? Thanks.

**Comment by gunterze** [comment]
Not short term - perhaps after I moved the repository to Sonatype (not yet
scheduled)
