### ISSUE TITLE
Testplan for Nearline Storage

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1382]
Provide Testplan for #590 in Wiki covering:
- [x] Test copy to near-line storage before/after creation of Series Metadata (#454) and before/after of Purging of Instance Records from the database (#470). : [Copy Objects Nearline Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Copy-Objects-Nearline-Storage)
- [x] Verify that both Storage Locations are shown in private Instance Attributes in the UI - also after Purging of Instance Records from the database. : [Copy Objects Nearline Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Copy-Objects-Nearline-Storage)
- [x] Verify, that on retrieve the object is read from the online Storage and **not** from the near-line Storage -  also after Purging of Instance Records from the database. : [Retrieve Objects Online Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Retrieve-Objects-Online-Storage)
- [x] Test IOCM operations reject/copy/move on instances with objects on online **and** near-line Storage : [IOCM Operations](https://github.com/dcm4che/dcm4chee-arc-light/wiki/IOCM-Operations)
- [x] Test the deletion of objects from the online Storage triggered by the configured deleter threshold before/after creation of Series Metadata (#454) and before/after of Purging of Instance Records from the database (#470). : [Auto Deletion of Objects Online Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Auto-Deletion-of-Objects-Online-Storage)
- [x] Verify that after the deletion only the Storage Location on the near-line storage is shown in private Instance Attributes in the UI - also after Purging of Instance Records from the database. : [Auto Deletion of Objects Online Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Auto-Deletion-of-Objects-Online-Storage)
- [x] Verify that a study is **not** deleted, if only some of its objects are available at the nearline Storage  - also after Purging of Instance Records from the database. : [No Deletion of Partially Available Study Nearline Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/No-Deletion-of-Partially-Available-Study-Nearline-Storage)

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/wiki/Nearline-Storage-Testplan
