### ISSUE TITLE
Testplan for Retrieve Cache for Nearline Storage

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1409]
Provide Testplan for #1402 in Wiki covering:

- [x] Verify that configured Retrieve Cache is used by C-MOVE SCP and C-GET SCP on Study, Series and Instance level.
- [x] Verify Number of Remaining/Completed Instances in pending and final C-MOVE RSP and C-GET RSP.
- [x] Verify that both Storage Locations are shown in private Instance Attributes in the UI
- [x] Repeat the tests for Studies/Series with some instances already on the retrieve cache
- [x] Repeat the tests for Studies/Series with calculated Series Meta Data. Verify that both Storage Locations are shown in private Instance Attributes in the UI.
- [x] Repeat the tests with Studies/Series which instance records are already purged
- [x] Verify that configured Retrieve Cache is used by RESTful service [Export Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/exportStudy) - synchronous (`/dcm4chee-arc/aets/{aet}/rs/studies/{studyUID}/export/dicom:{destinationAET}`) and queued (`/dcm4chee-arc/aets/{aet}/rs/studies/{studyUID}/export/{exporterID}`)
- [x] Verify that configured Retrieve Cache is used by IHE RAD-69: Retrieve Imaging Document Set (#546)
- [x] Verify that configured Retrieve Cache is used by WADO-RS [Retrieve Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger-dicom.json#/WADO-RS/RetrieveStudy)
- [x] Verify deletion of least recently accessed Study from retrieve cache, configuring a _Deleter Threshold_  and the nearline storage as _Export Storage ID_. Verify, that objects of a Study also get deleted from the retrieve cache, if not all of its instances are on the retrieve cache.
- [x] Repeat last test for Studies which instance records are already purged

Increase the level of logger `org.dcm4chee.arc.retrieve` to `DEBUG` to see details of the copying to the retrieve cache in `server.log`.

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/wiki/Retrieve-Cache-for-Nearline-Storage
