### ISSUE TITLE
Describe support of WADO-WS in DICOM Conformance Statement

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1439]
Document support of
- WADO-WS: RetrieveImagingDocumentSet according [IHE Radiology Technical Framework, Volume 3](http://ihe.net/uploadedFiles/Documents/Radiology/IHE_RAD_TF_Vol3.pdf#page=184) #546
- WADO-WS: RetrieveRenderedImagingDocumentSet according [DICOM PS3.18 2017b](http://dicom.nema.org/medical/dicom/2017b/output/html/part18.html#sect_6.4.2) #1176

in the DICOM Conformance Statement according [DICOM PS3.2 2017b](http://dicom.nema.org/medical/dicom/2017b/output/html/part02.html#sect_A.4.2.2.1). S.o. [Conformance Statement Sample WADO Service](http://dicom.nema.org/medical/dicom/2017b/output/html/part02.html#sect_I.4.2.1).

**Comment by vrindanayak** [comment]
[WADO-WS Retrieve Imaging Document Set Specification](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/wado-ws-rad69.html)
[WADO-WS Retrieve Rendered Imaging Document Set Specification](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/wado-ws-retrieve-rendered-imaging-doc-set.html)

**Comment by gunterze** [comment]
- Remove `Size restriction`, also from STOW-RS, WADO-URI and WADO-RS
- Correct `SOP Class Support`: Only Storage SOP Classes, not Q/R Service SOP Classes, WADO-WS Retrieve Rendered Imaging Document Set only **Image** Storage SOP Classes. Concerns also description of STOW-RS and WADO-RS.
- Remove `Transfer Syntaxes Supported` from WADO-WS Retrieve Rendered Imaging Document Set Specification
- Clarify `Transfer Syntaxes Supported` - also for STOW-RS, WADO-URI and WADO-RS - by referring directly to [Transfer Syntaxes for Image Storage SOP Classes](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/query-retrieve/query-retrieve.html#scuimagets) and [Transfer Syntax for Video Storage SOP Classes](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/query-retrieve/query-retrieve.html#scuvideots), for STOW-RS to to [Transfer Syntaxes for Image Storage SOP Classes](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/storage/storage.html#scpimagets) and [Transfer Syntax for Video Storage SOP Classes](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/storage/storage.html#scpvideots). Extract `Transfer Syntax for SR SOP Classes` and `Transfer Syntax for Other SOP Classes` from [Table 4.7 Accepted Presentation Contexts of Storage Application Entity by default configuration](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/storage/storage.html#id11) and [Table 4.25 Accepted Presentation Contexts of Query/Retrieve Application Entity by default configuration](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/specs/query-retrieve/query-retrieve.html#id15), so they can referred from the STOW-RS and WADO-URI/RS/WS specifications too.
- Correct/complete description of supported optional request parameters by WADO-WS Retrieve Rendered Imaging Document Set, as listed in #1176
- Specify web service endpoints (URL) of all services
- Include WADO WS Request Examples for Retrieve Imaging Document Set and Retrieve Rendered Imaging Document Set as in [DICOM PS3.18 2017b](http://dicom.nema.org/medical/dicom/2017b/output/html/part18.html#sect_E.2)

**Comment by vrindanayak** [comment]
- Also list error status codes for WADO-WS sent by archive
