### ISSUE TITLE
Update IHE Integration Statement  (Eyecare,  Web-based Image Capturer, ID Invoker)

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1445]

**Comment by vrindanayak** [comment]
[IHE Integration Statement](https://github.com/dcm4che/dcm4chee-arc-light/wiki/IHE-Integration-Statement)

**Comment by gunterze** [comment]
There are 2 different Eyecare Image Manager actors:
- Image Manager-Image Archive in U-EYECARE - Model I
- Image Manager-Image Archive in U-EYECARE - Model III
[integrationStatement.pdf](https://github.com/dcm4che/dcm4chee-arc-light/files/2104995/integrationStatement.pdf)


Compare/adjust (also other profiles) with attached PDF generated by IHE Gazelle from the registration of dcm4chee-arc at IHE Europe Connectathon 2018

**Comment by gunterze** [comment]
Table structure broken, so it's no longer rendered pretty.
Last not broken commit: [470bba0fc9b19584fe26cab6597f9048064e4bc5](https://github.com/dcm4che/dcm4chee-arc-light/wiki/IHE-Integration-Statement/470bba0fc9b19584fe26cab6597f9048064e4bc5)
