### ISSUE TITLE
Support cache storage over several filesystems

### ISSUE THREAD

**Issue by adreyfus** [dcm4che/dcm4chee-arc-light#1455]
Hi,

Our studies are sent in several pieces, so they are divided between different storages. When a storage is 
full, they are not found for deletion.

I think this is because the function `Study.FIND_PK_BY_STORAGE_ID_ORDER_BY_ACCESS_TIME` (executed by the function `findStudiesForDeletionOnStorage(String storageID, int limit)>` to find the studies to purge) select studies with a storageID = `fs1`, or `fs2`, or `fs3`. Then studies with storageId = `fs1//fs2//fs3` are never selected.

Can you confirm the bug, please ?

**Comment by gunterze** [comment]
Current implementation does not support cache storage over several filesystems

**Comment by adreyfus** [comment]
Maybe I mis explained, sorry. Here is more details about the configuration. 

We created 3 storage descriptors fs1, fs2 and fs3. Each storage descriptor has a deleter threshold set to 5GB. So we expect the archive to purge oldest studies when the usable space fall below that value. 

Then we configured to use storages in parallel in the Archive network extensions.

![img_18062018_100734_0](https://user-images.githubusercontent.com/25580127/41525133-46d30170-72e0-11e8-8388-dbcf590a4706.png)
![img_18062018_100420_0](https://user-images.githubusercontent.com/25580127/41525106-31145f0a-72e0-11e8-9bcb-e1cf70e3efed.png)
![img_18062018_100652_0](https://user-images.githubusercontent.com/25580127/41525070-13635650-72e0-11e8-9176-188a764b51b0.png)

Studies are stored properly on each storage (each storage is filled almost equally). Purge is correctly launched when a storage is almost full, but no Studies are found for deletion. We think that it's because the SQL request `Study.FIND_PK_BY_STORAGE_ID_ORDER_BY_ACCESS_TIME` returns the String "fs1, fs2, fs3", that does not match any storage Id (storageId equals "fs1" or "fs2" or "fs3").

![img_18062018_102359_0](https://user-images.githubusercontent.com/25580127/41525586-c62c11c2-72e1-11e8-86af-247993f0fc7f.png)

**Comment by gunterze** [comment]
Correct, but splitting a cache storage (=deletion of studies is triggered by getting low on storage space) over multiple file systems was just not intended so far. So the issue should be rather labeled as improvement, than as bug.

**Comment by adreyfus** [comment]
Ok, thank you for answering, we didn't understand as that. 
We will use LVM to see only one file system.

**Comment by gunterze** [comment]
All Storage Systems acting as **one** cache storage have to be marked with an equal value of new [Storage Attribute](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/storage.html)

Name | Type | Description
-- | -- | --
Storage Cluster ID | string | Identifies a Storage to belong to a Storage Cluster. Objects of one Study may be distributed over Storage Systems of one Storage Cluster. Used by threshold triggered deletion.
