### ISSUE TITLE
Testplan for cache storage over several filesystems

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1472]
Provide Testplan for #1455 in Wiki covering:

- [x] unconstrained deletion of least recent used studies distributed over 3 file systems on exceeding the deleter threshold on one of the file systems.
- [x] deletion of objects of least recent used studies distributed over 3 file systems which objects are also stored on another _Storage System_ - identified by _Storage Attribute_: _Export Storage ID_ - on exceeding the deleter threshold on one of the file systems.
- [x] deletion of objects of least recent used studies distributed over 3 file systems which are retrieveable from an _External Retrieve AE_ - identified by _Storage Attribute_: _External Retrieve AET_ - on exceeding the deleter threshold on one of the file systems.

**Comment by vrindanayak** [comment]
[Cache Storage over Several Filesystems](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Cache-Storage-over-Several-Filesystems)
