### ISSUE TITLE
dicom Manufacturer and DivceSeriesNumber 

### ISSUE THREAD

**Issue by kongdetai** [dcm4che/dcm4chee-arc-light#1475]
Hi,   I see the field of the hospital name is recorded in the series table. 
About the fields of the device manufacturers and device serial number of DICOM data,  are there some fields in the database table to record?  Or how to know DICOM data's manufacturers and device serial number in DCM4CHEE database? How to config it?

Sorry about my poor English.  

Looking forward to your reply！

**Comment by vrindanayak** [comment]
Please use [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che) only for asking questions.
