### ISSUE TITLE
WADO-URI: insert xml-stylesheet processing instruction in returned CDA documents

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1482]
Insert [xml-stylesheet processing instruction](https://www.w3.org/TR/2010/REC-xml-stylesheet-20101028/#the-xml-stylesheet-processing-instruction) in returned CDA documents **after**  `<?xml version="1.0"?>` and **before** `<ClinicalDocument ...>`, e.g.
```xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="https://raw.githubusercontent.com/lantanagroup/stylesheets/master/Stylesheets/CDA/dist/cda-web.xsl"?>
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:voc="urn:hl7-org:v3/voc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:v3 CDA.xsd">
:
```
If the embedded CDA already contains a `<?xml-stylesheet ..>` processing instruction, the url shall be replaced with the configured one.

The URL of the XSL Stylesheet shall be configurable on [Archive Device](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveDevice.html) or [Archive Network AE](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveNetworkAE.html) level by Attribute

Name | Type | Description (LDAP Attribute)
-- | -- | --
Wado CDA2Html Template URI | string | URL to XSL style sheet inserted as <?xml-stylesheet  type="text/xsl" href="\<url>" > in CDA documents returned by WADO-URI service. If absent, the embedded CDI document is returned verbatim. (dcmWadoCDA2HtmlTemplateURI)

Set the attribute on Archive Device to `https://raw.githubusercontent.com/lantanagroup/stylesheets/master/Stylesheets/CDA/dist/cda-web.xsl` in the default configuration.

**Comment by vrindanayak** [comment]
- UI : Render Encapsulated CDA documents (similar to the way SRs are rendered)
- [CDASamples.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/2166006/CDASamples.zip)

**Comment by gunterze** [comment]
MIME type in a Content-type header value is case-**in**sensitive
