### ISSUE TITLE
Can't get NumberOfStudyRelatedSeries(0020,1206), NumberOfStudyRelatedInstances(0020,1208)

### ISSUE THREAD

**Issue by SongYg** [dcm4che/dcm4chee-arc-light#1493]
I created a DICOMDIR file with : --record-config /dcm4che-assembly/src/etc/dcmdir/RecordFactory.xml disk99/DICOM 
The CSV file is referencing the same dcm in disk99/DICOM with the additional Query/Retrieve Attributes: (0020,1206),(0020,1208). I want to add  additional Query/Retrieve Attributes to the DICOMDIR file that i created. And then I used dcm4che2.x dcmqr to query. I can't get the NumberOfStudyRelatedSeries(0020,1206), NumberOfStudyRelatedInstances(0020,1208). 
So how can I add the the additional Query/Retrieve Attributes to DICOMDIR and they are the same study.

**Comment by gunterze** [comment]
Please post questions to https://groups.google.com/forum/#!forum/dcm4che
