### ISSUE TITLE
UI Configuration: Verify AET, host and port before saving a new Remote Application Entity

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1522]
- [x] Extend RESTful service [Verify DICOM Connection](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/DIMSE-RS/verifyConnection) by _Query Parameters_ `host` and `port` to verify the communications between the specified Archive AE and the other AE provided by the specified host on the specified port - instead of looking up the host and port from the configuration for the other AE in LDAP.
- [x] Add a `Test Connection` button to the `Register new Application Entity` Panel, and a drop-down list with available Archive AETs, to invoke a verification of the DICOM Connection before saving the configuration for the new Application Entity.
- [x] When clicked on `Test Connection` button, send the values entered for `host` and `port` as query parameters in the request.

**Comment by vrindanayak** [comment]
`host` and `port` query parameters are not sent in the request which are needed to do successful echo to an Application Entity which has not yet been configured.
