### ISSUE TITLE
mwl-cfindrsp.xml sorting on date and time?

### ISSUE THREAD

**Issue by zolo** [dcm4che/dcm4chee-arc-light#1541]
This is really for the old version of dcm4chee (2.x) but maybe it applies:

Is it possible to use `mwl-cfindrsp.xml` to sort the result on scheduled date and time (0040,0002 and 0040, 0003) ? We use coercion of several AE titles, and one AE comes after the other, but we need sorting on date/time.

Ideas appreciated.

**Comment by vrindanayak** [comment]
Please use [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che) only for asking questions.

**Comment by zolo** [comment]
Thanks!
