### ISSUE TITLE
Keycloak update

### ISSUE THREAD

**Issue by AllanPinheiroDeLima** [dcm4che/dcm4chee-arc-light#1580]
Hey guys! 

Actually, this is more a question than a issue

I've been developing and app based on top of keycloak + dcm4chee arc light. But it seems that the version of keycloak ( 4.3.0 ) used on dcm4chee latest release has a major bug when updating user attributes from the rest api.

So, 4.4 is out, probably fixing this issue and would be great to update. Do you guys have this scheduled for the next minor release ?

**Comment by vrindanayak** [comment]
Please ask questions only in the [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che)
