### ISSUE TITLE
Forward HL7 messages conditional on any HL7 message field ((sub-) component

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1586]
Extend Conditions of [HL7 forwarding rules](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/hl7ForwardRule.html) to refer any HL7 message field ((sub-) component), not just HL7 message header fields. E.g. `PID-3.4.1` refers Namespace ID in first sub-component of Assigning Authority in 4th component of Patient Identifier List in 3th field of PID segment

**Comment by andersoncav** [comment]
Good afternoon,

I'm trying to send the msg hl7 to dcm4chee-arc but without success, the same message worked on dmc4chee-web3
RIS/WORKLIST

MSH|^~\&|MESA_OF|XYZ_RADIOLOGY|MESA_IM|XYZ_IMAGE_MANAGER|20200827105605||ORM^O01|100112|P|2.3.1|||||| || 
PID|||123456789^^^ADT123456789||Paciente Teste TI NAO DELETAR^-||19840209|F||WH|820 JORIE BLVD^^CHICAGO^IL^60523|||||||20-98-4000||||||||||||||||||||| 
PV1||E|ED||||1234^WEAVER^TIMOTHY^-^^-|5101^-^^-^^-|0000^Consulting^Doctor^P^^DR|HSR|||||AS||0000^Admitting^Doctor^P^^DR||V100^^^ADT1|||||||||||||||||||||||||20200827105605|||||||V| 
ORC|NW|A100Z^ARCOSCOSTAISD^^^ARCOSCOSTAISD|B100Z^MESA_ORDFIL||SC||1^once^^^^S||20200827105605|^ROSEWOOD^RANDOLPH||7101^ESTRADA^JAIME^P^^DR|Enterer^^Location^EL^00000|(314)555-1212|200008161510||922229-10^IHE-RAD^IHE-CODE-231|| 
OBR|1|A100Z^MESA_ORDPLC|B100Z^MESA_ORDFIL|P1^Procedure 1&ARCOSCOSTAISD&ARCOSCOSTAISD&ARCOSCOSTAISD&ARCOSCOSTAISD^ERL_MESA^CR^ARCOSCOSTAISD^AMIL|||||||||||Radiology^^^^R|7101^ESTRADA^JAIME^P^^DR||244526111|244526111|244526111||||CR|||1^once^^^^S|||AMIL|ARCOSCOSTAISD^ARCOSCOSTAISD^ARCOSCOSTAISD||||||||||A|||244526111^ARCOSCOSTAISD||&FNAME&GNAME&MNAME&SUFFIX&PREFIX^FNAME^GNAME^MNAME^^SUFFIX|&ADMIN&ADMIN&ADMIN&M.D.&DR.^ADMIN^ADMIN^ADMIN^DR.^M.D.|||||||||PROCEDURECODE^^^^ARCOSCOSTAISD|| 
DG1||I9|824^ARCOSCOSTAISD^I9|ARCOSCOSTAISD|||||||||||ARCOSCOSTAISD|ARCOSCOSTAISD| 
ZDS|1.2.4.0.13.1.432252867.244526111.1^100^Application^DICOM

**Comment by vrindanayak** [comment]
@andersoncav : Your MSH segment has incorrect value in encoding characters. It has `^~&` instead of `^~\&`

I'm able to send your (updated with correct encoding characters) [HL7 message](https://github.com/dcm4che/dcm4chee-arc-light/files/5137239/1586.zip) to archive and also forward it to HL7 receiver successfully.

![image](https://user-images.githubusercontent.com/15785031/91460158-c6195780-e887-11ea-80c2-090aae3cd925.png)

![1586](https://user-images.githubusercontent.com/15785031/91460279-ef39e800-e887-11ea-8684-5f7b58cf840c.png)

**Comment by andersoncav** [comment]
![ERRO CONEXAO](https://user-images.githubusercontent.com/15268034/91473120-cfe29100-e86e-11ea-8680-49c4ea60247b.jpg)

I am able to connect but when sending it continues giving error. I am sending the settings as an attachment.
Is it necessary to perform any activation for dcm4chee-arc to activate hl7?

I saw that you are using port 2576

**Comment by vrindanayak** [comment]
@andersoncav : Which version of Dcm4chee archive are you using? The above screenshot that you have attached doesn't look like it is from Dcm4chee archive version 5.x.x

No extra settings are required to activate HL7 in archive, it is preconfigured to receive HL7 messages on port 2575.

The port 2576 that I've used is that of [hl7rcv tool](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-hl7rcv/README.md) from the dcm4che library toolkit, just to indicate simulation of forwarding received HL7 messages from the archive to other systems capable of receiving these.

**Comment by andersoncav** [comment]
Good Morning, I'm using dcm4chee-arc on a computer with windows 10. Do
these dcm tools install on windows?
I downloaded the package, these are java files. checked and you were
sending the message from the command prompt

Em sex., 28 de ago. de 2020 às 03:22, Vrinda Nayak <notifications@github.com>
escreveu:

**Comment by vrindanayak** [comment]
Yes the dcm4che toolkit can be used on Windows as well.
