### ISSUE TITLE
Emit Audit Messages on any action a Keycloak admin performs within the admin console

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1592]
Emit [Audit Message for Security Alert](http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_A.5.3.11) for : 
- Admin events for which returns Keycloak returns `Operation Type` as `CREATE` and `Resource Type` as `REALM_ROLE_MAPPING` or `CLIENT_ROLE_MAPPING`; `EventTypeCode` shall be `(110136, DCM, "Security Roles Changed")`
- Admin events for which returns Keycloak returns `Operation Type` as `UPDATE` and `Resource Type` as `USER`; `EventTypeCode` shall be `(110137, DCM, "User Security Attributes Changed")`
- All other Admin events for which returns Keycloak returns `Operation Type` as `CREATE`, `UPDATE` or `DELETE`; `EventTypeCode` shall be `(110129, DCM, "Security Configuration")`

The emitted audit message shall also contain `ParticipantObjectDetail` containing the `Representation` and `ResourcePath` information sent back by Keycloak.

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4che/commit/2fedab2373ba27fd2ef828db99b353396e85d485

**Comment by vrindanayak** [comment]
- As per [Security Alert audit message](http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_A.5.3.11) the `EventActionCode` shall always be `Execute(=E)`.  Hence change the current `EventActionCode` for various Keycloak Admin events from `Create(=C)`, `Update(=U)` and `Delete(=D)` to `Execute(=E)`. 
- The `OperationType` and `ResourceType` shall be included as part of `AlertDescription`.
