### ISSUE TITLE
problem with concurency in export task

### ISSUE THREAD

**Issue by lsoeot** [dcm4che/dcm4chee-arc-light#1599]
Hello,

there is another problem we experience export task even if we set fetch size to bigger number (like 30) 
always send only 5 concurent thread...

like in screen bellow 
![image](https://user-images.githubusercontent.com/38498348/45760792-2a0e5c80-bc2b-11e8-8ecc-7fd94c11f9b1.png)

**Comment by gunterze** [comment]
Number of JMS consumers is configurable by System properties (s. #1359), which requires that [Spec Descriptor Property Replacement](https://docs.jboss.org/author/display/WFLY/Subsystem+configuration) is enabled:

```
$ ~/wildfly-13.0.0.Final/bin/jboss-cli.sh -c
[standalone@localhost:9990 /] /subsystem=ee:read-attribute(name=annotation-property-replacement)
{
    "outcome" => "success",
    "result" => false
}
```
Please post questions to the [dcm4che user forum](https://groups.google.com/forum/#!forum/dcm4che). Github issue tracker shall only be used for bug reports and specific feature requests.
