### ISSUE TITLE
UI: Logout of the UI goes sometimes to infinit loop

### ISSUE THREAD

**Issue by shral** [dcm4che/dcm4chee-arc-light#1614]

**Comment by shral** [comment]
Logout loop seams to appear if caching of the UI is active. @gunterze pleas change the default config to not active.

**Comment by shral** [comment]
Seams to be connecte to this issue: https://github.com/mauriciovigolo/keycloak-angular/issues/91

**Comment by adreyfus** [comment]
https://github.com/mauriciovigolo/keycloak-angular/issues/91#issuecomment-477852747

**Comment by gunterze** [comment]
Actually, `web-origin` and `roles` are listed under **Assigned Default Client Scopes** on new created clients by default.

**Comment by adreyfus** [comment]
https://github.com/mauriciovigolo/keycloak-angular/issues/91#issuecomment-501403133

**Comment by shral** [comment]
The changes in #1999 should resolve this bug, tha's why I will close this for now.
