### ISSUE TITLE
Cannot deplay psql-secure and psql-secure-ui

### ISSUE THREAD

**Issue by FlDutchman** [dcm4che/dcm4chee-arc-light#162]
Hello,
I'm trying to install dcm4chee with postgresql and secured UI. I did every step as described in the wiki but I get those errors when I want to deploy it:
http://pastebin.com/K7caEy7k and http://pastebin.com/nDkn1iBr

I guess it is missing something with Keycloak. Which version of it do I need? And where do I put it? I already read this https://github.com/dcm4che/dcm4chee-arc-light/wiki/How-to-secure-the-Web-UI but it says it is for 5.2.x and I already tried it with a seperate installation but it didn't work out...

**Comment by vrindanayak** [comment]
For DCM4CHEE archive version 5.2.x onwards, you need Wildfly 10.0.0 and Keycloak 1.9.1.
For new Installation, please refer - https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#setup-wildfly
For Upgrade - https://github.com/dcm4che/dcm4chee-arc-light/wiki/Upgrade#update-wildfly-deployment.

Please post in the dcm4che google group for further issues - https://groups.google.com/forum/#!forum/dcm4che
