### ISSUE TITLE
UI Study List: Show Patient Demographics from external Patient Demographics Provider

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1640]
Provide in Study List for internal and external AETs  control on Patient Level to Query Patient Demographics from external Patient Demographics Provider by [GET /dcm4chee-arc/pdq/{PDQServiceID}/patients/{patientID}](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/PDQ-RS/queryPatientDemographics).

Related: #1631, #1638

**Comment by shral** [comment]
PDQ service was implemented while #1802 was implemented
