### ISSUE TITLE
UI Studies: Make AET that is selected on first load configurable

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1655]
In case the main AET is not DCM4CHEE but i.e. PACSXXX, on first load, the IOCM_EXPIRED is selected as it comes alphabetically first. This can be confusing for the user. It would be better to be able to configure which AET is selected on first load.

**Comment by shral** [comment]
In pro is the[ filter template](https://github.com/dcm4che/dcm4chee-arc-light/issues/1539) implemented which solves this problem, therefore, I will close this issue
