### ISSUE TITLE
Resolve deletion failures automatically

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1686]
Periodically try to resolve failures to delete objects or (series-)metadata, by rescheduling its deletion if the object or  (series-)metadata still exists on the Storage and is not referenced by another record from the DB; otherwise just delete the record from the DB without (any attempt) deleting the object.

If resolving of the deletion failure itself fails, the status of the object reference in the DB is updated from `2 (=FAILED_TO_DELETE)` to `9 (=FAILED_TO_DELETE2)`, so the record will no longer be fetched by the query for resolving deletion failures.

Configurable by [Archive Device parameters](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveDevice.html):

Name | Type | Description (LDAP Attribute)
-- | -- | --
Failed to delete Polling Interval | string | Polling Interval for resolving deletion failures in ISO-8601 duration format PnDTnHnMnS. (dcmFailedToDeletePollingInterval)
Failed to delete Fetch Size | integer | Maximal number of Location records fetched for resolving deletion failures in one query. (dcmFailedToDeleteFetchSize)

**Comment by petrkalina** [comment]
In the table above, the attractive name should be `dcmFailedToDeleteStorageFetchSize` rather than `dcmFailedToDeleteFetchSize`

**Comment by petrkalina** [comment]
This explains why it doesn't work yet! Thanks!
