### ISSUE TITLE
HowTo Coerce Attributes of received DICOM objects by XSLT

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1691]
Either generalize [Ensure DICOM VR compliance of attribute values](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Ensure-DICOM-VR-compliance-of-attribute-values) or as new page, referring that page as sample.

**Comment by vrindanayak** [comment]
[Coerce received DICOM objects attributes by XSLT](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Coerce-received-DICOM-objects-attributes-by-XSLT)
