### ISSUE TITLE
UI: include .zip suffix for downloaded series/study and improve the names

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1705]
- study/series are downloaded as `iuid` file, which is in fact a zip file, however, it is missing the `.zip` suffix.
- instances are downloaded as `WADO` file - possibly it would be better to name the file `sop_iuid` or using the hash with which it is stored on the filesystem.

**Comment by gunterze** [comment]
Guess, the (proposed) file name is chosen by the browser based on the URL and cannot be changed by the UI application.

**Comment by vrindanayak** [comment]
Available and works in both old and new studies pages
