### ISSUE TITLE
Not supported IID request type: PATIENT

### ISSUE THREAD

**Issue by WWLJ** [dcm4che/dcm4chee-arc-light#1719]
我在集成weasis的时候，使用viewer查看的时候，控制台报错
 [stdout] (pool-10-thread-1) 2018-12-04 15:03:54,253 [ool-10-thread-1] ERROR o.w.s.ServletUtil         Not supported IID request type: PATIENT

然后会下载一个文件，请问一下这个是什么原因导致的

**Comment by WWLJ** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/13062111/49426882-d4366300-f7dc-11e8-8848-094115908cef.png">

**Comment by vrindanayak** [comment]
Use [dcm4che forum](https://groups.google.com/forum/#!forum/dcm4che) to post questions and not the issue tracker! The error is not from archive side.
