### ISSUE TITLE
bower build failed on UI module 

### ISSUE THREAD

**Issue by smartriyaz** [dcm4che/dcm4chee-arc-light#1723]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by shral** [comment]
Hi @smartriyaz 
we are using [yarn](https://yarnpkg.com/lang/en/) and not bower, we don't support bower so pleas try with yarn or if you use maven for the whole project, maven will automatically install and call yarn.
Best Regards
