### ISSUE TITLE
build failed on  UI module

### ISSUE THREAD

**Issue by OrNot** [dcm4che/dcm4chee-arc-light#177]
failed on Ubuntu 16.04 LTS   . I am not very familiar with  bower  and got this output.

[INFO] Please note that,
[INFO]     angular-schema-form#0.8.13 depends on tv4#~1.0.15 which resolved to tv4#1.0.17
[INFO]     dcm4chee-arc-ui depends on tv4#~1.2.7 which resolved to tv4#1.2.7
[INFO] Resort to using tv4#~1.0.15 which resolved to tv4#1.0.17
[INFO] Code incompatibilities may occur.
[INFO] 
[ERROR] bower angular                          resolution Unsuitable resolution declared for angular: 1.5.5
[ERROR] bower                                   ECONFLICT Unable to find suitable version for angular

**Comment by shral** [comment]
We updated the js-libraries and the bower.json file, now it should work (we tested it on Debian 8)

**Comment by osantanen** [comment]
build failed on UI module
on Ubuntu 14.04 LTS . I am not either familiar with bower and got this output and I do not know how to resolve the problem?
------------------------------------------------------------------------
Building dcm4chee-arc-ui 5.9.0
------------------------------------------------------------------------

--- maven-clean-plugin:2.5:clean (default-clean) @ dcm4chee-arc-ui ---

--- frontend-maven-plugin:1.2:install-node-and-npm (install node and npm) @ dcm4chee-arc-ui ---
Node v4.6.0 is already installed.
NPM 2.15.9 is already installed.

--- frontend-maven-plugin:1.2:npm (npm install) @ dcm4chee-arc-ui ---
Running 'npm install' in /home/olli/Lataukset/dcm4chee-arc-light-master-5.9.0/dcm4chee-arc-ui

--- frontend-maven-plugin:1.2:bower (bower install) @ dcm4chee-arc-ui ---
Running 'bower install' in /home/olli/Lataukset/dcm4chee-arc-light-master-5.9.0/dcm4chee-arc-ui
bower bootstrap#^3.3.6          cached https://github.com/twbs/bootstrap.git#3.3.7
bower bootstrap#^3.3.6        validate 3.3.7 against https://github.com/twbs/bootstrap.git#^3.3.6
bower angular#^1.5.7            cached https://github.com/angular/bower-angular.git#1.6.1
bower angular#^1.5.7          validate 1.6.1 against https://github.com/angular/bower-angular.git#^1.5.7
bower vex#^2.3.4                cached https://github.com/HubSpot/vex.git#2.3.4
bower vex#^2.3.4              validate 2.3.4 against https://github.com/HubSpot/vex.git#^2.3.4
bower angular-loading-bar#^0.9.0           cached https://github.com/chieffancypants/angular-loading-bar.git#0.9.0
bower angular-loading-bar#^0.9.0         validate 0.9.0 against https://github.com/chieffancypants/angular-loading-bar.git#^0.9.0
bower tv4#^1.2.7                           cached https://github.com/geraintluff/tv4.git#1.2.7
bower tv4#^1.2.7                         validate 1.2.7 against https://github.com/geraintluff/tv4.git#^1.2.7
bower angular-route#^1.5.7                 cached https://github.com/angular/bower-angular-route.git#1.6.1
bower angular-route#^1.5.7               validate 1.6.1 against https://github.com/angular/bower-angular-route.git#^1.5.7
bower angular-sanitize#^1.5.7              cached https://github.com/angular/bower-angular-sanitize.git#1.6.1
bower angular-sanitize#^1.5.7            validate 1.6.1 against https://github.com/angular/bower-angular-sanitize.git#^1.5.7
bower angular-schema-form#^0.8.13          cached https://github.com/Textalk/angular-schema-form.git#0.8.13
bower angular-schema-form#^0.8.13        validate 0.8.13 against https://github.com/Textalk/angular-schema-form.git#^0.8.13
bower angular-touch#^1.5.7                 cached https://github.com/angular/bower-angular-touch.git#1.6.1
bower angular-touch#^1.5.7               validate 1.6.1 against https://github.com/angular/bower-angular-touch.git#^1.5.7
bower objectpath#^1.2.1                    cached https://github.com/mike-marcacci/objectpath.git#1.2.1
bower objectpath#^1.2.1                  validate 1.2.1 against https://github.com/mike-marcacci/objectpath.git#^1.2.1
bower jquery#^3.0.0                        cached https://github.com/jquery/jquery-dist.git#3.1.1
bower jquery#^3.0.0                      validate 3.1.1 against https://github.com/jquery/jquery-dist.git#^3.0.0
bower angular-clockpicker#^1.1.1           cached https://github.com/linagora/angular-clockpicker.git#1.1.1
bower angular-clockpicker#^1.1.1         validate 1.1.1 against https://github.com/linagora/angular-clockpicker.git#^1.1.1
bower angular-datepicker#^2.0.3            cached https://github.com/g00fy-/angular-datepicker.git#2.0.3
bower angular-datepicker#^2.0.3          validate 2.0.3 against https://github.com/g00fy-/angular-datepicker.git#^2.0.3
bower jsondiffpatch#^0.1.43                cached https://github.com/benjamine/JsonDiffPatch.git#0.1.43
bower jsondiffpatch#^0.1.43              validate 0.1.43 against https://github.com/benjamine/JsonDiffPatch.git#^0.1.43
bower angular-bootstrap#^1.3.3             cached https://github.com/angular-ui/bootstrap-bower.git#1.3.3
bower angular-bootstrap#^1.3.3           validate 1.3.3 against https://github.com/angular-ui/bootstrap-bower.git#^1.3.3
bower file-saver#^1.3.2                    cached https://github.com/eligrey/FileSaver.js.git#1.3.3
bower file-saver#^1.3.2                  validate 1.3.3 against https://github.com/eligrey/FileSaver.js.git#^1.3.2
bower moment#^2.13.0                       cached https://github.com/moment/moment.git#2.17.1
bower moment#^2.13.0                     validate 2.17.1 against https://github.com/moment/moment.git#^2.13.0
bower angular-contextmenu#^0.2.0           cached https://github.com/ds82/angular-contextmenu.git#0.2.0
bower angular-contextmenu#^0.2.0         validate 0.2.0 against https://github.com/ds82/angular-contextmenu.git#^0.2.0
bower tv4#~1.0.15                          cached https://github.com/geraintluff/tv4.git#1.0.17
bower tv4#~1.0.15                        validate 1.0.17 against https://github.com/geraintluff/tv4.git#~1.0.15
bower objectpath#~1.1.0                    cached https://github.com/mike-marcacci/objectpath.git#1.1.0
bower objectpath#~1.1.0                  validate 1.1.0 against https://github.com/mike-marcacci/objectpath.git#~1.1.0
bower angular-sanitize#>= 1.2              cached https://github.com/angular/bower-angular-sanitize.git#1.6.1
bower angular-sanitize#>= 1.2            validate 1.6.1 against https://github.com/angular/bower-angular-sanitize.git#>= 1.2
bower moment#~2.10.6                       cached https://github.com/moment/moment.git#2.10.6
bower moment#~2.10.6                     validate 2.10.6 against https://github.com/moment/moment.git#~2.10.6
bower angular#1.2.14                       cached https://github.com/angular/bower-angular.git#1.2.14
bower angular#1.2.14                     validate 1.2.14 against https://github.com/angular/bower-angular.git#1.2.14
bower lng-clockpicker#~0.0.8               cached https://github.com/linagora/clockpicker.git#0.0.9
bower lng-clockpicker#~0.0.8             validate 0.0.9 against https://github.com/linagora/clockpicker.git#~0.0.8
bower ng-device-detector#~1.1.7            cached https://github.com/srfrnk/ng-device-detector.git#1.1.9
bower ng-device-detector#~1.1.7          validate 1.1.9 against https://github.com/srfrnk/ng-device-detector.git#~1.1.7
bower moment-timezone#~0.4.1               cached https://github.com/moment/moment-timezone.git#0.4.1
bower moment-timezone#~0.4.1             validate 0.4.1 against https://github.com/moment/moment-timezone.git#~0.4.1
bower angular-moment#1.0.0-beta.3          cached https://github.com/urish/angular-moment.git#1.0.0-beta.3
bower angular-moment#1.0.0-beta.3        validate 1.0.0-beta.3 against https://github.com/urish/angular-moment.git#1.0.0-beta.3
bower re-tree#^0.0.2                       cached https://github.com/srfrnk/re-tree.git#0.0.2
bower re-tree#^0.0.2                     validate 0.0.2 against https://github.com/srfrnk/re-tree.git#^0.0.2

Please note that,
    angular-schema-form#0.8.13 depends on tv4#~1.0.15 which resolved to tv4#1.0.17
    dcm4chee-arc-ui depends on tv4#^1.2.7 which resolved to tv4#1.2.7
Resort to using tv4#~1.0.15 which resolved to tv4#1.0.17
Code incompatibilities may occur.

bower angular                          resolution Unsuitable resolution declared for angular: 1.5.8
bower                                   ECONFLICT Unable to find suitable version for angular
------------------------------------------------------------------------
BUILD FAILURE

**Comment by gunterze** [comment]
Fixed by  c00dde2

**Comment by osantanen** [comment]
The fixed bower.json resolved the problem, and now the build of UI module succeeds. Thanks!
