### ISSUE TITLE
Support range matching of Study Access Date Time for RESTful services

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1774]
Support range matching of Study Access Date Time (_Query Parameter_: `StudyAccessDateTime=<date-time-range>`) for following RESTful Services : 
- [QIDO-RS](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger-dicom.json#/QIDO-RS) 
- [COUNT-RS](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/COUNT-RS) 
- [Size of Studies](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/MONITOR-RS/SizeOfStudies) 
- [Apply Retention Policy](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/IOCM-RS/applyRetentionPolicy)

- Export Matching RS
   - [Export Matching Studies](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/exportMatchingStudies)
   - [Export Matching Series](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/exportMatchingSeries)
   - [Export Matching Series of Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/exportMatchingSeriesOfStudy) 
   - [Export Matching Instances](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/exportMatchingInstances)
   - [Export Matching Instances of Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/exportMatchingInstancesOfStudy) 
   - [Export Matching Instances of Series of Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/EXPORT-RS/exportMatchingInstancesOfSeries) 

- Storage Verification Matching RS
   - [Schedule Storage Verification of Studies](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/STGVER-RS/ScheduleStorageVerificationOfStudies)
   - [Schedule Storage Verification of Series](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/STGVER-RS/ScheduleStorageVerificationOfSeries)
   - [Schedule Storage Verification of Series of Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/STGVER-RS/ScheduleStorageVerificationOfSeriesOfStudy) 
   - [Schedule Storage Verification of Instances](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/STGVER-RS/ScheduleStorageVerificationOfInstances)
   - [Schedule Storage Verification of Instances of Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/STGVER-RS/ScheduleStorageVerificationOfInstancesOfStudy) 
   - [Schedule Storage Verification of Instances of Series of Study](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/STGVER-RS/ScheduleStorageVerificationOfInstancesOfSeries)

**Comment by sgala** [comment]
Hi, I'm testing in 5.22.3 and setting StudyAccessDateTime, both in the UI and in QIDO calls, does not make any difference on the results of the query.

In particular I receive studies just accessed and with an access_time in August 2020 from queries with StudyAccessDateTime=-20191231

Taking a quick look at the source I notice an asymmetry between StudyAccessDateTime and StudyReceiveDateTime

```
$ git grep -l StudyAccessDateTime >/tmp/access.diff
$ git grep -l StudyReceiveDateTime >/tmp/receive.diff
$ diff -u /tmp/access.diff /tmp/receive.diff 
--- /tmp/access.diff    2020-08-12 17:35:02.754204992 +0200
+++ /tmp/receive.diff   2020-08-12 17:35:22.874746250 +0200
@@ -1,6 +1,8 @@
 dcm4chee-arc-query-util/src/main/java/org/dcm4chee/arc/query/util/QueryAttributes.java
+dcm4chee-arc-query-util/src/main/java/org/dcm4chee/arc/query/util/QueryBuilder.java
 dcm4chee-arc-query/src/main/java/org/dcm4chee/arc/query/impl/StudyQuery.java
 dcm4chee-arc-ui2/src/app/constants/globalvar.ts
+dcm4chee-arc-ui2/src/app/interfaces.ts
 dcm4chee-arc-ui2/src/swagger/parameters.json
 dcm4chee-arc-ui2/src/swagger/paths/export.json
 dcm4chee-arc-ui2/src/swagger/paths/find.json
```

**Comment by vrindanayak** [comment]
@sgala : Thank you for reporting this. Will be fixed by #2716

**Comment by sgala** [comment]
Cool, thanks.

A procedural comment: I tend to comment on related closed issues, for instance for regressions or typos, rather than opening one new. In this way you can "debug" my comment and dismiss it straight away rather than having to deal with the whole issue workflow of a new issue.

Please tell me if you prefer that I go straight away for a new issue.

**Comment by vrindanayak** [comment]
We don't mind if a new issue is directly opened, provided it is really a bug and can be reproduced/simulated. If one is unsure or it's merely a query, then we encourage to post it first in the forum as we answer the questions there and if required we open an issue here accordingly.
