### ISSUE TITLE
UI: get 404 on http://localhost:8080/dcm4chee-arc/ui2.

### ISSUE THREAD

**Issue by Refun007** [dcm4che/dcm4chee-arc-light#1782]
**Desktop (please complete the following information):**
 - OS: Centos7
 - Browser: Firefox
 - Version :dcm4chee-arc-5.15.1-mysql

When I deploy $DCM4CHEE_ARC/deploy/dcm4chee-arc , I can't get the info about "Start TCP Listener on /0.0.0.0:11112 ....... and WFLYUT0021: Registered web context: /dcm4chee-arc/ui2....."
so I can't load the page http://localhost:8080/dcm4chee-arc/ui2. 
Did I miss some steps??
Thanks in advance.

**Comment by vrindanayak** [comment]
Please ask questions in [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che)!
