### ISSUE TITLE
Replace QueryDSL by JPA Criteria API

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1806]
QueryDSL 4.x is incompatible with Hibernate 5.3.x used by Wildfly 14+.
Future development of QueryDSL seems unsure - last commit at [GitHub](https://github.com/querydsl/querydsl/commits/master) was on Mar 22, 2018!

Replace QueryDSL by JPA Criteria API in module
- [x] dcm4chee-arc-diff
- [x] dcm4chee-arc-diff-rs
- [x] dcm4chee-arc-entity
- [x] dcm4chee-arc-export-mgt
- [x] dcm4chee-arc-export-rs
- [x] dcm4chee-arc-iocm-rs
- [x] dcm4chee-arc-qido
- [x] dcm4chee-arc-qmgt
- [x] dcm4chee-arc-qmgt-rs
- [x] dcm4chee-arc-query
- [x] dcm4chee-arc-query-scp
- [x] dcm4chee-arc-query-util
- [x] dcm4chee-arc-stgcmt
- [x] dcm4chee-arc-stgcmt-rs
- [x] dcm4chee-arc-retrieve
- [x] dcm4chee-arc-retrieve-mgt
- [x] dcm4chee-arc-retrieve-rs

**Comment by doc-jay** [comment]
thanks for this - finally allows us to move forward with more recent versions of wildfly and keycloak!
