### ISSUE TITLE
QIDO responds with 500 while uploading with parallel STOWs

### ISSUE THREAD

**Issue by spalte** [dcm4che/dcm4chee-arc-light#1877]
**Describe the bug**
dcm4chee 16.0 responds with 500 errors when doing a series level QIDO while many instances of the same study are uploading.
See log [server.log](https://github.com/dcm4che/dcm4chee-arc-light/files/3004287/server.log)

**To Reproduce**
1. Send a full Study using 6 parallel STOW requests
2. Send QIDO requests for series in the recently uploaded study simultaneously.

**Desktop (please complete the following information):**
 - OS: Docker Centos
 - Version 16.0

**Comment by gunterze** [comment]
Should be fixed by  #1849
