### ISSUE TITLE
UI : Enable to send Storage Commitment request to an External Archive for Study/Series/Instance

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#1887]
- [Request Storage Commitment of Study from external Storage Commitment SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/STGCMT-RS/RequestStorageCommitmentOfStudyExternal)
- [Request Storage Commitment of Series from external Storage Commitment SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/STGCMT-RS/RequestStorageCommitmentOfSeriesExternal)
- [Request Storage Commitment of Instance from external Storage Commitment SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/STGCMT-RS/RequestStorageCommitmentOfInstanceExternal)

RESTful service implemented by #1871

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/80377668-e1556580-889b-11ea-829b-a8bf37611bbb.png)

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/80378153-8708d480-889c-11ea-8ba0-6c7310955c8f.png)

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/80378274-b3bcec00-889c-11ea-9d06-a4225a9d8613.png)

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/80378379-de0ea980-889c-11ea-8c86-501534ddeb91.png)

**Comment by vrindanayak** [comment]
The `Storage Commitment SCP AE Title` dropdown shall contain list of external AETs. Current dropdown shows AE titles of its own archive!
