### ISSUE TITLE
UI : Enable to send Storage Commitment request to an external archive for matching studies

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#1888]
- [Schedule Storage Commitment of matching Studies from external Storage Commitment SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/STGCMT-RS/ScheduleStorageCommitmentOfMatchingStudiesExternal)

Currently on Studies page, `Storage Verification` is shown when `External` is selected, but the service invoked is for own archive. On implementation of #1802, label can be improved to `Storage Commitment multiple studies` since it is Storage Commitment request to external archive.

RESTful services implemented by #1872

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/80376057-90dd0880-8899-11ea-9ac9-fd421f7d78de.png)

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/80376185-bcf88980-8899-11ea-845c-c974052a0b7d.png)

**Comment by vrindanayak** [comment]
The `Storage Commitment SCP AE Title` dropdown shall contain list of external AETs. Current dropdown shows AE titles of its own archive!
