### ISSUE TITLE
UI : Enable to send Instance Availability Notification request to an external IAN SCP for matching studies

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#1896]
- [Schedule Instance Availability Notification of matching Studies to external Instance Availability Notification SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/IAN-RS/ScheduleInstanceAvailabilityNotificationOfMatchingStudiesExternal)

RESTful service implemented by #1875

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/80507462-2ac6b300-8977-11ea-8863-1bc9dd8bedf4.png)

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/80507594-47fb8180-8977-11ea-8d5c-4c276913542e.png)
