### ISSUE TITLE
Secure WiIdFly Admin Endpoint with TLS in archive and keycloak docker images

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#1948]
HTTPS port configurable by docker environment variable

#### `MANAGEMENT_HTTPS_PORT`

This environment variable sets the Management Https port of Wildfly. Default value is `9993`.

Requests to the http management port will be [redirected to the management https port](https://issues.jboss.org/browse/WFCORE-2673).

Use same Keystore as configured for the https endpoint of UI and RESTful services configurable by docker environment variables:

#### `KEYSTORE`

This environment variable sets the keystore used in ssl server identities in Wildfly configuration. Default value is
`/opt/wildfly/standalone/configuration/dcm4chee-arc/key.jks`.

#### `KEYSTORE_PASSWORD`

This environment variables sets the password of the keystore used in ssl server identities in Wildfly configuration.
Only effective if the file specified by `KEYSTORE_PASSWORD_FILE` does not exist. Default value is `secret`.

#### `KEYSTORE_PASSWORD_FILE`

Path to file containing the password of the keystore used in ssl server identities in Wildfly configuration.
If the file does not exist, it will be created containing the password specified by `KEYSTORE_PASSWORD`. 
Default value is `/tmp/keystore_password`.

#### `KEY_PASSWORD`

This environment variables sets the password of the key used in ssl server identities in Wildfly configuration.
Only effective if the file specified by `KEY_PASSWORD_FILE` does not exist. Default value is `secret`.

#### `KEY_PASSWORD_FILE`

Path to file containing the password of the key used in ssl server identities in Wildfly configuration.
If the file does not exist, it will be created containing the password specified by `KEY_PASSWORD`. 
Default value is `/tmp/key_password`.

#### `KEYSTORE_TYPE`

This environment variable sets the type of keystore that is used above. Default value is `JKS`.

**Comment by gunterze** [comment]
Seems there is an issue combining TLS with authentication by Keycloak:
https://developer.jboss.org/message/989058
