### ISSUE TITLE
Not able to connect with de UI

### ISSUE THREAD

**Issue by marinamota18** [dcm4che/dcm4chee-arc-light#1964]
I did every step from this page: https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation, I can start the wildfly without error, but the page http://localhost:8080/dcm4chee-arc/ui2 is not loading, and at the wildfly server does not show any error. Does any one could help me ?

**Comment by vrindanayak** [comment]
Please ask questions in [dcm4che user forum](https://groups.google.com/forum/#!forum/dcm4che)!
