### ISSUE TITLE
LDAP: error code 64 - value of naming attribute 'dcmuiPermissionName' is not present in entry

### ISSUE THREAD

**Issue by viss3595** [dcm4che/dcm4chee-arc-light#1982]
when I Import **default-ui-config.ldif** configuration into LDAP Server.

I try this Steps.

1. Install Apache Directory Studio 2.0.0-M9 and create a new LDAP Connection with:

Network Parameter:
    Hostname: localhost
    Port:     10389
Authentication Parameter:
    Bind DN or user: uid=admin,ou=system
    Bind password:   secret

2. Import LDAP schema files for Apache DS:

$DCM4CHEE_ARC/ldap/apacheds/dicom.ldif
$DCM4CHEE_ARC/ldap/apacheds/dcm4che.ldif
$DCM4CHEE_ARC/ldap/apacheds/dcm4chee-archive.ldif
$DCM4CHEE_ARC/ldap/apacheds/dcm4chee-archive-ui.ldif

3. One may modify the default Directory Base DN dc=example,dc=com by changing the value of attribute

ads-partitionsuffix: dc=dcm4che,dc=org`
of object

ou=config
+ ads-directoryServiceId=default
  + ou=partitions
      ads-partitionId=example

to ads-partitionId=dcm4che

4. restart the Apache DS service to effect the above changes.

5. Change previous Network Parameter:
    Hostname: localhost
    Port:     389
Authentication Parameter:
    Bind DN or user: cn=admin,dc=dcm4che,dc=org
    Bind password:   secret
Browser Options:
    Base DN: dc=dcm4che,dc=org

6. If one configured a different Directory Base DN thandc=dcm4che,dc=org, one has to replace all occurrences of dc=dcm4che,dc=org in LDIF files

$DCM4CHEE_ARC/ldap/init-baseDN.ldif
$DCM4CHEE_ARC/ldap/init-config.ldif
$DCM4CHEE_ARC/ldap/default-config.ldif
$DCM4CHEE_ARC/ldap/default-ui-config.ldif (This Ldif file is not import)

#!ERROR [LDAP: error code 64 - value of naming attribute 'dcmuiPermissionName' is not present in entry]

######ERROR#########

![image](https://user-images.githubusercontent.com/22858445/57504445-1d518c80-7312-11e9-861c-442c2519eb99.png)

**Comment by vrindanayak** [comment]
Please ask questions in [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che)

I've rechecked the schemas and ldif files, `dcmuiPermissionName` entry is available. You may search for this attribute in your schema, if it is not available, there might have been some issue during import of dcm4chee-archive-ui.ldif file. You may delete the ldif, re-import and try again.
