### ISSUE TITLE
Optionally ensure uniqueness of Patient IDs by supplementing Issuer of Patient ID derived from other Patient Attributes

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#1991]
Optionally ensure uniqueness of Patient IDs by supplementing Issuer of Patient ID derived from other Patient Attributes configurable by [Archive Attribute Coercion](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveAttributeCoercion.html#archive-attribute-coercion) Attribute

Name | Type | Description (LDAP Attribute)
-- | -- | --
Issuer of Patient ID Format | string | Format of Issuer of Patient ID (0010,0021) derived from other attributes. E.g. '{00100010,hash}-{00100030}': use hash value of Patient Name and Birth Date separated by '-'. For coercion of existing values of Issuer of Patient ID in received objects also **Nullify Issuer of Patient ID** must be set accordingly.  (dcmIssuerOfPatientIDFormat)

Rational: Avoid merging of Patient Records receiving objects with non-unique Patient IDs. 

Related #1990

**Comment by brunobart** [comment]
For example if i want to concat (0010,0021) "Universal Entity ID Type" with 0010,0024 "Issuer of Patient ID Qualifiers Sequence" and with 0008,0080 "Institution Name"
{0010,002}&{0010,0024}&{0008,0080} as format will be nice (?)
