### ISSUE TITLE
Decrease update study query attributes interval from 10 minutes to 1 minute or less

### ISSUE THREAD

**Issue by bhavesh-pandey** [dcm4che/dcm4chee-arc-light#2003]
I need to update the study query attributes at every 1 minute or less. It's happening currently at 10 minutes. I can't find that option in configuration. That is very important for the work I am doing. Kindly help.

If there is any configuration which I can do to update the study query attributes as soon as an image is received then it that will be the best. Can you please suggest if there is anything like this.

Or if there is any API which I can call to update the study query attributes ?

**Comment by bhavesh-pandey** [comment]
I updated every interval parameter to 1 minute in the Configuration > devicelist > dcm4chee-arc > Device Extension > Archive Device (For Example: Update Series Metadata Polling Interval). Still no luck. Please help. Thanks.

**Comment by gunterze** [comment]
Eager calculation of study query attributes can only be triggered by receive of an object. Why you want to trigger them periodically. They are anyway calculated lazily on query, if they are not yet set.
Please post further questions in the [dcm4che google group](https://groups.google.com/forum/#!forum/dcm4che).

**Comment by bhavesh-pandey** [comment]
Thanks for the reply. Where can I configure them in UI ? Both the links you have attached are codes. 

I have asked the question on google group (https://groups.google.com/forum/#!topic/dcm4che/mP7wu46TbtQ). 

Kindly reply there if you know this. 
I really appreciate your time and response.

**Comment by bhavesh-pandey** [comment]
Thanks for the reply with the screenshot. Our team really appreciated the quick response.

We did the configuration you suggested but I guess the problem we are trying to solve is different. I guess the study is not going in the queue of SCHEDULED itself. Its in TO SCHEDULED status.

I updated the response https://groups.google.com/forum/#!topic/dcm4che/mP7wu46TbtQ

I know we are bugging you for small queries. Please help.

**Comment by bhavesh-pandey** [comment]
Hi, can you please tell me how to set the issuer of patient ID?

I am trying this: https://github.com/dcm4che/dcm4chee-arc-light/issues/1991

Here is the google group link for the question (https://groups.google.com/forum/#!topic/dcm4che/hVsMG4_xK4s). Thanks
