### ISSUE TITLE
JPEG colors space issue with STOW

### ISSUE THREAD

**Issue by nroduit** [dcm4che/dcm4chee-arc-light#2022]
**Describe the bug**
This jpg image has no color-space metadata and no embedded color profile.
In dicom, the RGB color model is applied instead of YBR_FULL_422 (for lossy jpeg), even when setting  "00280004":{"vr":"CS","Value":["YBR_FULL_422"]} in json.

**To Reproduce**
Send the following image by STOW with the jpeg lossy syntax (1.2.840.10008.1.2.4.50)
![Macaca_selfie](https://user-images.githubusercontent.com/993975/59107662-6c9ed300-8939-11e9-83ee-28f2725f4ae1.jpg)

**Expected behavior**
In dcm4chee, the image should be rendered as it is above.

**Screenshots**
In dcm4chee:
![Sélection_003](https://user-images.githubusercontent.com/993975/59107957-1a11e680-893a-11e9-8363-f4cf697c0626.png)

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - fresh docker deploy (2.16.1 and 2.17.0)

**Comment by gunterze** [comment]
Caused by https://github.com/dcm4che/dcm4che/issues/469
