### ISSUE TITLE
Nullify Issuer of Patient ID configuration is not there in v5.17.0

### ISSUE THREAD

**Issue by bhavesh-pandey** [dcm4che/dcm4chee-arc-light#2024]
Hi I am trying to set Issuer of Patient ID field in the dcm-arc-light server but its not reflecting. In the issue https://github.com/dcm4che/dcm4chee-arc-light/issues/1991 its written to set Nullify Issuer of Patient ID but I cant find this configuration anywhere.

I am setting Issuer of Patient ID exactly as this {00100010,patientName-patientId}-{00100030}, is this correct ?

**Comment by bhavesh-pandey** [comment]
I updated dcm-arc-light version to 5.17.0 but this option is still not there

**Comment by bhavesh-pandey** [comment]
We don't want to merge studies with same patient ID, kindly help us in configuring that.

**Comment by vrindanayak** [comment]
Please ask questions in [dcm4che User forum](https://groups.google.com/forum/#!forum/dcm4che). This LDAP attribute is part of [Archive Attribute Coercion](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveAttributeCoercion.html#archive-attribute-coercion) child object
