### ISSUE TITLE
Issue : dcm4chee-arc-ear-5.17.0-psql-secure-ui.ear deployment failing with below error

### ISSUE THREAD

**Issue by chandrapenumarthi** [dcm4che/dcm4chee-arc-light#2058]
dcm4chee-arc-ear-5.17.0-psql-secure-ui.ear failing with below error

 "jboss.module.service.\"deployment.dcm4chee-arc-ear-5.17.0-psql-secure-ui.ear.dcm4chee-arc-mpps-5.17.0.jar\".main" => "WFLYSRV0179: Failed to load module: deployment.dcm4chee-arc-ear-5.17.0-psql-secure-ui.ear.dcm4chee-arc-mpps-5.17.0.jar
    Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core"
}}

Keycloak is configured and able to run on 8880 port. When i am deploying the ear file throughing above exception Caused by: org.jboss.modules.ModuleNotFoundException: org.keycloak.keycloak-core"

**Comment by vrindanayak** [comment]
Please ask questions in [dcm4che user forum](https://groups.google.com/forum/#!forum/dcm4che)

See point

![image](https://user-images.githubusercontent.com/15785031/60498602-35f97580-9cb7-11e9-873e-f2fcf1cce554.png)

in [Secure Archive UI and RESTful Services using Keycloak](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Secure-Archive-UI-and-RESTful-Services-using-Keycloak)
