### ISSUE TITLE
getting Caused by: org.postgresql.util.PSQLException: ERROR: relation "study" does not exist   Position: 265

### ISSUE THREAD

**Issue by chandrapenumarthi** [dcm4che/dcm4chee-arc-light#2071]
Getting exception after Secured UI and Unsecured RESTful services configuration.
https://github.com/dcm4che/dcm4chee-arc-light/wiki/Secure-Archive-UI-and-RESTful-Services-using-Keycloak#Secured-UI-and-Unsecured-RESTful-services

followed this link.. showing the exception for all tables.. but the tables are exist in the database.

**Comment by vrindanayak** [comment]
Please use [dcm4che user forum](https://groups.google.com/forum/#!forum/dcm4che) for questions
