### ISSUE TITLE
Upgrade 5.16.2 to 5.17.1 problems

### ISSUE THREAD

**Issue by phelys** [dcm4che/dcm4chee-arc-light#2082]
I try to upgrade to 5.17.1 version, but when I do it, in step to import $DCM4CHEE_ARC/ldap/apacheds/dcm4che.ldif, a error appear every time, returned: LDAP error code 17, m-dependencies: attribute type undefined some idea?

**Comment by vrindanayak** [comment]
The only change between these 2 versions in [apache-ds dcm4che-ldif](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-conf/dcm4che-conf-ldap-schema/src/main/resources/ldap/apacheds/dcm4che.ldif) file was addition of `dcmRoleSelectionNegotiationLenient` attribute. The definition and its usages are present in the file and also in the file present in [5.17.1 release package](https://sourceforge.net/projects/dcm4che/files/dcm4chee-arc-light5/5.17.1/dcm4chee-arc-5.17.1-psql.zip/download).

Please post further questions in [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che).

**Comment by phelys** [comment]
Thanks @vrindanayak I will try again just adding dcmRoleSelectionNegotiationLenient attribute and follow other steps
