### ISSUE TITLE
Test and document configuration of accept Rejection Notes received before the referenced objects

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2084]
Related #1451 #2083

Test Rejection Types
-  Patient Safety
-  Data Retention Expiry
-  Quality 

with Instances received
- before Rejection Note
- after Rejection Note but before configured Accept Previous Rejected Instance time
- after Rejection Note and after configured Accept Previous Rejected Instance time

with Instance records
- not purged
- purged

Test purging of instance records after the rejection (was not possible before #1451 )

Test restoring of rejected instances

**Comment by vrindanayak** [comment]
[Reject Instances of Study](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Reject-Instances-of-Study)
