### ISSUE TITLE
UI: Import a single JPEG 2000 (JP2) image on the local filesystem to a study in the archive using STOW-RS

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2091]
Import a single JPEG 2000 (JP2) image on the local filesystem to a study in the archive  - or referred in an MWL item in the archive - by a STOW-RS Metadata and Bulkdata request, with `Content-Type: image/jp2`

Requires #2088

**Comment by vrindanayak** [comment]
Fixed by #4276
