### ISSUE TITLE
i install dcm4che/dcm4chee-arc-psql:5.17.1 and  i upload the dicom file that time it's throwing SQLGrammarException.

### ISSUE THREAD

**Issue by viss3595** [dcm4che/dcm4chee-arc-light#2093]
### Anyone can help me. what I doing wrong in this situation.
`Error 409 Conflict`

![image](https://user-images.githubusercontent.com/22858445/61607382-1a590d80-ac6c-11e9-8ca4-40b1bef2ebb9.png)

javax.ejb.EJBException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by gunterze** [comment]
Guess something goes wrong creating the tables in your DB. Post further question in the [dcm4che google group](https://groups.google.com/forum/#!forum/dcm4che).
