### ISSUE TITLE
RESTful service: List Web Applications - Suppress Keycloak Client ID for local Web Services

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2101]
Suppress Keycloak Client ID in returned list of Web Applications by [GET /dcm4chee-arc/webapps](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/CONFIG-RS/listWebApplications) for Web Applications secured by the same Keycloak realm as the UI of this Archive instance, where following System and KeycloakClient properties matches:

System property | Keycloak Client property
-- | --
`System.getProperty("auth-server-url")` | `keycloakServerURL`
`System.getProperty("realm-name", "dcm4che")` | `keycloakRealm`

*Rationale:*
Simplify for the UI to distinguish, if it has to fetch a new token by [GET ​/token2​/{webAppName}](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/AUTH-RS/getAccessToken) or it can use the token it already has fetched from Keycloak.

Improves #1331
Requires dcm4che/dcm4che#509

**Comment by petrkalina** [comment]
I believe it is relevant to check also if the keycloak client ID is `dcm4chee-arc-ui` - otherwise the client id is not returned for i.e.:

```
dn: dcmKeycloakClientID=arr-gatekeeper,dicomDeviceName=log,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
objectClass: dcmKeycloakClient
dcmKeycloakClientID: arr-gatekeeper
dcmKeycloakRealm: dcm4che
dcmURI: https://auth:8843/auth
dcmKeycloakClientSecret: {secret}
dcmTLSAllowAnyHostname: TRUE
```
