### ISSUE TITLE
RESTful service to create DB entries for a given list of DICOM Composite objects on a storage system

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2105]
[POST /dcm4chee-arc/aets​/{aet}​/rs​/instances​/storage​/{StorageID}](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IMPORT-RS/ImportInstances)

The request payload shall contain a list of storage paths delimited by line breaks (CRLF).

*Rational:*
Enables migration to dcm4chee-arc without (re-)sending the objects.

*Usage e.g.:*
```
$ cd path/to/old/storage/directory
$ find 2010/10 -type f | curl -v -H "Content-Type: text/plain" --data-binary - http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/instances/storage/migrated-data
```

**Comment by innowave2024** [comment]
Hi I am using the script
find 2010 -type f | curl -v -H "Content-Type: text/plain" --data-binary @- http://localhost:8080/dcm4chee-arc/aets/FREEDOM/rs/instances/storage/migrated-data

but getting error 

HTTP/1.1 500 internal server error

I am having data aroung 400 GB in each folder and 
Dicom4chee arc running on ubuntu 22.04 virtual machine with mysql database

Any help would be appreciated
