### ISSUE TITLE
dcm4chee-arc-5.18.0-psql.zip on sourceforge contains wrong jdbc module

### ISSUE THREAD

**Issue by ixM** [dcm4che/dcm4chee-arc-light#2121]
**Describe the bug**
In the "manual" installation procedure, the point 7 of the "Setup Wildfly" section suggests to unzip the content of the relevant JDBC driver shipped with the distribution. In the case of the psql version (downloaded on sourceforge: dcm4chee-arc-5.18.0-psql.zip), the file named $DCM4CHEE_ARC/jboss-modules/jdbc-jboss-modules-1.0.0-psql.zip contains the mariadb module.xml and no JDBC driver.

**To Reproduce**
1. Go to sourceforge to download the PostgreSQL distribution of dcm4chee-arc version 5.18.0 (https://sourceforge.net/projects/dcm4che/files/dcm4chee-arc-light5/5.18.0/)
2. Download the psql version (the psql-secure is also affected) : https://sourceforge.net/projects/dcm4che/files/dcm4chee-arc-light5/5.18.0/dcm4chee-arc-5.18.0-psql.zip/download
3. Unzip the downloaded file to $DCM4CHEE_ARC directory
4. Unzip the $DCM4CHEE_ARC/jboss-modules/jdbc-jboss-modules-1.0.0-psql.zip and see that this zip only contains modules/org/mariadb/main/module.xml

**Expected behavior**
The $DCM4CHEE_ARC/jboss-modules/jdbc-jboss-modules-1.0.0-psql.zip should contain two files: modules/org/postgresql/main/module.xml and modules/org/postgresql/main/postgresql-42.1.4.jar

**Additional context**
This error is not present when installing DCM4CHEE using docker

**Comment by gunterze** [comment]
Read [Installation, Setup WildFly](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#setup-wildfly):

> 7. Except for H2, one has to install the JDBC Driver for the database. DCM4CHEE Archive light 5.x binary distributions do not include a JDBC driver for the database for license issues...
> :
> For installation as a core module, $DCM4CHEE_ARC/jboss-modules/jdbc-jboss-modules-1.0.0-<database>.zip already provides a module definition file module.xml. Just extract the ZIP file into $WILDFLY_HOME **and copy the JDBC Driver file(s) into the sub-directory** ..
>

**Comment by ixM** [comment]
Ok, sorry I missed that.

Nonetheless, the file that is present in the distribution is wrong as it references the mariadb JDBC driver.

**Comment by gunterze** [comment]
Right. Just uploaded fixed binary distribution packages for postgres to sf.net. You may also just [download  the correct jdbc-jboss-modules-1.0.0-psql.zip ](https://www.dcm4che.org/maven2/org/dcm4che/jdbc-jboss-modules/1.0.0/jdbc-jboss-modules-1.0.0-psql.zip).
