### ISSUE TITLE
Illegal access to operation warning is displayed while running the docker and server doesn't start.

### ISSUE THREAD

**Issue by bhavesh-pandey** [dcm4che/dcm4chee-arc-light#2143]
![Screenshot 2019-08-29 at 10 38 29 PM](https://user-images.githubusercontent.com/23245538/63961232-f16b3a00-caad-11e9-9dc2-1658c14111a8.png)

Sometimes DCM server stops working and on restarting docker it gives this warning. A successfully running server gives more logs. What is this issue and how to fix this.

**Comment by gunterze** [comment]
It's just a warning message - s. [WFCORE-429](https://issues.jboss.org/browse/WFCORE-429). There must be other issues with your installation causing the server to stop working.
