### ISSUE TITLE
Import default configuration into LDAP Server

### ISSUE THREAD

**Issue by iris19920918** [dcm4che/dcm4chee-arc-light#216]
Network Parameter:
    Hostname: localhost
    Port:     389
Authentication Parameter:
    Bind DN or user: cn=admin,dc=dcm4che,dc=org
    Bind password:   secret
Browser Options:
    Base DN: dc=dcm4che,dc=org
Filling in content above and click Check Authentication appeared error:
The authentication faild ---[LDAP: error code 49- INVALID_CREDENTIALS: Bind failed: Attempt to lookup non-existant entry:dc=dcm4che,dc=org]

**Comment by gunterze** [comment]
As the error message states, the LDAP server was not proper configured as described in the [Install Description](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#openldap) . Please use post further question at the [dcm4che Google group] (https://groups.google.com/forum/#!forum/dcm4che) .

**Comment by iris19920918** [comment]
I use Apache DS 2.0.0 not OpenLDAP

**Comment by gunterze** [comment]
Anyway, INVALID_CREDENTIAL states, that the DN or password does not match what you configured - so it's not an issue of the provided default configuration
