### ISSUE TITLE
 change default Storage Directory on windows

### ISSUE THREAD

**Issue by andreyals** [dcm4che/dcm4chee-arc-light#2162]
wildfly install and run on disk c: (windows)
I can not change default Storage Directory. old value path  dcmURI ${jboss.server.data.url}/fs1/ work, but when change path to other disk like this d:/pack/fs/ archive not worked.
how right change absolute archive path in windows ?

**Comment by gunterze** [comment]
Must be a file URI (e.g. file:///D:/pack/fs) , not a file path!

Pleas, post questions to https://groups.google.com/forum/#!forum/dcm4che
