### ISSUE TITLE
【RetrieveFrames】How to simulate this service and return this file ? 

### ISSUE THREAD

**Issue by dscdaixu** [dcm4che/dcm4chee-arc-light#2169]
[http://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.5.html] 

6.5 WADO-RS Request/Response for 【4.RetrieveFrames】

The response is pixel data,I found in my test that a .mht

How to simulate this service and return this file ? 
Is there a toolkit?

thanks!

**Comment by vrindanayak** [comment]
Please post questions in [dcm4che user forum](https://groups.google.com/forum/#!forum/dcm4che)

Use the [wadors tool](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-wadors/README.md) available in the dcm4che toolkit
