### ISSUE TITLE
Сonnection to external storage

### ISSUE THREAD

**Issue by WahTank** [dcm4che/dcm4chee-arc-light#2176]
Not a bug. Question about configuring external storage (NAS) for 2.17.2 version.
in what format to specify the login / password in the DefaultUserInformation field?
![image](https://user-images.githubusercontent.com/55870685/65869583-3081f900-e394-11e9-9191-63c0104a8727.png)

**Comment by gunterze** [comment]
2.17.2 is no longer maintained. You may ask for help in https://groups.google.com/forum/#!forum/dcm4che
