### ISSUE TITLE
Merge available object to unused MWL items

### ISSUE THREAD

**Issue by mokbelt** [dcm4che/dcm4chee-arc-light#2184]
Is there a possibility to merge an available DICOM object with an unused MWL record.

Example: When a study is received from Modality that was not selected via MWL, HOW to merge the received study later with the unused MWL record on dcm4che.

**Comment by gunterze** [comment]
see #428

Post further question to https://groups.google.com/forum/#!forum/dcm4che

**Comment by mokbelt** [comment]
Dear Gunter,

Already checked the #428 but my concern is the the objects that are already stored; how to make them merge with the unused MWL record.

If I modify the accession# of any **available** study (considering the dcmMergeMWLMatchingKey) is set), will the study be automatically merged with the concerned MWL record?

Can you provide a procedure for this issue?

**Comment by gunterze** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/issues/929

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vrindanayak** [comment]
@mokbelt : The swagger was updated in the last release and hence some of the links referenced in older issues no longer work. Here is the link for the RESTful service
[Link Instances With MWL Entry](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/LinkInstancesWithMWLEntry)
Complete list of RESTful services on the [home page](https://github.com/dcm4che/dcm4chee-arc-light/wiki) available as [RESTful Services of DCM4CHEE Archive 5.x](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json)

Using Archive UI, you may 
- select your study (which you want to link with MWL) and `Cut selected study`
![link-study-to-mwl-cut](https://user-images.githubusercontent.com/15785031/66409504-f7c7cc80-e9f0-11e9-8f61-f012d503cf91.png)
- next query for MWLs and select the MWL (to which you want this study to be linked); once MWL is selected `Merge study` 
![link-study-to-mwl-merge](https://user-images.githubusercontent.com/15785031/66409627-19c14f00-e9f1-11e9-93c1-21c4e60b2d79.png)
to MWL (typically using `Incorrect Modality Worklist` as the Rejection Note)
![link-study-to-mwl-rejectionNote](https://user-images.githubusercontent.com/15785031/66409818-5d1bbd80-e9f1-11e9-81fe-115e3bfeef3b.png)

**Comment by mokbelt** [comment]
@vrindanayak 
Thanks a lot for the explanation.
I tried and it was successful, but the new study with the correct worklist came without study date/time (so it can't be queried).
Did I miss anything?

**Comment by mokbelt** [comment]
Further to above, the record is still available in the MWL list and in SCHEDULED status.

**Comment by gunterze** [comment]
Start using the UI. Select/Cut the Study, switch to the MWLlist, Paste the Study to the selected MWL.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mokbelt** [comment]
Hello...
I used "SUPPLEMENT" for the coercion attributes of the Link to MWL.
However, the MWL wasn't marked automatically as "COMPLETED" after preforming the linking to MWL.

Please confirm that I didn't miss anything.

**Comment by gunterze** [comment]
In both cases, someone has to provide the descriptions - if we use the same machine readable format, we could feed both help systems with it.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gunterze** [comment]
The operation just adjust coerce the attributes of the instances according the linked MWL - it does not change the SPS Status of the MWL item.
