### ISSUE TITLE
Rule Conditions does not work as expected for empty values and nested attributes

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2190]
Conditions for
- Compressing Rules
- Export Rules
- Export Priors Rules
- Study Access Control ID Rules
- Study Retention Policy Rules

does not work as expected for empty values and nested attributes

**Comment by andreyals** [comment]
Rule Conditions for empty values now work, but rule  for non emprty atribute ( !=string) stopped working

**Comment by gunterze** [comment]
Should be covered by https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-conf/src/test/java/org/dcm4chee/arc/conf/ConditionsTest.java#L90-L94

**Comment by andreyals** [comment]
Export atribute condition: ReferringPhysicianName!=etazh\^2
dicom  atribute  value for ReferringPhysicianName : stacionar
export rule not working in this case

**Comment by andreyals** [comment]
sory all worked , my operator change name other atribute

**Comment by gunterze** [comment]
Be aware to that `+*?^$\.[]{}()|/ ` have special meaning, and should be preceded by a \ (backslash) to represent a literal character.
