### ISSUE TITLE
UI: Improve display of person names

### ISSUE THREAD

**Issue by mokbelt** [dcm4che/dcm4chee-arc-light#2195]
Can the patient name display be modified to GIVENNAME^MIDDLENAME^FAMILYNAME?

**Comment by shral** [comment]
@mokbelt For now, UI displays the Name like it is saved in the server respectively like it is defined in [DICOM](http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_6.2.1.1).
I will assign this issue to me and I will implement an UI config so the UI admin can than define how the name of the Patient should be displayed in study page. 
But we have than to see how we can make to the user clear how the name filter should be used, That will decide my colleague @gunterze

**Comment by gunterze** [comment]
Propose to format all Person Names - not only Patient names - as the samples in [DICOM PS3.5](http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_6.2.1.1) as `{name prefix} {given name complex} {middle name} {family name complex}, {name suffix}`

PN value | render as
-- | --
`Adams^John Robert Quincy^^Rev.^B.A. M.Div.` | `Rev. John Robert Quincy Adams, B.A. M.Div.`
`Morrison-Jones^Susan^^^Ph.D., Chief Executive Officer` | `Susan Morrison-Jones, Ph.D., Chief Executive Officer`
`Doe^John` | `John Doe`

The label of PN filter text fields shall be changed from `XXX name` to `XXX family name` to indicate, that the order of name components in the search field differs from the rendered person names in the list.
