### ISSUE TITLE
Unrecognized PDU in Docker setup

### ISSUE THREAD

**Issue by andri12321** [dcm4che/dcm4chee-arc-light#2213]
**Describe the bug**
The dcm4chee PACS seems to have an issue with the Network negotiation. I tried with different tools and data, but I always get the same error unrecognized PDU type (differenet numbers though).

**To Reproduce**
1. Setup docker with docker-compose according https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host#use-docker-compose
2. Try to send some DICOM data with the dcm4che toolkit ( ./storescu STORESCP@localhost:8080 ../../bmode.dcm ) or dmctk ( dcmsend localhost 8080 XX_0002 )

Data was taken from:
https://medistim.com/dicom/ --> BMode.dcm
https://www.insight-journal.org/midas/collection/view/194 --> Artichoke

**Expected behavior**
The image should be stored in the PACS or return a meaningful error

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Output storescu:
developer@developer-virtual-machine:~/Downloads/dcm4che-5.19.0/bin$ ./storescu -c STORESCP@localhost:8080 ../../bmode.dcm 
Scanning files to send
.
Scanned 1 files in 0.135s (=135ms/file)
13:59:21,072 INFO  - Initiate connection from 0.0.0.0/0.0.0.0:0 to localhost:8080
13:59:21,084 INFO  - Established connection Socket[addr=localhost/127.0.0.1,port=8080,localport=51391]
13:59:21,106 DEBUG - /127.0.0.1:51391->localhost/127.0.0.1:8080(1): enter state: Sta4 - Awaiting transport connection opening to complete
13:59:21,107 INFO  - STORESCU->STORESCP(1) << A-ASSOCIATE-RQ
13:59:21,135 DEBUG - A-ASSOCIATE-RQ[
  calledAET: STORESCP
  callingAET: STORESCU
  applicationContext: 1.2.840.10008.3.1.1.1 - DICOM Application Context Name
  implClassUID: 1.2.40.0.13.1.3
  implVersionName: dcm4che-5.19.0
  maxPDULength: 16378
  maxOpsInvoked/maxOpsPerformed: 0/0
  PresentationContext[id: 1
    as: 1.2.840.10008.1.1 - Verification SOP Class
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
  ]
  PresentationContext[id: 3
    as: 1.2.840.10008.5.1.4.1.1.3.1 - Ultrasound Multi-frame Image Storage
    ts: 1.2.840.10008.1.2.1 - Explicit VR Little Endian
  ]
  PresentationContext[id: 5
    as: 1.2.840.10008.5.1.4.1.1.3.1 - Ultrasound Multi-frame Image Storage
    ts: 1.2.840.10008.1.2 - Implicit VR Little Endian
  ]
  PresentationContext[id: 7
    as: 1.2.840.10008.5.1.4.1.1.3.1 - Ultrasound Multi-frame Image Storage
    ts: 1.2.840.10008.1.2.4.70 - JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1])
  ]
]
13:59:21,135 DEBUG - STORESCU->STORESCP(1): enter state: Sta5 - Awaiting A-ASSOCIATE-AC or A-ASSOCIATE-RJ PDU
13:59:21,137 WARN  - STORESCU->STORESCP(1): unrecognized PDU[type=72, len=1414541105]
13:59:21,137 INFO  - STORESCU->STORESCP(1) << A-ABORT[source: 2 - service-provider, reason: 1 - unrecognized-PDU]
13:59:21,137 DEBUG - STORESCU->STORESCP(1): enter state: Sta13 - Awaiting Transport Connection Close Indication
13:59:21,143 DEBUG - STORESCU->STORESCP(1): closing Socket[addr=localhost/127.0.0.1,port=8080,localport=51391] in 50 ms
storescu: A-ABORT[source: 2 - service-provider, reason: 1 - unrecognized-PDU]
A-ABORT[source: 2 - service-provider, reason: 1 - unrecognized-PDU]
	at org.dcm4che3.net.PDUDecoder.abort(PDUDecoder.java:234)
	at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:199)
	at org.dcm4che3.net.Association$2.run(Association.java:534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Debug output dcmsend:
developer@developer-virtual-machine:~/Downloads/DICOM_test_data$ dcmsend localhost 8080 XX_0002 -d
D: $dcmtk: dcmsend v3.6.1 2015-09-24 $
D: 
D: DcmDataDictionary: Loading file: /usr/share/libdcmtk5/dicom.dic
I: checking input files ...
D: adding DICOM file 'XX_0002'
D: getting SOP Class UID, SOP Instance UID and Transfer Syntax UID from DICOM file
D: DcmMetaInfo::checkAndReadPreamble() TransferSyntax="Little Endian Explicit"
D: trying to get SOP Class UID, SOP Instance UID and Transfer Syntax UID from meta-header
D: successfully added SOP instance 1.3.46.670589.11.5730.5.24.5.1.3144.2010043013311843153 to the transfer list
D: in total, there are 1 SOP instances to be sent, 0 invalid files are ignored
D: multiple associations allowed (option --multi-associations used)
D: preparing presentation context for SOP Class / Transfer Syntax: RawDataStorage / Little Endian Explicit
D: added new presentation context with ID 1
D: -----------------------------------------------------------------
D: starting association #1
I: initializing network ...
D: Configured a total of 1 presentation contexts for SCU
I: negotiating network association ...
D: Request Parameters:
D: ====================== BEGIN A-ASSOCIATE-RQ =====================
D: Our Implementation Class UID:      1.2.276.0.7230010.3.0.3.6.1
D: Our Implementation Version Name:   OFFIS_DCMTK_361
D: Their Implementation Class UID:    
D: Their Implementation Version Name: 
D: Application Context Name:    1.2.840.10008.3.1.1.1
D: Calling Application Name:    DCMSEND
D: Called Application Name:     ANY-SCP
D: Responding Application Name: resp. AP Title
D: Our Max PDU Receive Size:    16384
D: Their Max PDU Receive Size:  0
D: Presentation Contexts:
D:   Context ID:        1 (Proposed)
D:     Abstract Syntax: =RawDataStorage
D:     Proposed SCP/SCU Role: Default
D:     Proposed Transfer Syntax(es):
D:       =LittleEndianExplicit
D:       =BigEndianExplicit
D:       =LittleEndianImplicit
D: Requested Extended Negotiation: none
D: Accepted Extended Negotiation:  none
D: Requested User Identity Negotiation: none
D: User Identity Negotiation Response:  none
D: ======================= END A-ASSOCIATE-RQ ======================
I: Requesting Association
D: setting network send timeout to 60 seconds
D: setting network receive timeout to 60 seconds
D: Constructing Associate RQ PDU
D: Association Request Failed: 0006:0321 Unrecognized PDU type: 48
F: cannot negotiate network association: Unrecognized PDU type: 48
D: Cleaning up internal association and network structures

**Comment by gunterze** [comment]
Send to the dicom port (default:11112), not to the http port (default:8080)!
