### ISSUE TITLE
Some MWL DICOM tags lost after study is received/completed

### ISSUE THREAD

**Issue by mokbelt** [dcm4che/dcm4chee-arc-light#2220]
ver 5.17.1

I am having an issue where some DICOM tags generated in the HL7 MWL, such as (0038, 0010), (0040, 1002), (0040, 0006) - that correctly appear inside the MWL record on the dcm4che-arc-light UI, are lost after the study is received from the modality (although SUPPLEMENT is selected in the "Link MWL Entry Update Policy").

Please clarify how to keep the above tags in the completed study.

**Comment by mokbelt** [comment]
Is this issue related to settings?

**Comment by vrindanayak** [comment]
[Link MWL Entry Update Policy](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveNetworkAE.html#dcmlinkmwlentryupdatepolicy) is not related to feature [Update MWL status to COMPLETED for received studies](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Update-MWL-status-to-COMPLETED-for-received-studies). 

Your use case reflects [Update MWL status to COMPLETED for received studies](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Update-MWL-status-to-COMPLETED-for-received-studies) feature.

The above mentioned attributes, do get reflected even when the MWL status is COMPLETED (on receive of study) 

![Screenshot_2019-11-13 dcm4chee-arc-ui](https://user-images.githubusercontent.com/15785031/68759495-13d21580-0610-11ea-87a7-d89ccdf8e0cc.png)

Please post further questions in the [dcm4che User Forum](https://groups.google.com/forum/#!forum/dcm4che)

**Comment by mokbelt** [comment]
Dear vrindanayak,

Both "Link MWL Entry Update Policy"  and "Update MWL status to COMPLETED for received studies" are not related to my case.

In my case: The MWL is pulled directly from modality and the study is sent to dcm4chee and the modality sends the MPPS COMPLETED message;
the problem is that before the MWL record is selected from modality (which is while the MWL record is in SCHEDULED status) I can see on the dcm4che UI the tags (0038, 0010), (0040, 1002), (0040, 0006), however when the study is received from modality the mentioned DICOM tags are no longer visible on the received study on dcm4chee UI.

Please advise!

**Comment by vrindanayak** [comment]
It is the modality's responsibility to populate the values of tags (of interest) from MWL to the study before sending it to archive! 
As a workaround, you could configure [Coerce received DICOM objects attributes by XSLT](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Coerce-received-DICOM-objects-attributes-by-XSLT) feature (refer first [Use case - Merge from MWL](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Coerce-received-DICOM-objects-attributes-by-XSLT#use-cases)) and update the default stylesheet provided accordingly to accommodate these 3 tags (as they are not part of default Series IOD defined by DICOM, they are not available in the default stylesheet).

**Comment by mokbelt** [comment]
Dear vrindanayak,
Thank you for the clarification...
Is it possible to provide a step-by-step example for the attributes (0038, 0010), (0040, 1002), (0040, 0006) inside which xsl sheet? (mwl2series.xsl ? hl7-order2dcm.xsl?)

**Comment by vrindanayak** [comment]
- It is the `mwl2series.xsl` as explained in the use case. 
- `Reason for the Requested Procedure (0040,1002)` is already available inside the `Request Attributes Sequence (0040,0275)`. 
- For other two attributes i.e. `Admission ID (0038,0010)` and `Scheduled Performing Physician's Name(0040,0006)`, to be seen on root level, you can do it similar to `Accession Number (0008,0050)` as shown in the same stylesheet.

**Comment by mokbelt** [comment]
Thanks.
Shall I need to do anything else after modifying the stylesheet?

**Comment by vrindanayak** [comment]
- You just need to configure the feature - [Coerce received DICOM objects attributes by XSLT](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Coerce-received-DICOM-objects-attributes-by-XSLT) - [Use case - Merge from MWL](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Coerce-received-DICOM-objects-attributes-by-XSLT#use-cases) with your updated stylesheet. 
- Upload your updated stylesheet as part of the [Vendor Data](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Vendor-Data#using-archive-ui) - See point `Partial Update`

**Comment by mokbelt** [comment]
Did as mentined above, but the tags above weren't coerced, noting that they were visible in he MWL record. The log gave:

2019-11-27 11:13:51,822 INFO  [org.dcm4chee.arc.store.impl.StoreServiceEJB] (EE-ManagedExecutorService-default-Thread-881) SMLPACS<-XC_DICOM(19): Query for MWL Items with MergeMWLQueryParam{accessionNumber='null', studyIUID='2.25.173908173803804260228738351643212707085', spsID='null'}
2019-11-27 11:13:51,822 INFO  [org.dcm4chee.arc.store.impl.StoreServiceEJB] (EE-ManagedExecutorService-default-Thread-881) SMLPACS<-XC_DICOM(19): Found 1 matching MWL Items
2019-11-27 11:13:51,837 INFO  [org.dcm4chee.arc.store.impl.StoreServiceImpl] (EE-ManagedExecutorService-default-Thread-881) SMLPACS<-XC_DICOM(19): Coerce Request Attributes from matching MWL item(s) using rule: ArchiveAttributeCoercion[cn=AddDICOMTags, priority=0, DIMSE=C_STORE_RQ, role=SCU, aets=[], hostNames=[], cuids=[], retrieveAsReceived=false, deIdentification=[], xslturi=null, noKeywords=true, leadingCFindSCP=null, mergeMWLMatchingKey=StudyInstanceUID, mergeMWLTemplateURI=file:///SMLPACS/wildfly-17.0.1.Final/standalone/tmp/dcm4chee-arc/mwl2series.xsl, attributeUpdatePolicy=SUPPLEMENT, nullifyIssuerOfPatientID=null, issuerOfPatientIDs=[], issuerOfPatientIDFormat=null, supplementFromDeviceName=null]
2019-11-27 11:13:51,884 INFO  [org.dcm4chee.arc.store.impl.StoreServiceEJB] (EE-ManagedExecutorService-default-Thread-881) SMLPACS<-XC_DICOM(19): Supplement attributes of Patient[pk=138, id=PatientID[pk=138, id=X19-41-PID-1623, issuer=null], name=_omitted_^_omitted_^_omitted_]:
(0010,0032) TM [000000] PatientBirthTime

**Comment by gunterze** [comment]
Only attributes extracted in the DB according configured [Attribute Filters](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/attributeFilter.html) can be coerced in received objects.

**Comment by mokbelt** [comment]
Please clarify, what **Attribute Entity** (MWL?, Series?, Study?, Patient?), **Attribute Update Policy** shall I use for my case above?

**Comment by gunterze** [comment]
Patient or Study, depended of the _Information Entity_ (IE) the attribute belongs. Be aware that attributes of the [Patient Study Module](http://dicom.nema.org/medical/dicom/current/output/html/part03.html#table_C.7-4a) belongs to the Study and not to the Patient IE, because they may vary for different Studies for the same Patient. The **Attribute Update Policy** defines how to merge attribute values of existing DB records created on receive of previous objects of that entity with attributes with different values in the received object.

**Comment by mokbelt** [comment]
if the MWL has the attributes, and the new received object does not have them, shall I use SUPPLEMENT to make the newly received object have the required MWL attributes?

**Comment by gunterze** [comment]
Read https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/attributeFilter.html#dcmattributeupdatepolicy . The defaults take care, that Patient attributes can only be supplemented but not changes via receive of DICOM object, where Study and Series attributes are always updated to the value of the latest received object.

**Comment by mokbelt** [comment]
A bit lost!!!! In order to summarize for the future:
My request is that I need (0038, 0010), (0040, 1002), (0040, 0006)  that are available inside the MWL, to be available also on in the received object.
What steps shall I follow to do this?

**Comment by gunterze** [comment]
#2282 #2283 [mwl2series.xsl](https://github.com/dcm4che/dcm4chee-arc-light/blob/5.20.0/dcm4chee-arc-conf-data/src/main/resources/mwl2series.xsl)

**Comment by mokbelt** [comment]
This will be fixed in 5.20?

**Comment by gunterze** [comment]
Yes, but you may just take the modified [mwl2series.xsl](https://github.com/dcm4che/dcm4chee-arc-light/blob/5.20.0/dcm4chee-arc-conf-data/src/main/resources/mwl2series.xsl) and refer it as **Merge MWL Template URI** in your configured [Attribute Coercion](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveAttributeCoercion.html#archive-attribute-coercion) also in v5.17.1.

**Comment by mokbelt** [comment]
I am using this configuration but the supplement attributes (0038, 0010), (0040, 1002), (0040, 0006) are not being added to the received object:
![image](https://user-images.githubusercontent.com/56265911/69811157-234b8400-11f6-11ea-997a-7e49e4b86c01.png)
![image](https://user-images.githubusercontent.com/56265911/69811187-3a8a7180-11f6-11ea-8d75-f5bb01448625.png)
further to that the below lines are included in mwl2series.xsl:
	   
      <xsl:copy-of select="DicomAttribute[@tag='00380010']"/>
	  		   
      <xsl:copy-of select="DicomAttribute[@tag='00400006']"/>

**Comment by gunterze** [comment]
![Screenshot from 2019-11-28 14-51-41](https://user-images.githubusercontent.com/400095/69811803-2c852280-11ef-11ea-8b71-9462279d60c9.png)
![Screenshot from 2019-11-28 14-53-23](https://user-images.githubusercontent.com/400095/69811804-2d1db900-11ef-11ea-8908-394db578a6db.png)
![Screenshot from 2019-11-28 14-54-52](https://user-images.githubusercontent.com/400095/69811807-2d1db900-11ef-11ea-9af9-e87f004cfb92.png)

**Comment by mokbelt** [comment]
What about the "Attribute Update Policy"?

**Comment by gunterze** [comment]
Does not matter for Merge MWL attribute coercion

**Comment by gunterze** [comment]
You have to restart the archive - XSLT results for a particular MWL item are cached
