### ISSUE TITLE
List Export REST service returns wrong value for LocalAET

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2223]
[List Export REST service](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MONITOR-RS/listExportTasks) returns wrong value for LocalAET

**Comment by petrkalina** [comment]
.. Displayed info

<img width="424" alt="Screenshot" src="https://user-images.githubusercontent.com/1150350/67498700-3069d600-f680-11e9-95ad-aa9221f53206.png">

.. exporter definition in referenced device:

```
dn: dcmExporterID=Export to S3,dicomDeviceName=archive2tln,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
objectClass: dcmExporter
dcmExporterID: Export to S3
dcmQueueName: Export5
dcmURI: storage:s3-data
dcmInstanceAvailability: NEARLINE
dicomAETitle: ARC2TLN_IOCM_REG
dicomDescription: Copy Objects from Cache to S3
```
