### ISSUE TITLE
Optionally do not remove Storage Systems which usable space fall below the configured Storage Threshold from the list of configured Storage Systems

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2232]
Optionally do not remove Storage Systems which usable space fall below the configured Storage Threshold from the list of configured Storage Systems, but mark them as full and recheck the usable space when the Storage Threshold of the next associated Storage System also exceeds, so existing Storage Systems kept filled up, before the next configured Storage System is used.

Configurable by [Storage](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/storage.html) attributes:

Name | Type | Description (LDAP Attribute)
-- | -- | --
Storage Threshold | string | Minimal Usable Space on Storage System. If the usable space falls below that value the Storage System will be marked as full by setting Storage Threshold Exceeds to the current time and - if Storage Threshold Exceeds Permanently is true - the Storage System will be removed from the list of configured Storage Systems of the Network AE requesting that Storage System. Format nnn(MB\|GB\|MiB\|GiB) (dcmStorageThreshold)
Storage Threshold Exceeded | string | Date and time in format YYYYMMDDHHMMSS.FFFFFF when the Storage Threshold exceeded. (dcmStorageThresholdExceeded)
Storage Threshold Exceeds Permanently | boolean | Indicates to removed the Storage System from the list of configured Storage Systems of the Network AE requesting that Storage System when the Storage Threshold exceeds. (dcmStorageThresholdExceedsPermanently)

Requires dcm4che/dcm4che#579

**Comment by andor-pierdelacabeza** [comment]
Could be checked either "on receive of next object over a different Association" or "on the moment the current filesystem fills up":

- First would be better if you have _more than one_ "Object Storage Count", so each time you store something new, you check which filesystems have free space
- Second would be better if you only have _one_  "Object Storage Count", so you only worry about storage when you fill up the one you're using

**Comment by andor-pierdelacabeza** [comment]
Ah ok, I still have in my mind the "dcm4chee v2 way", which had some sort of "active filesystem".

Because sometimes storage is set up, ahem, asimetrically:
- So they give me a 10TB fs now, and another one in 3 months.
- They are filling up in different proportion and one hits "full" before the other
- But I have delayed compression, or maybe "forward and delete old studies" enabled, and I get new free space and I want the PACS to store objects there again if the second filesystem gets full

**Comment by andor-pierdelacabeza** [comment]
I mean, it not necessarily critical for my deployments, maybe I just need to change my point of view when setting up a new PACS.

I'm doing my first v5 deployment and some things are different as they used to be when I deployed v2, years ago :laughing: 

- Is it OK if I explain some of this things a bit more thoroughly on the Wiki?
- Is the mailing list the best place to ask for small doubts on dcm4chee behavior?

**Comment by gunterze** [comment]
Prefer using the mailing list for discussions.

So what you want is to make the order of filling dependent on the filling state: 
If you configure A, B, C and A becomes full, it should be changed to B, A, C, so if B becomes full, A is refilled before C is used.

Currently the order is determined by the literal order of the storage id.
