### ISSUE TITLE
How to configure query of external archives

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2253]
[Query remote Application Entities](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Query-remote-Application-Entities)

**Comment by petrkalina** [comment]
Wiki entry ready..

**Comment by petrkalina** [comment]
Wiki entry ready..

**Comment by vrindanayak** [comment]
Reverted above changes, as this has been covered as part of more comprehensive wiki [Accessing External Archive](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Accessing-External-Archive) documented as part of #2311
