### ISSUE TITLE
Problem in "Update MWL status to COMPLETED for received studies"

### ISSUE THREAD

**Issue by mokbelt** [dcm4che/dcm4chee-arc-light#2268]
Dears,

I am having a problem in marking the HL7 received MWL status to COMPLETED after the study is received.
The following settings are used:
![image](https://user-images.githubusercontent.com/56265911/69319232-78f8bd00-0c47-11ea-831c-b5f7715897b0.png)

Further, the study received has the same studyInstanceUID of the one in the MWL. 
PS: The modality is sending "STARTED" status, but not sending "COMPLETED" status, that's why I am using the Update Status feature.

The error log is giving:
_2019-11-21 09:52:59,064 INFO  [org.dcm4chee.arc.hl7.psu.HL7PSUScheduler] (EE-ManagedScheduledExecutorService-default-Thread-2) Schedule HL7PSUTask[pk=10, deviceName=dcm4chee-arc, studyInstanceUID=2.25.73283257327090901975981746874934706041, scheduledTime=2019-11-21 09:30:04.0]_

2019-11-21 09:52:59,080 ERROR [org.jboss.as.ejb3.invocation] (EE-_ManagedScheduledExecutorService-default-Thread-2) WFLYEJB0034: EJB Invocation failed on component HL7PSUEJB for method public void org.dcm4chee.arc.hl7.psu.HL7PSUEJB.scheduleHL7PSUTask(org.dcm4chee.arc.entity.HL7PSUTask,org.dcm4chee.arc.hl7.psu.HL7PSUScheduler$HL7PSU): javax.ejb.EJBException: java.lang.NullPointerException_

Please advise if other settings shall be also made and the possible reasons for this error.

Thank you!

**Comment by mokbelt** [comment]
Dear vrindanayak, do you mean this issue will be fixed in the release 5.20?

**Comment by vrindanayak** [comment]
Yes, the exception occurs **only** if you have also activated notifying HL7 receivers of this procedure status update. If you are interested only in updating status to COMPLETED but **not** notifying the HL7 receivers, you will not see this exception. 

Notification to HL7 receivers about this procedure status update can be disabled by attributes _HL7 Procedure Status Update Sending Application_ and _HL7 Procedure Status Update Receiving Application_

**Comment by mokbelt** [comment]
They are already disabled (check attached), but still getting this error!
![image](https://user-images.githubusercontent.com/56265911/69345442-ce4dc200-0c79-11ea-9d2d-f053ebfbdbeb.png)

**Comment by vrindanayak** [comment]
This has been already fixed as part of #2174
