### ISSUE TITLE
Getting error Retrieving studies from Horos 3.3.5

### ISSUE THREAD

**Issue by tecsal** [dcm4che/dcm4chee-arc-light#2272]
When connecting from Horos 3.3.5, we can query studies correctly, but I'm unable to retrieve (with C-GET) the study. I get this error in server.log:

org.dcm4che3.net.NoRoleSelectionException: No Role Selection for SOP Class 1.2.840.10008.5.1.4.1.1.4 - MR Image Storage as SCU negotiated

This is the same issue as here: https://github.com/horosproject/horos/issues/404

**To Fix It it had to modify code and recompile dcm4chee**
org.dcm4chee.arc.store.scu.impl.RetrieveTaskImpl:180
Remove this line:
`-- storeas.cstore(cuid, iuid, priority, data, tsuid, rspHandler);`
Add thoses lines instead:
```
PresentationContext pc = storeas.pcFor(cuid, tsuid);
Attributes cstorerq = Commands.mkCStoreRQ(rspHandler.getMessageID(), cuid, iuid, priority);
storeas.invoke(pc, cstorerq, data, rspHandler, 0);
```

Do you agree with it ? Can you update the source code, so I'll be able to update next version from trunk wihout having to re-compile the fix.

**Comment by gunterze** [comment]
No. The Archive behaves correctly, Horos behaves wrong. You may disable the check for the required  SCP/SCU role selection negotiation  by configuration: https://github.com/dcm4che/dcm4che/issues/463
