### ISSUE TITLE
UI: Improve devicelist page

### ISSUE THREAD

**Issue by shral** [dcm4che/dcm4chee-arc-light#228]

**Comment by gunterze** [comment]
IMO, it is sufficient to support filtering for Primary Device Types, selectable from values defined on [DICOM Part 16,  CID 30 DICOM Devices](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_30.html). That list may be also provided in the Device editor to pick up possible values for Primary Device Types.
