### ISSUE TITLE
How to manually change the status of the MWL records from SCHEDULED to COMPLETED

### ISSUE THREAD

**Issue by mokbelt** [dcm4che/dcm4chee-arc-light#2280]
v.5.17.1

I have some MWL that are still in SCHEDULED status.
How to manually change the status to COMPLETED?

**Comment by gunterze** [comment]
Let me know, why you don't post questions like that to https://groups.google.com/forum/#!forum/dcm4che ? Just want to reserve this tracker for bugs and feature requests.

**Comment by mokbelt** [comment]
Apologizies. Done.
