### ISSUE TITLE
How to anonymize on receive? 

### ISSUE THREAD

**Issue by thiagobusa** [dcm4che/dcm4chee-arc-light#2285]
As I understand it "Basic Application Confidentiality Profile" on coerce functionality, works only for the retrive, correct? For the receive(on store) should i generate a coerce.xsl file and assign/remove tags one by one?

**Comment by gunterze** [comment]
Attribute Coercion is only applied on attributes extracted into the DB, the stored file always contains the attributes as received.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gunterze** [comment]
Please use the forum for question
