### ISSUE TITLE
UI: Query Unified Worklist (UWL) using RESTful Service

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2294]
Using RESTful service: [Search for Workitems](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/UPS-RS/SearchForWorkitems)

Support filtering by

- Patient attributes:

  Attribute | Tag | Query Parameter(s)
  -- | -- | --
  **Patient's Name** | (0010,0010)| `00100010=<string>`
  Patient ID | (0010,0020)| `00100020=<string>`
  Issuer of Patient ID | (0010,0021) | `00100021=<string>`
  Patient's Birth Date | (0010,0030) | `00100030=<min-date>-<max-date>`
  Patient's Sex | (0010,0040) | `00100040=F\|M\|O`

- Worklist and Workitem state

  Attribute | Tag | Query Parameter(s)
  -- | -- | --
  **Worklist Label** | (0074,1202) | `00741202=<string>`
  **Input Readiness State** | (0040,4041) |  `00404041=INCOMPLETE\|UNAVAILABLE\|READY`
  **Procedure Step State** | (0074,1000) |  `00741000=SCHEDULED\|IN PROGRESS\|CANCELED\|COMPLETED`

- Workitem Priority and Scheduled Start Time

  Attribute | Tag | Query Parameter(s)
  -- | -- | --
  **Scheduled Procedure Step Priority** | (0074,1200) |  `00741200=LOW\|MEDIUM\|HIGH`
  **Scheduled Procedure Step Start Date and Time** | (0040,4005) | `00404005=<min-date-and-time>-<max-date-and-time>`
  Expected Completion Date and Time | (0040,4011) | `00404011=<min-date-and-time>-<max-date-and-time>`

- Workitem Label and Code

  Attribute | Tag | Query Parameter(s)
  -- | -- | --
  **Procedure Step Label** | (0074,1204) | `00741204=<string>`
  Scheduled Workitem Code Sequence | (0040,4018) | `00404018.00080100=<code-value>&00404018.00080102=<coding scheme designator>`

- Scheduled Station

  Attribute | Tag | Query Parameter(s)
  -- | -- | --
  Scheduled Station Name Code Sequence | (0040,4025) | `00404025.00080100=<code-value>&00404025.00080102=<coding scheme designator>`
  Scheduled Station Class Code Sequence | (0040,4026) | `00404026.00080100=<code-value>&00404026.00080102=<coding scheme designator>`
  Scheduled Station Geographic Location  Code Sequence | (0040,4027) | `00404027.00080100=<code-value>&00404027.00080102=<coding scheme designator>`

- Scheduled Human Performer

  Attribute | Tag | Query Parameter(s)
  -- | -- | --
  Scheduled Human Performers Sequence | (0040,4034) | `00404034.00404009.00080100=<code-value>&00404034.00404009.00080102=<coding scheme designator>`

- Referenced Request

  Attribute | Tag | Query Parameter(s)
  -- | -- | --
  Admission ID | (0038,0010) | `00380010=<string>`
  Issuer of Admission ID Sequence | (0038,0014) | `00380014.00400031=<string>`
  Referenced Request Sequence | (0040,A370) | see below
  \>Study Instance UID | (0020,000D) | `0040A370.0020000D=<string>`
  \>Accession Number | (0008,0050) | `0040A370.00080050=<string>`
  \>Issuer of Accession Number Sequence | (0008,0051) |  `0040A370.00080051.00400031=<string>`
  \>Requested Procedure ID | (0040,1001) | `0040A370.00401001=<string>`
  \>Requesting Physician | (0032,1032) | `0040A370.00321032=<string>`
  \>Requesting Service | (0032,1033) | `0040A370.00321033=<string>`

Support sort by

Attribute | Tag | Query Parameter
-- | -- | --
Scheduled Procedure Step Priority | (0074,1200) |  `orderby=[-]00741200`
Scheduled Procedure Step Start Date and Time | (0040,4005) | `orderby=[-]00404005`
Expected Completion Date and Time | (0040,4011) | `orderby=[-]00404011`

Display

Attribute | Tag | Property
-- | -- | --
Scheduled Procedure Step Modification Date and Time | (0040,4010) | `"00404010"`

additionally to **bold** query attributes in table columns.

Related  #178  #2164 #2279

**Comment by vrindanayak** [comment]
- `No Elements Found` in `Order by` dropdown
- `More Functions` dropdown is not required in UWL tab
- `Procedure Step Label` and `Scheduled Procedure Step Modification Date and Time` not available on Display of UWL entries
