### ISSUE TITLE
RESTful Service: Delete Empty Study Permanently

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#231]
[RESTful Service: Delete Study Permanently](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#!/IOCM-RS/DeleteStudy)

Only allowed for studies with no (not rejected) instances (`Study.rejectionState = COMPLETE or EMPTY`). Other fail with HTTP error status 403 Forbidden.

**Comment by vrindanayak** [comment]
RESTful Service : Delete Empty Study Permanently
