### ISSUE TITLE
UI Navigation page -> Studies tab : Enable to Download (uncompressed ) DICOM object from WADO_URI web applications of external archive

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2330]
Currently only `View DICOM object` works, whereas for `Download DICOM object` and `Download uncompressed DICOM object`, the service path configured for a web application of an external archive having `WADO_URI` as service class is **not** invoked at all.

**Comment by shral** [comment]
Fixed with #2323
