### ISSUE TITLE
Corruption of querying MySQL dicomattrs.attrs data

### ISSUE THREAD

**Issue by mokbelt** [dcm4che/dcm4chee-arc-light#2338]
V 5.17.1
Trying to pull a specific field (in italic below "X19-49") from mysql/php from dicomattrs.attrs BLOB field is being received corrupt (using utf8), example:

� �CS
�ISO_IR 100 � �DA �20191223 �0�TM �115506 �P�SH �US227 ���PN�� �0 LO �7755 Ultrasound of breast � AS �037Y �� LO�� � !LO�� �
�UI,�2.25.180626064865327159115292639608312837855 � �SH �190044001201912231110 8� �LO � _X19-49_ 8� �SQ����������������������

Is this a bug that prevents correct pulling of data by mysql query?

**Comment by gunterze** [comment]
BLOBs contains binary, not UTF8 strings!
Please post questions to https://groups.google.com/forum/#!forum/dcm4che
