### ISSUE TITLE
Queue Retrieve Tasks automatically according their Scheduled Time

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2368]
Configurable by [Archive Device](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveDevice.html) attributes:

Name | Type | Description (LDAP Attribute)
-- | -- | --
Retrieve Task Polling Interval | string | Retrieve Task Polling Interval in ISO-8601 duration format PnDTnHnMnS. (dcmRetrieveTaskPollingInterval)
Retrieve Task Fetch Size | integer | Limit result set of DB query for Retrieve Tasks ready for processing. (dcmRetrieveTaskFetchSize)

- [x] Add property `ScheduledTime` to entity `RetrieveTask`
- [x] Persist/Load configuration attributes _Retrieve Task Polling Interval_ and _Retrieve Task Fetch Size_ to/from LDAP
- [x] Serialize/Deserialize configuration attributes _Retrieve Task Polling Interval_ and _Retrieve Task Fetch Size_ to/from JSON
- [x] Implement `RetrieveScheduler` in module `dcm4chee-arc-retrieve-mgt`
- [x] support to specify `scheduledTime` by optional Query Parameter in RESTful services
  - [x] [Mark Study for retrieve from external C-MOVE SCP](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/MarkStudyForRetrieve)
  - [x] [Mark Series from external C-MOVE SCP](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/MarkSeriesForRetrieve)
  - [x] [Mark Instance from external C-MOVE SCP](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/MarkInstanceForRetrieve)
  - [x] [Mark Studies for Retrieve specified in CSV from external C-MOVE SCP](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/MarkForRetrieveStudiesCSV)
  - [x] [Query from C-FIND SCP and Mark matching Studies for retrieve from external C-MOVE SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/QueryCFindMarkMatchingStudiesForRetrieve)
  - [x] [Query from C-FIND SCP and Mark matching Series for retrieve from external C-MOVE SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/QueryCFindMarkMatchingSeriesForRetrieve)
  - [x] [Query from C-FIND SCP and Mark matching Instances for retrieve from external C-MOVE SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/QueryCFindMarkMatchingInstancesForRetrieve)
  - [x] [Query and Mark matching Studies for retrieve from external C-MOVE SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/QueryAndMarkMatchingStudiesForRetrieve)
  - [x] [Query and Mark matching Series for retrieve from external C-MOVE SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/QueryAndMarkMatchingSeriesForRetrieve)
  - [x] [Query and Mark matching Instances for retrieve from external C-MOVE SCP](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-RS/QueryAndMarkMatchingInstancesForRetrieve)
  - [x] [Query from C-FIND SCP and Mark matching Studies for retrieve from external C-MOVE SCP Legacy](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-LEGACY-RS/QueryCFindMarkMatchingStudiesForRetrieveLegacy)
  - [x] [Query from C-FIND SCP and Mark matching Series for retrieve from external C-MOVE SCP Legacy](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-LEGACY-RS/QueryCFindMarkMatchingInstancesForRetrieveLegacy)
  - [x] [Query from C-FIND SCP and Mark matching Instances for retrieve from external C-MOVE SCP Legacy](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MOVE-LEGACY-RS/QueryCFindMarkMatchingStudiesForRetrieveLegacy)
- [x] support to specify Scheduled Time by optional Query Parameter in RESTful services [Reschedule Retrieve Task](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MONITOR-RS/rescheduleRetrieveTask)  and [Reschedule Retrieve Tasks](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MONITOR-RS/rescheduleRetrieveTasks) . If specified, only update property scheduledTime of the affected ReportTask(s), but don't schedule the task(s) immediately. For Report Tasks with previous status != TO_SCHEDULE, remove the associated QueueMessage.
- [ ] adjust RESTful services 
  - [x] [List Retrieve Tasks](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MONITOR-RS/listRetrieveTasks) 
  - [ ] [List Retrieve Batches](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MONITOR-RS/listRetrieveBatches) 
to reflect Scheduled Time of Retrieve Tasks without associated Queue message (Status: TO_SCHEDULE) in returned list

**Comment by luxunxiansheng** [comment]
hi, there, how to configure this task with WebUI?  is there any user guide we can refer to ? thanks .
