### ISSUE TITLE
Timezone and localtime not working for dcm4chee on docker

### ISSUE THREAD

**Issue by MaherJendoubi** [dcm4che/dcm4chee-arc-light#2397]
**Describe the bug**
**-v /etc/localtime:/etc/localtime:ro** **-v /etc/timezone:/etc/timezone:ro** are causing an issue for creating correctly the dcm4chee-arch-light on docker.

**To Reproduce**
1. docker run --network=dcm4chee_default --name ldap -p 389:389 -v /var/local/dcm4chee-arc/ldap:/var/lib/ldap -v /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d -d dcm4che/slapd-dcm4chee:2.4.48-21.0
2. docker run --network=dcm4chee_default --name db -p 5432:5432 -e POSTGRES_DB=pacsdb -e POSTGRES_USER=pacs -e POSTGRES_PASSWORD=pacs -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v /var/local/dcm4chee-arc/db:/var/lib/postgresql/data -d dcm4che/postgres-dcm4chee:12.1-21
3. docker run --network=dcm4chee_default --name arc -p 8080:8080 -p 8443:8443 -p 9990:9990 -p 11112:11112 -p 2575:2575 -e POSTGRES_DB=pacsdb -e POSTGRES_USER=pacs -e POSTGRES_PASSWORD=pacs -e WILDFLY_WAIT_FOR="ldap:389 db:5432" -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone -d dcm4che/dcm4chee-arc-psql:5.20.0
4. See error:

**docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/timezone\\\" to rootfs \\\"/var/lib/docker/overlay2/d86c2fe24d149a9f8dec100f1fa992d0a47b715d7ae4d24a2e005218901cae4d/merged\\\" at \\\"/var/lib/docker/overlay2/d86c2fe24d149a9f8dec100f1fa992d0a47b715d7ae4d24a2e005218901cae4d/merged/etc/timezone\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.**

![image](https://user-images.githubusercontent.com/1798510/72971562-33cd4480-3dca-11ea-84c2-54dac7102cdc.png)

**Expected behavior**
Timezone and local time should be synced with the host machine running docker engine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1909 (64 bits)
 - Browse:r  Firefox 
 - Firefox Version: 72.0.2 (64 bits)
 - docker:

![image](https://user-images.githubusercontent.com/1798510/72971793-9cb4bc80-3dca-11ea-9dea-4c866c69f274.png)

**Additional context**

**Comment by gunterze** [comment]
Did you follow [Run minimum set of archive services on a single host](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host#start-postgresql-server):

> Bind mount -v /etc/localtime:/etc/localtime:ro and -v /etc/timezone:/etc/timezone:ro duplicates your host timezone inside the container. Otherwise the container timezone is UTC. **Attention:** If there is no /etc/timezone on your host, you have to create one (e.g.: $ echo "Europe/Vienna" > /etc/timezone) before launching the container, otherwise the container will not start.

?

**Comment by MaherJendoubi** [comment]
@gunterze my mistake, I didn't.

**Comment by MaherJendoubi** [comment]
@gunterze Any idea how to mount them?

**Comment by gunterze** [comment]
Be aware, that on WIndows the docker host is the Docker VM, not the Windows host.

**Comment by MaherJendoubi** [comment]
I see. Thanks a lot @gunterze
