### ISSUE TITLE
UI Navigation -> Studies : Enable to send multiple values for SOP Classes in Study filter

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2414]
RESTful services
- [Search for Studies](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/QIDO-RS/SearchForStudies)
- [Count Studies](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/STAT-RS/CountStudies)
- [Size of Studies](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/STAT-RS/SizeOfStudies)
- [Compare Studies](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/DIFF-RS/CompareStudies)
- [Compare Studies Count](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/DIFF-RS/CompareStudiesCount)
- [Compare Studies specified in CSV](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/DIFF-RS/CompareStudiesCSV)

Multiple values can be sent in one of the following two ways : (eg)
- `SOPClassesInStudy=1.2.840.10008.5.1.4.1.1.7&SOPClassesInStudy=1.2.840.10008.5.1.4.1.1.11.1`
- `SOPClassesInStudy=1.2.840.10008.5.1.4.1.1.7,1.2.840.10008.5.1.4.1.1.11.1`

**Comment by sgala** [comment]
I'm seeing it not working, I see this: 
![Screenshot from 2020-06-26 10-40-11](https://user-images.githubusercontent.com/2065/85838291-a25b6780-b799-11ea-8713-04b40ae974ed.png)

I'm using 5.22.2, my own build of the docker image, I wonder if I broke something unadvertently or there is a reproducible bug.

**Comment by vrindanayak** [comment]
Thanks for reporting!

**Comment by shral** [comment]
> I'm seeing it not working, I see this:
> ![Screenshot from 2020-06-26 10-40-11](https://user-images.githubusercontent.com/2065/85838291-a25b6780-b799-11ea-8713-04b40ae974ed.png)
> 
> I'm using 5.22.2, my own build of the docker image, I wonder if I broke something unadvertently or there is a reproducible bug.

That is a bug, now should work!
