### ISSUE TITLE
How To build this project?

### ISSUE THREAD

**Issue by MaherJendoubi** [dcm4che/dcm4chee-arc-light#2420]
Hello,

I am using Eclipse for this project. I have imported into Eclipse as a maven project.
There are many classes not found after the maven install.
Would you please elaborate on the process of building this project?

Best regards,
Maher

**Comment by gunterze** [comment]
Please post questions about dcm4che/dcm4chee-arc to https://groups.google.com/forum/#!forum/dcm4che
