### ISSUE TITLE
non-secure arc-light 5.21.0 does not accept STOW

### ISSUE THREAD

**Issue by spalte** [dcm4che/dcm4chee-arc-light#2435]
**Describe the bug**
When trying to do a STOW the following error is returned with status 403
{"errorMessage":"Web Application with STOW_RS service class does not list role of accessing user"}

**To Reproduce**
1. Load containers with images dcm4che/dcm4chee-arc-psql:5.21.0, dcm4che/postgres-dcm4chee:12.1-21, and dcm4che/slapd-dcm4chee:2.4.48-21.0.
2. Perform a STOW on the archive.

**Expected behavior**
A successful STOW given that this is not a secured instance.

**Comment by vrindanayak** [comment]
Not reproducible

**Comment by spalte** [comment]
Upon further investigation, I found that the issue is a change of behavior if an Authorization http header is provided with the request. It used to be ignored, but is now taken into account and a forbidden response is returned.

**Comment by vrindanayak** [comment]
> Upon further investigation, I found that the issue is a change of behavior if an Authorization http header is provided with the request. It used to be ignored, but is now taken into account and a forbidden response is returned.

Yes, as https://github.com/dcm4che/dcm4chee-arc-light/issues/2400 has been implemented in 5.21.0. Also for unsecure version, sending `Authorization` header is incorrect.
