### ISSUE TITLE
C-Find / QIDO requests containing <Sequence>[/.]CodeMeaning as matching key / query filter is not handled in QueryBuilder code predicate

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2457]
Only `CodeValue`, `CodingSchemeDesignator` and `CodingSchemeVersion` are handled currently. `CodeMeaning` is missing.

**Comment by gunterze** [comment]
Not required by DICOM: http://dicom.nema.org/medical/dicom/current/output/html/part04.html#table_8-1b
