### ISSUE TITLE
Web application permissions issue on version with secured UI but not secured RESTful services

### ISSUE THREAD

**Issue by Syrlander** [dcm4che/dcm4chee-arc-light#2462]
After installing/upgrading to the latest version (5.21.0) of dcm4chee arc light, I seem to be having trouble with querying any configured web applications after having pressed the "Submit" button.

I get error 403: "Web Application with QIDO_RS service class does not list role of accessing user"

![qido-rs-error](https://user-images.githubusercontent.com/28839674/75335947-9c588700-588a-11ea-8a86-d38c4f69f536.png)

I've temporarily fixed the issue by going into ```Configuration``` -> ```Devices``` -> ```dcm4chee-arc``` -> ```Device Extension``` under Extensions -> ```Web Applications``` under it's child objects and removing the Property: "roles=user,admin" for each web application.

![prop](https://user-images.githubusercontent.com/28839674/75336300-2d2f6280-588b-11ea-867d-4aa6277984b7.png)

I've had the problem with both fresh installs for the secured version following:
https://github.com/dcm4che/dcm4chee-arc-light/wiki/Secure-Archive-UI-and-RESTful-Services-using-Keycloak
and upgrades following:
https://github.com/dcm4che/dcm4chee-arc-light/wiki/Upgrade#apache-ds-200 and
https://github.com/dcm4che/dcm4chee-arc-light/wiki/Upgrade-Secured#ldap-configuration

The log files under ```$WILDFLY/standalone/log``` don't provide any information regarding the error.

It just seems strange that I would have to remove the roles property, as I would imagine it's there for access control reasons. Don't know if it's a bug in the current upgrade script for the latest version or if it's a problem with the new study UI, but hope it can be fixed.

The installation is running on:
- OS: CentOS 7
- Browsers: Chrome, Firefox, Internet Explorer
- Version: 5.21.0

**Comment by vrindanayak** [comment]
Since [Restrict DICOM RESTful services according configured Web Applications](https://github.com/dcm4che/dcm4chee-arc-light/issues/2400) was requested in [dcm4che user forum post](https://groups.google.com/forum/#!searchin/dcm4che/2400%7Csort:date/dcm4che/ER1mkCd9kkM/EDeuQFSgAAAJ), it was implemented as part of [Release 5.21.0](https://github.com/dcm4che/dcm4chee-arc-light/releases/tag/5.21.0) 

The user with which you logged didn't contain the roles, hence you got `403-Forbidden`. As part of 5.22.0 version (yet to be released), these [default pre-configured roles have been removed](https://github.com/dcm4che/dcm4chee-arc-light/issues/2440)

**Comment by Syrlander** [comment]
@vrindanayak, Thanks for the response, it's good to know that it'll be fix in upcoming versions.

**Comment by gunterze** [comment]
Cannot reproduce the issue with 5.21.0-secure and default configuration. Are you sure, that there was not some stale state in your browser (cookie) cache. Can you reproduce the issue from a private window of your browser?

**Comment by Syrlander** [comment]
@gunterze, the problem still seems to persist when accessed from a private window. The specific installation I'm currently working with is running on a Vagrant VM, but I've also experienced the issue with installations not running on VMs. For the time being, I've still just gone through all Web Applications and removed the property, which seems to work.

![Screenshot from 2020-03-03 08-15-26](https://user-images.githubusercontent.com/28839674/75751657-4a4eb000-5d27-11ea-8735-6de5cf950da3.png)

**Comment by gunterze** [comment]
Verify the content of the JWT token in the Authorization field of the request. E.g.:
```
$ echo eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI4eGVGTDZjUmozX3A1T3pnWGs4bnZpb1ZGbzA3Sk5BcmhMQ2NHdVI0bWxvIn0.eyJqdGkiOiIwZGRhMDY2Mi05NDAwLTRhNDEtODBjZS00NjJjNDgzYzQyY2UiLCJleHAiOjE1ODMyMjQ4NTMsIm5iZiI6MCwiaWF0IjoxNTgzMjI0NTUzLCJpc3MiOiJodHRwczovL3Rlc3Qtbmc6ODg0My9hdXRoL3JlYWxtcy9kY200Y2hlIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImZhZGQ5YTEwLTYyZjYtNGI4Ni1hNmNkLTNkMTllYzUxYmU0MSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImRjbTRjaGVlLWFyYy11aSIsIm5vbmNlIjoiYmViZDg1OTEtNDkxZC00ZWFmLWE1OWEtYjFhM2JkMmNjZGQ0IiwiYXV0aF90aW1lIjoxNTgzMjI0NTUxLCJzZXNzaW9uX3N0YXRlIjoiMGMzN2YzMTYtYmUwNi00YjIxLWFlYzItZGY0MTFkMTExYTU5IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vdGVzdC1uZzo4MDgwIiwiaHR0cHM6Ly90ZXN0LW5nOjg0NDMiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInVzZXIiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIiwiZ2l2ZW5fbmFtZSI6IiIsImZhbWlseV9uYW1lIjoiIn0.CN4K8ldpgIa-eSPzMJlc1A1qirakr-z7eKLIDKxlChCUK4U5IoxTU4_nWZmeKsBNiE4ny0VjIcWSFdyx8-TWnS-GCBPmc0KZNDQ1Q2gzOzSbME2xu6LB5CJnGxlfsfinnhZVYfHwjq0OYmOqMVltc9byQan8ckmVL9elyvFbrGE5xZ5JkYiVompNH-Fn0sR9ETWCKtel47ViJtr501O0SbbCZRGQ28sfkbtbyDV4tJTPRS6gTUXysBCgNmjgCRGcRyRSbUJNgroFonkrFV5A1N7H0e7GkO5EjDfEOluRiU3qk8cnV55ASxLhRz9yMMYtWuSEgNpqKR2F7SMKfSACjQ | cut -d. -f2 | base64 -d | python -m json.tool
base64: invalid input
{
    "acr": "0",
    "allowed-origins": [
        "http://test-ng:8080",
        "https://test-ng:8443"
    ],
    "aud": "account",
    "auth_time": 1583224551,
    "azp": "dcm4chee-arc-ui",
    "email_verified": false,
    "exp": 1583224853,
    "family_name": "",
    "given_name": "",
    "iat": 1583224553,
    "iss": "https://test-ng:8843/auth/realms/dcm4che",
    "jti": "0dda0662-9400-4a41-80ce-462c483c42ce",
    "nbf": 0,
    "nonce": "bebd8591-491d-4eaf-a59a-b1a3bd2ccdd4",
    "preferred_username": "user",
    "realm_access": {
        "roles": [
            "user"
        ]
    },
    "resource_access": {
        "account": {
            "roles": [
                "manage-account",
                "manage-account-links",
                "view-profile"
            ]
        }
    },
    "scope": "openid email profile",
    "session_state": "0c37f316-be06-4b21-aec2-df411d111a59",
    "sub": "fadd9a10-62f6-4b86-a6cd-3d19ec51be41",
    "typ": "Bearer"
}
```

**Comment by gunterze** [comment]
Could reproduce the issue: Happens with secured UI, but **not** secured REST services! (docker image: 5.21.0-secure-**ui**)
