### ISSUE TITLE
Store SCP slowly

### ISSUE THREAD

**Issue by tienninhptit** [dcm4che/dcm4chee-arc-light#2468]
When I send dicom images from SCU to DCM4CHEE, images received slowly with network address 172.16.x.x /24 (Network Class B)
But I change network address to 192.168.1.x/24 (Class C ) , images sent very fast.  After that, I reboot the system and continue slowly. 

Software vesion. 
 - OS: Ubuntu 18.04
 - dcm4chee-arc-5.21-mysql
 - wildfly 18.0
 - openjdk-8-jdk

(I've install without docker) 

* SCU Status *

10:41:50,589 DEBUG - STORESCU->DCM4CHEE(1) << 3:C-STORE-RQ Dataset sent
10:41:50,590 INFO  - STORESCU->DCM4CHEE(1) << 4:C-STORE-RQ[pcid=5, prior=0
  cuid=1.2.840.10008.5.1.4.1.1.2 - CT Image Storage
  iuid=1.2.392.200036.9123.100.11.12.400002320.2.2019030209532206.3 - ?
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian]
10:41:50,592 DEBUG - STORESCU->DCM4CHEE(1) << 4:C-STORE-RQ Command:
(0000,0002) UI [1.2.840.10008.5.1.4.1.1.2] AffectedSOPClassUID
(0000,0100) US [1] CommandField
(0000,0110) US [4] MessageID
(0000,0700) US [0] Priority
(0000,0800) US [0] CommandDataSetType
(0000,1000) UI [1.2.392.200036.9123.100.11.12.400002320.2.2019030209532206.3]

Thanks for your help,

**Comment by gunterze** [comment]
I am quite sure, that's not an application issue.

By default configuration, the listening port is bind to all IP4 addresses ([Bind Address](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/dcmNetworkConnection.html#dcmbindaddress) = 0.0.0.0). Don't think, it make a difference if only binding one a specific IP of the host.

My knowledge about network issues is rather limited. Perhaps someone reading https://groups.google.com/forum/#!forum/dcm4che can help.
