### ISSUE TITLE
UI Navigation : Linking Study to MWL is restricted

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2498]
![image](https://user-images.githubusercontent.com/15785031/77169162-57a2c300-6ab9-11ea-99ae-3048665c801b.png)

**Comment by shral** [comment]
Can you @vrindanayak describe a little bit what were you trying to do and how can I reproduce this?

**Comment by vrindanayak** [comment]
@shral : Test steps attached

file:///home/vrinda/work/issues-worked-working-On/2498_UI_MWL_Link-issue.pdf

**Comment by vrindanayak** [comment]
[2498_issue.pdf](https://github.com/dcm4che/dcm4chee-arc-light/files/4419722/2498_issue.pdf)

Issue still persists, this time error comes up on the Link to MWL itself. Test steps attached.
