### ISSUE TITLE
UI: in-process indicator is not closed on receive of the 204 HTTP response on reschedule of export tasks

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2500]

**Comment by shral** [comment]
Would you @gunterze explane more what do you mean by that and how I can reproduce that?

**Comment by vrindanayak** [comment]
@shral : [Test steps](https://github.com/dcm4che/dcm4chee-arc-light/files/4419969/2500_issue.pdf) attached.
