### ISSUE TITLE
UI Navigation : RESTful services invoked with 'http' for Web Applications with 'https' Network Connection

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2509]
![image](https://user-images.githubusercontent.com/15785031/78012713-a9630d00-7345-11ea-810f-b04a3138d50f.png)

![image](https://user-images.githubusercontent.com/15785031/78013182-648ba600-7346-11ea-89f7-321971eab9dc.png)

**Comment by shral** [comment]
To be able the UI to recognize the connection as HTTPS, one of the checkboxes in the Attribute TLS CipherSuites must be checked:
![image](https://user-images.githubusercontent.com/7990614/108876539-9b257b80-75fe-11eb-876e-2046ef2662ec.png)
