### ISSUE TITLE
LDAP docker image: Optionally merge vendor data with content of directories or ZIPs specified by ENV

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2519]
### `EXT_VENDOR_DATA_PATH`

Space separated paths to directories or ZIP files merged with default vendor data, effective on first LDAP startup, invoke of `update-data <version>` or `replace-vendor-data`.

**Comment by petrkalina** [comment]
- invoke `replace-vendor-data` the replacement does not take place. So this is rather effective "on first invocation of `replace-vendor-data` after re-creation of the container"..

**Comment by gunterze** [comment]
This behavior is indented to avoid re-generation of  `/etc/openldap/data/vendor-data.zip` on each invocation of `merge-vendor-data.sh`, which is not only invoked by `replace-vendor-data`.

You have to recreate the container for re-generation of `/etc/openldap/data/vendor-data.zip`.
