### ISSUE TITLE
Modification of pre-configure Invoke Image Display Patient/Study URLs during import

### ISSUE THREAD

**Issue by nroduit** [dcm4che/dcm4chee-arc-light#2539]
The issue is related to https://github.com/dcm4che/dcm4chee-arc-light/issues/2241

When adding in docker-compose.env:
```
IID_STUDY_URL=weasis://$dicom:rs --url "http://192.168.0.31:8080/dcm4chee-arc/aets/DCM4CHEE/rs" -r "&studyUID={}"  --query-ext "&includedefaults=false" -H "Authorization: &access_token={}"
```
The result in the properties:
```
IID_STUDY_URL=weasis://$dicom:rs --url "http://192.168.0.31:8080/dcm4chee-arc/aets/DCM4CHEE/rs" -r "dcmProperty: IID_STUDY_URL=studyUID={}" --query-ext "dcmProperty: IID_STUDY_URL=includedefaults=false" -H "Authorization: dcmProperty: IID_STUDY_URL=access_token={}"
```
When importing the character **&** is replaced with "**dcmProperty: IID_STUDY_URL=**".

**Comment by gunterze** [comment]
`&` has to be escaped by `\&`. Updated [README.md](https://github.com/dcm4che-dockerfiles/slapd-dcm4chee/blob/master/README.md#iid_patient_url)

### `IID_PATIENT_URL`

URL to launch external Image Display for a Patient. `{}` will be replaced by the Patient ID formatted as HL7 CX data type. `&` has to be escaped by `\&`.
E.g.: `http(s)://<viewer-host>:<viewer-port>/IHEInvokeImageDisplay?requestType=PATIENT\&patientID={}`.

### `IID_STUDY_URL`

URL to launch external Image Display for a Study. `{}` will be replaced by the Study Instance UID. `&` has to be escaped by `\&`. 
E.g.: `http(s)://<viewer-host>:<viewer-port>/IHEInvokeImageDisplay?requestType=STUDY\&studyUID={}`.

**Comment by nroduit** [comment]
Thanks for the clarification!

**Comment by gunterze** [comment]
Thanks for notifying us about the missing information!
