### ISSUE TITLE
"errorMessage":"No Web Application with QIDO_RS service class found for Application Entity: dcm4chee"

### ISSUE THREAD

**Issue by Vishal568** [dcm4che/dcm4chee-arc-light#2557]
Hello team,

When I getting Studylist from dcm4che secure with auth token its throwing error message "errorMessage":"No Web Application with QIDO_RS service class found for Application Entity: dcm4chee" 

Url : http://hostip:8080/dcm4chee-arc/aets/dcm4chee/rs/studies?includefield=all&StudyDate=17460707-20200420
headers : Authorization : bearer {{token}}

output :  "errorMessage":"No Web Application with QIDO_RS service class found for Application Entity: dcm4chee"

**Comment by gunterze** [comment]
Please post question to https://groups.google.com/forum/#!forum/dcm4che
