### ISSUE TITLE
ldapadd -f dcm4chee-archive.ldif fails with sysmalloc: Assertion 

### ISSUE THREAD

**Issue by jpaoletti** [dcm4che/dcm4chee-arc-light#2568]
Trying to install acording the README with the current options, leads me to the current dead-end:

In "OpenLDAP with dynamic runtime configuration" , the first and second command works fine but the 3rd command throws the following error:

```
sudo ldapadd -vvv -Y EXTERNAL -H ldapi:/// -f /tmp/dcm4chee-arc-5.22.1-mysql/ldap/slapd/dcm4chee-archive.ldif

ldap_initialize( ldapi:///??base )
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
ldapadd: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
```

And thats it, the next file also fail and the overall process fail most likely due to this error. I think its some kind of error in dcm4chee-archive.ldif but can't say for sure.

Thanks best regards

**Comment by shral** [comment]
Hi @jpaoletti you schould first ask your question on the [google forum](https://groups.google.com/forum/#!forum/dcm4che). Meybe there is someone who had the same problem and maybe someone will have the smae problem in the future. All developer are reading the forum and responding there!

**Comment by gunterze** [comment]
Seems there is an issue with openldap's `ldapadd` utility concerning larger object descriptions.

You may workaround by creating an empty schema description by
```console
$ sudo ldapadd -Y EXTERNAL -H ldapi:/// 
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
```
```
dn: cn=dcm4chee-archive,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: dcm4chee-archive
<CTRL^D>
```
And modifying it by
```console
$ sudo ldapmodify -Y EXTERNAL -H ldapi:/// -f dcm4chee-arc-5.22.1-psql-secure-ui/ldap/slapd/dcm4chee-archive-modify.ldif
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "cn={6}dcm4chee-archive,cn=schema,cn=config"
```

**Comment by jpaoletti** [comment]
We endend using apacheDS after fixing some issues in it. 

For the record, you can install ldif without Apache DS Studio (we installed everything in a server without interface) using:

ldapadd -h localhost -p 10389 -D "uid=admin,ou=system" -f $DCM4CHEE/ldap/apacheds/dicom.ldif -x -w secret
ldapadd -h localhost -p 10389 -D "uid=admin,ou=system" -f $DCM4CHEE/ldap/apacheds/dcm4che.ldif -x -w secret
ldapadd -h localhost -p 10389 -D "uid=admin,ou=system" -f $DCM4CHEE/ldap/apacheds/dcm4chee-archive.ldif -x -w secret
ldapadd -h localhost -p 10389 -D "uid=admin,ou=system" -f $DCM4CHEE/ldap/apacheds/dcm4chee-archive-ui.ldif -x -w secret
ldapadd -h localhost -p 10389 -D "uid=admin,ou=system" -f $DCM4CHEE/ldap/init-baseDN.ldif -x -w secret
ldapadd -h localhost -p 10389 -D "uid=admin,ou=system" -f $DCM4CHEE/ldap/init-config.ldif -x -w secret
ldapadd -h localhost -p 10389 -D "uid=admin,ou=system" -f $DCM4CHEE/ldap/default-config.ldif -x -w secret
ldapadd -h localhost -p 10389 -D "uid=admin,ou=system" -f $DCM4CHEE/ldap/default-ui-config.ldif -x -w secret

Of course using correct credentials.

Best regards and thanks for such a great software!

**Comment by gunterze** [comment]
Another workaround is to reduce the size of the LDIF file by converting the line ending from `\r\n` to `\n`:

```console
$ tr -d \\r < $DCM4CHEE/ldap/slapd/dcm4chee-archive.ldif | sudo ldapadd -Y EXTERNAL -H ldapi:///
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=dcm4chee-archive,cn=schema,cn=config"
```

**Comment by gunterze** [comment]
Changed line separator from CR LF in LF in LDIF files provided in binary distribution package

**Comment by gunterze** [comment]
Opened https://bugs.launchpad.net/openldap/+bug/1877557
