### ISSUE TITLE
How to add user to Wildfly Administration Console by runing (Run minimum set of archive services on a single host)

### ISSUE THREAD

**Issue by sathishravula** [dcm4che/dcm4chee-arc-light#2594]
Welcome to WildFly
Your WildFly Application Server is running.

However you have not yet added any users to be able to access the admin console.

To add a new user execute the add-user.sh script within the bin folder of your WildFly installation and enter the requested information.

By default the realm name used by WildFly is "ManagementRealm" this is already selected by default.

After you have added the user follow this link to Try Again.

![image](https://user-images.githubusercontent.com/6880713/82658621-f1672780-9c44-11ea-822a-59a016e8a4e4.png)

**Comment by vrindanayak** [comment]
Please ask question in [dcm4che user forum](https://groups.google.com/forum/#!forum/dcm4che)
