### ISSUE TITLE
java.security.KeyStoreException: ${env.KEYSTORE_TYPE} not found

### ISSUE THREAD

**Issue by vimalgupta** [dcm4che/dcm4chee-arc-light#2608]
Hi team,

while I am deploying the dcm4chee-arc-ear-5.22.1-psql.ear file into wildfly, i am getting below error.

{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"WFLYCTL0080: Failed services" => {"jboss.deploy
ment.subunit.\"dcm4chee-arc-ear-5.22.1-psql.ear\".\"dcm4chee-arc-service-5.22.1.jar\".component.ArchiveServiceImpl.START" => "java.lang.IllegalStateException: WFLYEE0042
: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: javax.ejb.EJBException: java.lang.RuntimeException: java.security.KeyStoreException: ${env.KEYSTORE_TYPE} not found
    Caused by: java.lang.RuntimeException: java.security.KeyStoreException: ${env.KEYSTORE_TYPE} not found
    Caused by: java.security.KeyStoreException: ${env.KEYSTORE_TYPE} not found
    Caused by: java.security.NoSuchAlgorithmException: ${env.KEYSTORE_TYPE} KeyStore not available"}}}}

I have setup the manual environment for wildfly and dcm4chee and running ldcm4che/slapd-dcm4chee:2.4.48-22.1 with docker for ldap purpose  

Please let me know  the fix for it so that i can able to deploy it.

**Comment by gunterze** [comment]
Default configuration in docker image [dcm4che/slapd-dcm4chee](https://github.com/dcm4che-dockerfiles/slapd-dcm4chee) relies that the archive sees following ENVs;
```console
$ curl -s https://raw.githubusercontent.com/dcm4che-dockerfiles/slapd-dcm4chee/master/ldap/data/default-config.ldif | grep env | sort | uniq
dcmKeyStoreKeyPin: ${env.KEY_PASSWORD}
dcmKeyStorePin: ${env.KEYSTORE_PASSWORD}
dcmKeyStoreType: ${env.KEYSTORE_TYPE}
dcmKeyStoreURL: file://${env.KEYSTORE}
dcmTrustStorePin: ${env.TRUSTSTORE_PASSWORD}
dcmTrustStoreURL: file://${env.TRUSTSTORE}
```
s. [Environment Variables](https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/blob/master/README.md#environment-variables) of docker image `dcm4che/dcm4chee-arc-psql`

**Comment by gunterze** [comment]
You may just re-pull
```
$ docker pull dcm4che/slapd-dcm4chee:2.4.48-22.2
```
which now (#2609) includes a script for doing that adjustment:

Usage:
```console
$ docker exec <ldap-container-name> rmenv
modifying entry "dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org"
```
