### ISSUE TITLE
How To : Configure UI in a language other than English

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2610]
Steps and configurations required to make UI available in a language other than English

**Comment by vrindanayak** [comment]
[Different languages for Archive UI](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Different-languages-for-Archive-UI)

**Comment by Talos06100** [comment]
Hello Vrinda, i'm reading the procedure, but i'm confused. Is the src repertory inside the .war file ? If so, is this the only way to change the langage in dcm4chee arc-light ui ??

**Comment by vrindanayak** [comment]
> Hello Vrinda, i'm reading the procedure, but i'm confused. Is the src repertory inside the .war file ? If so, is this the only way to change the langage in dcm4chee arc-light ui ??

Please see the updated wiki page, where it should be clearer how a different non-English language (existing in dcm4chee-arc-lang repository) can be enabled or a new one can be added
