### ISSUE TITLE
DICOM Conformance Statement: Describe usage of Study Instance UID 1.2.40.0.13.1.15.110.3.165.1 and  Patient ID <none> for "unknown study/patient" in Audit message

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2614]
Describe usage of _Study Instance UID_ `1.2.40.0.13.1.15.110.3.165.1` for "unknown" in Audit messages 

- [x] [Begin Transferring DICOM Instances](https://dcm4chee-arc-cs.readthedocs.io/en/latest/security/audit/begin-transferring-dicom-instances.html)
- [x] [Data Export](https://dcm4chee-arc-cs.readthedocs.io/en/latest/security/audit/data-export.html)
- [x] [DICOM Instances Accessed](https://dcm4chee-arc-cs.readthedocs.io/en/latest/security/audit/dicom-instances-transferred.html)
- [x] [DICOM Instances Transferred](https://dcm4chee-arc-cs.readthedocs.io/en/latest/security/audit/dicom-instances-transferred.html)
- [x] [DICOM Study Deleted](https://dcm4chee-arc-cs.readthedocs.io/en/latest/security/audit/dicom-study-deleted.html)
- [x] [Patient Record](https://dcm4chee-arc-cs.readthedocs.io/en/latest/security/audit/patient-record.html)
- [x] [Procedure Record](https://dcm4chee-arc-cs.readthedocs.io/en/latest/security/audit/procedure-record.html)
- [x] [Security Alert](https://dcm4chee-arc-cs.readthedocs.io/en/latest/security/audit/security-alert.html)

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-cs/commit/84551030e7796504b2e89c255bbe6f0afa9445fe
