### ISSUE TITLE
UI Navigation Studies: Download ZIP including DICOMDIR

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2619]
Provide two additional widgets for download Study/Series/Object uncompressed or as stored at the archive in ZIP **including DICOMDIR**:

Function | URL
-- | -- 
Retrieve Study uncompressed with DICOMDIR | [/dcm4chee-arc/​aets​/{aet}​/rs​/studies​/{study}​?accept=application/zip&dicomdir=true](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveStudy)
Retrieve Series as stored at the archive with DICOMDIR | [/dcm4chee-arc/​aets​/{aet}​/rs​/studies​/{study}​?accept=application/zip;transfer-syntax=*&dicomdir=true](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveStudy)
Retrieve Series uncompressed with DICOMDIR | [/dcm4chee-arc/​aets​/{aet}​/rs​/studies​/{study}​/series​/{series}?accept=application/zip&dicomdir=true](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveSeries)
Retrieve Series as stored at the archive with DICOMDIR | [/dcm4chee-arc/​aets​/{aet}​/rs​/studies​/{study}​/series​/{series}?accept=application/zip;transfer-syntax=*&dicomdir=true](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveSeries)
Retrieve Object uncompressed with DICOMDIR | [/dcm4chee-arc/​aets​/{aet}​/rs​/studies​/{study}​/series​/{series}​/instances​/{instance}?accept=application/zip&dicomdir=true](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveInstance)
Retrieve Object as stored at the archive with DICOMDIR | [/dcm4chee-arc/​aets​/{aet}​/rs​/studies​/{study}​/series​/{series}​/instances​/{instance}?accept=application/zip;transfer-syntax=*&dicomdir=true](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveInstance)

Propose icons derived from icons for download without DICOMDIR + CD symbol

Requires #2618

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/86033530-5e868d80-ba39-11ea-994b-a0e7b2656f0d.png)

**Comment by shral** [comment]
![image](https://user-images.githubusercontent.com/7990614/86033618-8249d380-ba39-11ea-9366-add7851eb729.png)
