### ISSUE TITLE
UI Navigation -> Studies : SOP Classes in Study filter broken

### ISSUE THREAD

**Issue by sgala** [dcm4che/dcm4chee-arc-light#2649]
**Describe the bug**
The commit 7b4bc4666a2b613f8941065ab81546127f9cd938 caused a regression in the fix of https://github.com/dcm4che/dcm4chee-arc-light/issues/2414 in  https://github.com/dcm4che/dcm4chee-arc-light/commit/4e0cc95d08c1bdde76cd26ffd83ba242aa9f8522

**To Reproduce**
See https://github.com/dcm4che/dcm4chee-arc-light/issues/2414#issuecomment-650062919

**Expected behavior**
Not sure if the fix was good, I never tried before, but I'd expect to be able to select from a dictionary of SOP Class UIDs. In 5.19 you'd have to type one in a text input.

**Screenshots**
See it in the comment above

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox
 - Version 77.0.1

I'm seeing it not working, I see this: 
![Screenshot from 2020-06-26 10-40-11](https://user-images.githubusercontent.com/2065/85838291-a25b6780-b799-11ea-8713-04b40ae974ed.png)

**Comment by vrindanayak** [comment]
Fixed by https://github.com/dcm4che/dcm4chee-arc-light/commit/e440848b9b7518092ac881cfb4f5985a5365c6fd
