### ISSUE TITLE
UI: Setting TCP Backlog to 0 results in "internal server error"

### ISSUE THREAD

**Issue by wkochFPV** [dcm4che/dcm4chee-arc-light#2670]
Tested with version 5.22.1:

In user interface set

Devicelist -> dcm4chee-arc -> Child object: localhost:4006 DICOM -> Network Connection Extension -> TCP Backlog to 0

results in "internal server error" when saving.

**Comment by gunterze** [comment]
TCP Backlog must be > 0
```
Error detail
java.lang.IllegalArgumentException: backlog: 0 at org.dcm4che.net@5.22.4//org.dcm4che3.net.Connection.setBacklog(Connection.java:407) at 
```
