### ISSUE TITLE
Images in "Getting OIDC Access Token using curl" of the Wiki invisible

### ISSUE THREAD

**Issue by ChristianGeng** [dcm4che/dcm4chee-arc-light#2708]
**Describe the bug**

[Getting OIDC Access Token using curl](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Getting-OIDC-Access-Token-using-curl) are not rendered. 

**To Reproduce**
Navigating to the above link shows only placeholders instead of real images. 

**Expected behavior**
Images demonstrating the keycloak client settings would be shown. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 
 - Chromium

**Additional context**
Works fine in firefox

**Comment by vrindanayak** [comment]
The images are displayed on the wiki (checked with both Firefox and Chrome).
![Screenshot_2020-08-08 dcm4che dcm4chee-arc-light](https://user-images.githubusercontent.com/15785031/89715224-a25ba380-d9a4-11ea-8be1-5be4dd0214ff.png)

![Screenshot_2020-08-08 dcm4che dcm4chee-arc-light(1)](https://user-images.githubusercontent.com/15785031/89715228-a5ef2a80-d9a4-11ea-91ba-72563d1a4f00.png)

Pleasepost further questions in [dcm4che user forum](https://groups.google.com/g/dcm4che)
