### ISSUE TITLE
Study access date time query filter is ineffective in RESTfule services

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2716]
Applicable to all services mentioned in #1774 

Caused by #1806 [commit](https://github.com/dcm4che/dcm4chee-arc-light/commit/60a04c6b237319651c64e648f0669e208c13dcaf#diff-10dd71da7a2cbde6c6b19350b67e678a)

**Comment by sgala** [comment]
Sometimes I do and get no feedback at all. For instance I found that in some cases (having middle_name) the fuzzy search does not include the  exact match (see https://groups.google.com/g/dcm4che/c/VrURK50TBAk/m/t6JZF0fuAgAJ ) . No answer at all, and I think it is a bug, but I can't understand how the code works...

**Comment by gunterze** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/issues/2718
