### ISSUE TITLE
QIDO orderby SeriesNumber or InstanceNumber return literal instead numeric ordered matches 

### ISSUE THREAD

**Issue by OrNot** [dcm4che/dcm4chee-arc-light#272]
when query a study by orderby seriesnumber (00200011), suppose the series number is from 1 to 15, the final results ' order  will be  1, 10, 11, 12,13,14, 15 ,2, 3.....       .   This is the case for 4.x . I have  not run the 5.x but from code I doubt it might be still there.    

Not a big issue but worth taking a check for 5.x .

**Comment by gunterze** [comment]
It's caused because series and instance number are stored in a VARCHAR column.
We will change it to an INTEGER column.
