### ISSUE TITLE
Testplan for Utilizing Unified Worklist (UWL) for queuing of DICOM Export Tasks

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2725]
Related #2347, #2689, #2694, #2710, #2712

**Comment by vrindanayak** [comment]
[Replace Queuing of Export Tasks using UWL](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Replace-Queuing-of-Export-Tasks-using-UWL)
