### ISSUE TITLE
Testplan for Utilizing Unified Worklist (UWL) for queuing of Retrieve Tasks

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2726]
Related #2346, #2690, #2695, #2711, #2713

**Comment by vrindanayak** [comment]
[Replace Queuing of Retrieve Tasks using UWL](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Replace-Queuing-of-Retrieve-Tasks-using-UWL)
