### ISSUE TITLE
Extend UI language list configuration to support Italian

### ISSUE THREAD

**Issue by marcheschi** [dcm4che/dcm4chee-arc-light#2740]
Please add Italian language.
Reference #2728   

Thank you
Paolo

**Comment by vrindanayak** [comment]
Extends #2728 
Related : https://github.com/dcm4che/dcm4chee-arc-lang/commit/8c473fa4efe756d67f3f0c1f883753988a6a76ad

![image](https://user-images.githubusercontent.com/15785031/91331298-e6cfa780-e7ca-11ea-8f09-1bb4a471779a.png)
