### ISSUE TITLE
ERROR SENDING HL7 DCM4CHEE-ARC MESSAGE

### ISSUE THREAD

**Issue by andersoncav** [dcm4che/dcm4chee-arc-light#2744]
Good afternoon,

I'm trying to send the msg hl7 to dcm4chee-arc but without success, the same message worked on dmc4chee-web3
RIS/WORKLIST

MSH|^~\&|MESA_OF|XYZ_RADIOLOGY|MESA_IM|XYZ_IMAGE_MANAGER|20200827105605||ORM^O01|100112|P|2.3.1|||||| || 
PID|||123456789^^^ADT123456789||Paciente Teste TI NAO DELETAR^-||19840209|F||WH|820 JORIE BLVD^^CHICAGO^IL^60523|||||||20-98-4000||||||||||||||||||||| 
PV1||E|ED||||1234^WEAVER^TIMOTHY^-^^-|5101^-^^-^^-|0000^Consulting^Doctor^P^^DR|HSR|||||AS||0000^Admitting^Doctor^P^^DR||V100^^^ADT1|||||||||||||||||||||||||20200827105605|||||||V| 
ORC|NW|A100Z^ARCOSCOSTAISD^^^ARCOSCOSTAISD|B100Z^MESA_ORDFIL||SC||1^once^^^^S||20200827105605|^ROSEWOOD^RANDOLPH||7101^ESTRADA^JAIME^P^^DR|Enterer^^Location^EL^00000|(314)555-1212|200008161510||922229-10^IHE-RAD^IHE-CODE-231|| 
OBR|1|A100Z^MESA_ORDPLC|B100Z^MESA_ORDFIL|P1^Procedure 1&ARCOSCOSTAISD&ARCOSCOSTAISD&ARCOSCOSTAISD&ARCOSCOSTAISD^ERL_MESA^CR^ARCOSCOSTAISD^AMIL|||||||||||Radiology^^^^R|7101^ESTRADA^JAIME^P^^DR||244526111|244526111|244526111||||CR|||1^once^^^^S|||AMIL|ARCOSCOSTAISD^ARCOSCOSTAISD^ARCOSCOSTAISD||||||||||A|||244526111^ARCOSCOSTAISD||&FNAME&GNAME&MNAME&SUFFIX&PREFIX^FNAME^GNAME^MNAME^^SUFFIX|&ADMIN&ADMIN&ADMIN&M.D.&DR.^ADMIN^ADMIN^ADMIN^DR.^M.D.|||||||||PROCEDURECODE^^^^ARCOSCOSTAISD|| 
DG1||I9|824^ARCOSCOSTAISD^I9|ARCOSCOSTAISD|||||||||||ARCOSCOSTAISD|ARCOSCOSTAISD| 
ZDS|1.2.4.0.13.1.432252867.244526111.1^100^Application^DICOM

**Comment by vrindanayak** [comment]
Post questions in [dcm4che forum](https://groups.google.com/forum/#!forum/dcm4che).

I've already commented regarding the above [HL7 message](https://github.com/dcm4che/dcm4chee-arc-light/issues/1586#issuecomment-682011570)
