### ISSUE TITLE
dcm4chee 5.22.3  patient study id matching problem!!!

### ISSUE THREAD

**Issue by telemy** [dcm4che/dcm4chee-arc-light#2758]
Hi, Two separate records with the same work ID are combined under a single record. How can we prevent two different records with the same work ID from merging?

![OK_NO_PROBLEM](https://user-images.githubusercontent.com/70746929/92222055-16577180-eea7-11ea-8154-7944d753c4de.jpg)  dcm4chee-web3 no problem

![PROBLEM](https://user-images.githubusercontent.com/70746929/92222063-16f00800-eea7-11ea-8f96-1c7132e702ad.jpg)  dcm4chee-arc/ui2  5.22.3  problem???

Thanks...

**Comment by gunterze** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/wiki/Coerce-Issuer-of-Patient-ID

Post questions in https://groups.google.com/forum/#!forum/dcm4che
