### ISSUE TITLE
UI Navigation : Link instances to MWL does not consider all selected entities

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2773]
Request body of the service shall be sent as defined in [Link Instances with MWL Entry](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/LinkInstancesWithMWLEntry)

[Test steps to simulate the issue](https://github.com/dcm4che/dcm4chee-arc-light/files/5223785/UI-MWL-link-issue.pdf)

Related #929

**Comment by shral** [comment]
The https://github.com/dcm4che/dcm4chee-arc-light/issues/2774 issue should fix this too.

**Comment by vrindanayak** [comment]
See https://github.com/dcm4che/dcm4chee-arc-light/issues/2774#issuecomment-694177627
