### ISSUE TITLE
UI Navigation : Copy / Move of entities does not consider all selected entities

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2774]
Request body of the service shall be sent as defined in
- [Copy Instances to a Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/CopyInstances)
- [Move Instances to a Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/MoveInstances)

[Test steps to simulate the issue](https://github.com/dcm4che/dcm4chee-arc-light/files/5224441/UI-move-entities-issue.pdf) : Shows only Move entities, but same test steps also applicable for copy entities

Related #2773 , #266

**Comment by vrindanayak** [comment]
Fix doesn't on object level copy / move / link : See test steps attached (includes screenshots only for link, but same can be applied to copy / move as well) : [2773-2774-object-level-issue-persists.pdf](https://github.com/dcm4che/dcm4chee-arc-light/files/5238848/2773-2774-object-level-issue-persists.pdf)

**Comment by shral** [comment]
On the PDF- file you are showing @vrindanayak  how to reproduce the link problem but this issue is not for the link, the link "problem" should be fixed with the last push on https://github.com/dcm4che/dcm4chee-arc-light/issues/2773
