### ISSUE TITLE
Getting errors Running Docker Containers

### ISSUE THREAD

**Issue by mackeyja** [dcm4che/dcm4chee-arc-light#2796]
**Describe the bug**
Hello I am installing this software on a RHEL 7 server.
I used docker compose to install the components.

**To Reproduce**
1.  Installed RHEL supplied Docker packages.
2.  Installed docker-compose package from epel
3.  Created docker-compose.yaml and docker-compose.env in /root/
4.  As root ran docker-compose -p dcm4chee up -d
5.  Error:
# docker-compose -p dcm4chee up -d
Starting dcm4chee_db_1 ...
dcm4chee_ldap_1 is up-to-date
Starting dcm4chee_db_1 ... error

ERROR: for dcm4chee_db_1  Cannot start service db: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely"
Starting dcm4chee_keycloak_1 ... error

ERROR: for dcm4chee_keycloak_1  Cannot start service keycloak: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely"

ERROR: for db  Cannot start service db: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely"

ERROR: for keycloak  Cannot start service keycloak: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely"

ERROR: Encountered errors while bringing up the project.

**Expected behavior**
Creating network "dcm4chee_default" with the default driver
Creating dcm4chee_db_1 ... 
Creating dcm4chee_ldap_1 ... 
Creating dcm4chee_db_1
Creating dcm4chee_ldap_1 ... done
Creating dcm4chee_keycloak_1 ... 
Creating dcm4chee_keycloak_1 ... done
Creating dcm4chee_arc_1 ... 
Creating dcm4chee_arc_1 ... done

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Additional context**

**Comment by gunterze** [comment]
Try unsecure version without keycloak first and error logs of containers
```
docker-compose logs ldap
docker-compose logs db 
docker-compose logs arc
```
in https://groups.google.com/u/0/g/dcm4che

**Comment by mackeyja** [comment]
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                  NAMES
805e7f683861        dcm4che/slapd-dcm4chee:2.4.50-22.5   "/docker-entrypoin..."   30 minutes ago      Up 30 minutes       0.0.0.0:389->389/tcp   dcm4chee_ldap_1

# docker-compose logs ldap
Attaching to root_ldap_1
ldap_1  | 5f723c6e @(#) $OpenLDAP: slapd 2.4.50 (May  7 2020 12:49:06) $
ldap_1  |       openldap
ldap_1  | 5f723c6e slapd starting
ldap_1  | 5f723cba daemon: shutdown requested and initiated.
ldap_1  | 5f723cba slapd shutdown: waiting for 0 operations/tasks to finish
ldap_1  | 5f723cba slapd stopped.

# docker-compose logs db
Attaching to root_db_1
db_1    | container_linux.go:235: starting container process caused "container init exited prematurely"

# docker-compose logs arc
Attaching to

**Comment by mackeyja** [comment]
Only the slapd container starts.

**Comment by gunterze** [comment]
Please post deployment issues in https://groups.google.com/u/0/g/dcm4che
