### ISSUE TITLE
UI Navigation Studies: Display Series and SOP Instance UID

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2818]
- Display Series and SOP Instance UID on hover over `UID` link and enable to copy it into clipboard.
- Replace Study Instance UID by `UID` link for consistency.

**Comment by shral** [comment]
A more generic solution (https://github.com/dcm4che/dcm4chee-arc-light/issues/3050) may make this issue obsolete.
