### ISSUE TITLE
Wiki: How to secure Kibana using OAuth2 Proxy with Keycloak as Auth Provider

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2820]
_Rationale_: development on _Keycloak Gatekeeper_ and _Louketo_ has been [terminated by Red Hat](https://www.keycloak.org/2020/08/sunsetting-louketo-project.adoc.html).

https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#keycloak-auth-provider

specialized for using dockerized version of OAuth2 Proxy (quay.io/oauth2-proxy/oauth2-proxy:v6.1.1-amd64) and Keycloak (dcm4che/keycloak:11.0.2).

**Comment by vrindanayak** [comment]
[Secure Kibana using OAuth2 Proxy](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Secure-Kibana-using-OAuth2-Proxy)

**Comment by vrindanayak** [comment]
Test / use https://github.com/oauth2-proxy/oauth2-proxy/pull/767 and https://github.com/oauth2-proxy/oauth2-proxy/issues/956 once available
