### ISSUE TITLE
Replace UPS Processors for eager calculation of study size and study/series query attributes by scheduler

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2824]
[Study Size Query Attributes Calculation](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Study-Size-Query-Attributes-Calculation) wiki

Configurable by [Archive Device](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveDevice.html) attributes:

Name | Type | Description (LDAP Attribute)
-- | -- | --
Calculate Study Size Delay | string | Delay in ISO-8601 duration format PnDTnHnMnS for eager calculation of Study Size and Query Attributes. If absent, no (minimal) delay for eager calculation of the Study Size and Query Attributes is applied.(dcmCalculateStudySizeDelay)
Calculate Study Size Polling Interval | string | Polling Interval for Studies with unknown size in ISO-8601 duration format PnDTnHnMnS. If absent, there is no eager calculation of the Study Size and Query Attributes.(dcmCalculateStudySizePollingInterval)
Calculate Study Size Fetch Size | integer | Limit result set of DB query for Studies with unknown size.(dcmCalculateStudySizeFetchSize)
Calculate Query Attributes | boolean | Indicates to eager calculate Query Attributes configured Calculate Study Size Delay and Calculate Study Size Polling Interval.(dcmCalculateQueryAttributes)

- [x] Update LDAP schema
- [x] Update JSON schema
- [x] Extend `ArchiveDeviceExtension` by corresponding properties
- [x] Implement configuration marshaling to/from LDAP/JSON
- [x] Implement `org.dcm4chee.arc.studysize.impl.StudySizeScheduler` in new module `dcm4chee-arc-study-size`
- [x] Provide default configuration in LDAP with
  - _Calculate Study Size Delay_: `PT5M`
  - _Calculate Study Size Polling Interval_: `PT5M`
  - _Calculate Query Attributes_: `true`
- [x] Remove from default configuration in LDAP:
  - UPS on Store Rules `CALC_QUERY_ATTRS` and `CALC_STUDY_SIZE`
  - UPS Processing Rules `CALC_QUERY_ATTRS` and `CALC_STUDY_SIZE`
  - Exporter Descriptor `CalculateQueryAttributes` and `CalculateStudySize`
- [x] Purge modules
  - `dcm4chee-arc-export-query-attrs`
  - `dcm4chee-arc-export-study-size`
  - `dcm4chee-arc-ups-query-attrs`
  - `dcm4chee-arc-ups-study-size`

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/e1c9b92a2942bcb4dbc71012256764c1f3ddbc41
