### ISSUE TITLE
How to create and config to use my own image compressor / decompressor ?

### ISSUE THREAD

**Issue by OrNot** [dcm4che/dcm4chee-arc-light#284]
Suppose I'd like to create a new encoder to compress the images,  what is the steps for me to follow to make it work.   

I have take a quick reading the source code, in 5.x , it seems to take this part to dcm4che?   

Any help will be appreciated .

Thanks.

**Comment by gunterze** [comment]
You need to write a Java ImageIO Writer, which then can be used by dcm4chee-arc 5.x.
Please post questions about dcm4che/dcm4chee-arc in https://groups.google.com/forum/#!forum/dcm4che .
