### ISSUE TITLE
Wiki : HowTo use various Archive Metrics

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2843]
Related #2842 #2070 #2069 #2068 #2067 #2065 #2056 

[Metrics](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Metrics)

**Comment by gunterze** [comment]
Provide details about
- cloning pre-configured defaults
- replacing `fs1` in _Metrics Name_ with _Storage ID_ of Storage system you want to provide read/write/delete metrics 
- replacing  `STORESCP` in _Metrics Name_ with _AE Title_ of external STORE SCP you want to provide send and concurrently requested associations metrics
- replacing  `STORESCU` in _Metrics Name_ with _AE Title_ of external STORE SCU you want to provide receive and concurrently accepted associations metrics
