### ISSUE TITLE
have some problem ,need help

### ISSUE THREAD

**Issue by 1418677061** [dcm4che/dcm4chee-arc-light#2867]
I have a java medical system,and this system have many patients.Now,how can I put some of them into the dcmche3 system to become the worklist?

**Comment by vrindanayak** [comment]
Questions should be asked in [dcm4che forum](https://groups.google.com/forum/#!forum/dcm4che)

**Comment by 1418677061** [comment]
> Questions should be asked in [dcm4che forum](https://groups.google.com/forum/#!forum/dcm4che)

thanks
