### ISSUE TITLE
ups subscription through DIMSE or RESTful API seems not to work

### ISSUE THREAD

**Issue by codepage949** [dcm4che/dcm4chee-arc-light#2868]
**Describe the bug**

ups subscription by N-ACTION DIMSE service and UPS RESTful service didn't work.

but it was only worked as expected by setting 'UPS Event SCU' attribute of dcm4chee-arc device in dcm4chee-arc-ui.

**To Reproduce**
1. in dcm4chee-arc-ui, register AE(named UPSSCU) that is going to handle N_EVENT_REPORT event.
2. run a program that implements N_EVENT_REPORT handler with pynetdicom enabling debug logger.
3. run `upsscu -c DCM4CHEE@localhost:11112 -O subscribe` and `upsscu -c DCM4CHEE@localhost:11112 -O create`
4. send request POST .../dcm4chee-arc/aets/DCM4CHEE/rs/workitems/1.2.840.10008.5.1.4.34.5/subscribers/UPSSCU with  token and run `upsscu -c DCM4CHEE@localhost:11112 -O create`

**Expected behavior**
some debug messages are printed and N_EVENT_REPORT handler is invoked.

**Desktop (please complete the following information):**
 - OS: debian 10
 - Browser: vivaldi
 - Version: 5.22.6

**Comment by gunterze** [comment]
Guess you did not had configured `UPSSCU` as **UPS Event SCU** on [Archive Device](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveNetworkAE.html#dcmupseventscu) or [Archive Network AE](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveNetworkAE.html#dcmupseventscu) level:
![Screenshot from 2020-11-25 15-38-49](https://user-images.githubusercontent.com/400095/100242211-d697a780-2f34-11eb-87cf-fe4885d27175.png)

**Comment by codepage949** [comment]
@gunterze do you mean **UPS Event SCU** should be configured  first and request ups subscription by DIMSE or RESTful API?

**Comment by gunterze** [comment]
No, you also may configure it after the subscription. It has to been configured when the event is triggered.
