### ISSUE TITLE
UI Configuration for background and logo not working

### ISSUE THREAD

**Issue by mightymouse2045** [dcm4che/dcm4chee-arc-light#2893]
I have configured the background and logo for device however they do not change when I save or restart the archive server

**To Reproduce**
1. Go to the device configuration, extensions then edit the default UI Configuration child.
2. Enter the url to the 140wide transparent PNG file for the logo
3. Save 

**Expected behavior**
Expect to see the logo appear

**Comment by mightymouse2045** [comment]
Any chance of giving an example of how to change the logo or reference to the documentation for this? I also can't change the background image.

**Comment by shral** [comment]
You can not change the logo and background image in the open-source version, that is only on the pro version of the UI possible.
