### ISSUE TITLE
Installation guide inconsistencies

### ISSUE THREAD

**Issue by crossmanith** [dcm4che/dcm4chee-arc-light#2894]
In the installation guide chapter "Setup WildFly" item 10. should refer to item 8. instead of 7. because 7. describes how to install Keycloak and not the jdbc driver. 

Item 14. refers to a script $DCM4CHEE_ARC/cli/adjust-managed-executor.cli which does not exist in the dcm4chee-arc-5.22.6-psql package.

Related #2895

**Comment by gunterze** [comment]
Fixed https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#setup-wildfly
