### ISSUE TITLE
metadata return type has been changed

### ISSUE THREAD

**Issue by linzhidong1984** [dcm4che/dcm4chee-arc-light#2921]
I use ohif-vewer as front and dcm4chee-arc-ligth-5.22.6 as backend in my project.But ,the ohif-vewer can not work ;
When i use  dcm4chee-arc-ligth-5.22.0,it can works well;
The reason is ,in dcm4chee-arc-ligth-5.22.6 ,
this api http://xxx/dcm4chee-arc/aets/DCM4CHEE/rs/studies/xxxx/series/xxx/metadata  
returns some attributes like this :
00200011":{"vr":"IS","Value":["4"]},"00200012":{"vr":"IS","Value":["2"]},"00200013":{"vr":"IS","Value":["234"]} 
the value of "Value" is String;
in dcm4chee-arc-ligth-5.22.0 returns:
"00200011":{"vr":"IS","Value":[4]},"00200012":{"vr":"IS","Value":[2]},"00200013":{"vr":"IS","Value":[1]}
the value of "Value" is Int;

can someone help me to solve this problem? thanks a lot.

**Comment by gunterze** [comment]
s. https://github.com/dcm4che/dcm4che/issues/803, #2922
