### ISSUE TITLE
RESTful Service List Devices: add Query Parameters 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#297]
Support Query Parameters:
- `dicomDeviceName`
- `dicomDescription`
- `dicomManufacturer`
- `dicomManufacturerModelName`
- `dicomStationName`
- `dicomPrimaryDeviceType`
- `dicomInstitutionName`
- `dicomInstitutionDepartmentName`
- `dicomInstalled`

by RESTful Service [List Devices](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#!/CONFIG-RS/listDevices).

**Comment by vrindanayak** [comment]
Already implemented
