### ISSUE TITLE
How to configure multiple HL7 receivers for feeding one or multiple MWL SCPs

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2970]
How to configure multiple HL7 receivers with
- one common or
- multiple, HL7 receiver specific, HL7 to MWL mapping configurations

available
- on one common or
- on multiple, HL7 receiver specific, Network Connections (=TCP port) 

feeding
- one or
- multiple, HL7 receiver specific, MWL SCPs with
    - none or
    - one common or
    - multiple, MWL SCP specific, Attribute Coercions of MWL C-FIND RQs
  
  available  
  - on one common or
  - on multiple, MWL SCP specific, Network Connections (=TCP port)

**Comment by vrindanayak** [comment]
[HL7 Receivers feeding MWL SCPs](https://github.com/dcm4che/dcm4chee-arc-light/wiki/HL7-Receivers-feeding-MWL-SCPs)
