### ISSUE TITLE
RESTful Service to list configured Application Entities

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#298]
[List Application Entities](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#!/CONFIG-RS/listApplicationEntities).

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4che/commit/f6f951efa67e9832b380fc8716e32a2f1a3e74ed
