### ISSUE TITLE
Update Howto: Test IHE SWF using dcm4che tools according IHE SWF.b

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#2985]
Update Howto: [Test IHE SWF using dcm4che tools](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Test-IHE-SWF-using-dcm4che-tools) according [IHE SWF.b](https://www.ihe.net/uploadedFiles/Documents/Radiology/IHE_RAD_TF_Vol1.pdf#page=247), particularly using HL7 v2.5.1 instead HL7 v2.3.1 messages for Transactions
- [Procedure Scheduled [RAD-4]](https://www.ihe.net/uploadedFiles/Documents/Radiology/IHE_RAD_TF_Vol2.pdf#page=103)
- [Patient Update [RAD-12]](https://www.ihe.net/uploadedFiles/Documents/Radiology/IHE_RAD_TF_Vol2.pdf#page=184)

Also update [Query Modality Worklist](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Test-IHE-SWF-using-dcm4che-tools#query-modality-worklist) to reflect attributes used in sample messages as per HL7 v2.5.1

Related https://github.com/dcm4che/dcm4che/issues/871, https://github.com/dcm4che/dcm4che/issues/875

**Comment by vrindanayak** [comment]
- [Procedure Scheduled](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Test-IHE-SWF-using-dcm4che-tools#procedure-scheduled)
- [Query Modality Worklist](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Test-IHE-SWF-using-dcm4che-tools#query-modality-worklist)
- [Patient Update](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Test-IHE-SWF-using-dcm4che-tools#patient-update)
