### ISSUE TITLE
UI Navigation : On switching between tabs, some Patient/MWL attributes disappear  

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#2986]
Veterinary specific patient attributes is consistently displayed only in Patients and Studies tab. On MWL and UWL tabs some attributes disappear if user switches from MWL/UWL tabs to Patients/Studies tabs and comes back to one of these two tabs.
All of the veterinary specific patient attributes are displayed in MWL and UWL tabs **only if** the browser is reloaded and when directly gone to one of these two tabs.

Similarly some MWL attributes also disappear when tabs are switched.

### Test steps to reproduce : 
- Configure a [UPS On Store Rule](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/upsOnStore.html)
- Send [Veterinary HL7 Order msg](https://github.com/dcm4che/dcm4chee-arc-light/files/5842655/test.hl7.zip) using [hl7snd](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-hl7snd/README.md) tool.
- Access archive UI `Navigation` page and directly go to `MWL` tab.
- Select web application and Submit. [All the attributes are seen on Patient / MWL level.](https://github.com/dcm4che/dcm4chee-arc-light/files/5844136/MWL-allAttrsDisplayed.pdf)
- Go to `Patients` tab. Upload some image or pdf to the patient to create a study record.
- Switch back to `MWL` tab and `Submit` to see list of MWLs again.
- [Now only some attributes are displayed on Patient / MWL level.](https://github.com/dcm4che/dcm4chee-arc-light/files/5844144/switchTabs-MWL-attrs.pdf)
- Similar behavior observed on `UWL` tab for Patient / UPS level attributes.
  - [Patient / UPS attributes displayed on reload browser -> UWL tab](https://github.com/dcm4che/dcm4chee-arc-light/files/5844150/UPS-allAttrsDisplayed.pdf)
  - [On switching tabs displayed Patient / UPS attributes](https://github.com/dcm4che/dcm4chee-arc-light/files/5844151/switchTabs-UPS-attrs.pdf)

Tested both on Firefox and Chrome and with unsecure version of archive.

### Expected Behavior
All patient / MWL / UWL attributes should be consistently displayed irrespective of the tabs and switching between tabs.

**Comment by gunterze** [comment]
It's not only affecting attributes shown on Patient Level, but also on MWL level: If only basic patient attributes (Patient Name / ID / Birth Date / Sex) are shown on Patient Level, also not all MWL attributes are shown (e.g.  
-  Patient's Weight (0010,1030)

is shown but not
-   Patient's Size (0010,1020)

![20180510_181237](https://user-images.githubusercontent.com/400095/105209822-90cd1900-5b4a-11eb-9828-8743b3ee1a0b.jpg)

**Comment by gunterze** [comment]
MWL show attributes:

Correct:
![MWL-all-attributes](https://user-images.githubusercontent.com/400095/105691181-342c7e00-5efd-11eb-825f-afd836e9b3cf.png)

Missing attributes:
![MWL-missing-attributes](https://user-images.githubusercontent.com/400095/105691180-3393e780-5efd-11eb-8b30-05602f9b3b0f.png)
