### ISSUE TITLE
Remove stale redundant PHILIPS-IMAGING-DD-001.js and PHILIPS-MR-IMAGING-DD-001.js files

### ISSUE THREAD

**Issue by nuttycat** [dcm4che/dcm4chee-arc-light#3071]
**Overview**
The letter case of file name is confusing and it leads to a problem in case-insensitive file system such as macOSX. 

**Describe the bug**
The letter case of file name "Philips-Imaging-DD-001.js","Philips-Imaging-DD-001.js","PHILIPS-MR-IMAGING-DD-001.js" and "Philips-MR-Imaging-DD-001.js" is confusing and it leads to a problem in case-insensitive file system such as macOSX.

**To Reproduce**
File path:
./dcm4chee-arc-ui2/src/app/constants/
Related files:
PHILIPS-IMAGING-DD-001.js Philips-Imaging-DD-001.js
PHILIPS-MR-IMAGING-DD-001.js Philips-MR-Imaging-DD-001.js

> diff --git a/dcm4chee-arc-ui2/src/app/constants/PHILIPS-IMAGING-DD-001.js b/dcm4chee-arc-ui2/src/app/constants/PHILIPS-IMAGING-DD-001.js
index a422410c8..eae0a2e70 100644
--- a/dcm4chee-arc-ui2/src/app/constants/PHILIPS-IMAGING-DD-001.js
+++ b/dcm4chee-arc-ui2/src/app/constants/PHILIPS-IMAGING-DD-001.js
@@ -1,5 +1,5 @@
 DCM4CHE.elementName.addDictionary({
-"privateCreator":"PHILIPS IMAGING DD 001",
+"privateCreator":"Philips Imaging DD 001",
 "2001xx01":"Chemical Shift",
 "2001xx02":"Chemical Shift Number MR",
 "2001xx03":"Diffusion B-Factor",
@@ -9,8 +9,8 @@ DCM4CHE.elementName.addDictionary({
 "2001xx07":"Image Type End Diastole or End Systole",
 "2001xx08":"Phase Number",
 "2001xx09":"Image Prepulse Delay",
-"2001xx0A":"Image Plane Number",
-"2001xx0B":"Image Orientation",
+"2001xx0A":"Slice Number",
+"2001xx0B":"Slice Orientation",
 "2001xx0C":"Arrhythmia Rejection",
 "2001xx0E":"Cardiac Cycled",
 "2001xx0F":"Cardiac Gate Width",
...

It makes me confusing and don't know how to merge these files if necessary.

**Desktop (please complete the following information):**
 - OS: macOS

Related dcm4che/dcm4che#725, dcm4che/dcm4che#755

**Comment by vrindanayak** [comment]
It is intended that there shall be 2 files each for Philips Imaging DD 001 and Philips MR Imaging DD 001, as the template file for private dictionary of Philips Data Elements (provided by David Clunie in dicom3tools) consists of duplicate naming with case differences for Owner Groups and there are certain differences in the private tags for each of these 2 apparently similar Owner Groups : See [Element Dictionary for private Philips Data Elements](https://github.com/dcm4che/dcm4che/issues/725). 

````
diff dcm4chee-arc-ui2/src/app/constants/PHILIPS-IMAGING-DD-001-1.js dcm4chee-arc-ui2/src/app/constants/Philips-Imaging-DD-001.js
2c2
< "privateCreator":"PHILIPS IMAGING DD 001",
---
> "privateCreator":"Philips Imaging DD 001",
12,13c12,13
< "2001xx0A":"Image Plane Number",
< "2001xx0B":"Image Orientation",
---
> "2001xx0A":"Slice Number",
> "2001xx0B":"Slice Orientation",
````
and 
````
 diff dcm4chee-arc-ui2/src/app/constants/PHILIPS-MR-IMAGING-DD-001-1.js dcm4chee-arc-ui2/src/app/constants/Philips-MR-Imaging-DD-001.js
2c2
< "privateCreator":"PHILIPS MR IMAGING DD 001",
---
> "privateCreator":"Philips MR Imaging DD 001",
5a6
> "2005xx03":"Image Annotation Count",
7a9
> "2005xx07":"Image Line Count",
32c34
< "2005xx20":"Number of Chemical Shift",
---
> "2005xx20":"Number of Chemical Shifts",
62a65,72
> "2005xx40":"PlanScan Survey Chemical Shift Number",
> "2005xx41":"PlanScan Survey Dynamic Scan Number",
> "2005xx42":"PlanScan Survey Echo Number",
> "2005xx43":"PlanScan Survey Image Type",
> "2005xx44":"PlanScan Survey Phase Number",
> "2005xx45":"PlanScan Survey Reconstruction Number",
> "2005xx46":"PlanScan Survey Scanning Sequence",
> "2005xx47":"PlanScan Survey Slice Number",
119a130,152
> "2005xx87":"Number of Geometry Slices",
> "2005xx88":"Geom Angulation AP",
> "2005xx89":"Geom Angulation FH",
> "2005xx8A":"Geom Angulation RL",
> "2005xx8B":"Geom FOV AP",
> "2005xx8C":"Geom FOV FH",
> "2005xx8D":"Geom FOV RL",
> "2005xx8E":"Geom OffCentre AP",
> "2005xx8F":"Geom OffCentre FH",
> "2005xx90":"Geom OffCentre RL",
> "2005xx91":"Geom Preparation Direct",
> "2005xx92":"Geom Radial Angle",
> "2005xx93":"Geom Radial Axis",
> "2005xx94":"Geom Slice Distance",
> "2005xx95":"Geom Slice Number",
> "2005xx96":"Geom Type",
> "2005xx97":"Geom ViewA xis",
> "2005xx98":"Geom Colour",
> "2005xx99":"Geom Application Type",
> "2005xx9A":"Geom Id",
> "2005xx9B":"Geom Application Name",
> "2005xx9C":"Geom Label Name",
> "2005xx9D":"Geom Line Style",
121c154
< "2005xx9F":"Spectral Selective Excitation Pulse",
---
> "2005xx9F":"SeriesSpectral Selective Excitation Pulse",
````

To avoid a [similar issue reported by a Windows user](https://github.com/dcm4che/dcm4che/issues/755), the workaround was to append a `-1` for each of one of these 2 Owner Groups i.e. change `PHILIPS-IMAGING-DD-001` to `PHILIPS-IMAGING-DD-001-1` and `PHILIPS-MR-IMAGING-DD-001` to `PHILIPS-MR-IMAGING-DD-001-1` in the corresponding respective xml and js files for these private dictionaries. The removal of stale `PHILIPS-IMAGING-DD-001.js` and `PHILIPS-MR-IMAGING-DD-001.js` files was missed as part of the commits for that issue. I've deleted those two stale files now.
