### ISSUE TITLE
Download of study via the UI leads to java.util.zip.ZipException: duplicate entry: DICOM/

### ISSUE THREAD

**Issue by Christian-e-S** [dcm4che/dcm4chee-arc-light#3101]
When I try to download a study via the UI, I receive only a corrupt zip file and the error "java.util.zip.ZipException: duplicate entry: DICOM/" is logged. Downloading single DICOM files (which are not zipped) works perfectly.

Has anybody any clue what the problem could be?

Please find the context and the detailed steps to reproduce this error below.

Best,
Christian

![image](https://user-images.githubusercontent.com/59229557/112197134-07020080-8c0c-11eb-96f9-b3de6967f718.png)

Context:
 
* I am using the docker image "dcm4che/dcm4chee-arc-psql:5.23.1-secure" on an Azure AKS Kubernetes Cluster.
* I have populated an initial dataset via "docker run --rm  dcm4che/dcm4che-tools storescu -cDCM4CHEE@MyIP:11112 /opt/dcm4che/etc/testdata/dicom"
* Downloading a single DICOM file works (which is not zipped)
* When I try to download the study, I get a corrupt zip file
* The logs show "java.util.zip.ZipException: duplicate entry: DICOM/"

I have attached a text file with the complete stack trace.
[dcm4chee-arc-stacktrace.txt](https://github.com/dcm4che/dcm4chee-arc-light/files/6191924/dcm4chee-arc-stacktrace.txt)

**Comment by gunterze** [comment]
What's your configured [**Wado ZIP Entry Name Format**](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveDevice.html#dcmwadozipentrynameformat)?
![Screenshot from 2021-03-24 12-49-08](https://user-images.githubusercontent.com/400095/112305755-5f361280-8c9f-11eb-8c95-c1ac664e72ba.png)

**Comment by Christian-e-S** [comment]
I did not change anything in the default configuration. 
The current value is DICOM/{0020000D,hash}/{0020000E,hash}/{00080018,hash}.dcm

**Comment by gunterze** [comment]
Introduced by #3061

**Comment by Christian-e-S** [comment]
Perfect ... Thank you very much! 

Do you have any estimate when there will be a dcm4che/dcm4chee-arc-psql image with this fix available?

**Comment by gunterze** [comment]
Today :)

**Comment by Christian-e-S** [comment]
Great !!!!

**Comment by gunterze** [comment]
pushed docker image `dcm4che/dcm4chee-arc-psql:5.23.2-secure`, but also replaced affected `dcm4che/dcm4chee-arc-psql:5.23.1-secure, so you don't need to upgrade to 5.23.2 to prevent that issue. (Don't forget to purge mapped out `wildfly/standalone/deployment` and `wildfly/standalone/configuration` before recreating the archive container from new docker image).

**Comment by Christian-e-S** [comment]
Excellent ... I have tested it and everything works. ... Thank you!!

**Comment by yuqian-liu** [comment]
Hi, I am using docker.io/dcm4che/dcm4chee-arc-psql:5.31.0-secure and have this problem, may I ask what should I update to resolve? Thank you.
