### ISSUE TITLE
Document using Amazon-S3 as Storage System

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3131]
Document using Amazon-S3 as Storage System at [S3-Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/S3-Storage)

s.o. https://jclouds.apache.org/guides/aws/
https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html

**Comment by vrindanayak** [comment]
[Amazon S3 Storage](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Amazon-S3-Storage)
