### ISSUE TITLE
Archive Docker image: Provide ENVs for HTTPS/SSL with a Reverse Proxy

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3140]
Provide ENVs for HTTPS/SSL with a Reverse Proxy:

#### `HTTP_PROXY_ADDRESS_FORWARDING`

If this is enabled then the X-Forwarded-For and X-Forwarded-Proto headers will be used to determine the peer address.
This allows applications that are behind a proxy to see the real address of the client, rather than the address
of the proxy.  (optional, default is `false`).

#### `REDIRECT_HTTPS_PORT`

HTTPS port to redirect requests that require security too. (optional, default is `8443`).
Have to be set different to `HTTPS_PORT`, if running behind a HTTPS/SSL reverse proxy listing on a different port.

**Comment by petrkalina** [comment]
Only effective for http listener, not https currently!

**Comment by petrkalina** [comment]
seems HTTP_PROXY_ADDRESS_FORWARDING=true renders WILDFLY_RESOLVE_PEER_ADDRESS=true ineffective

**Comment by gunterze** [comment]
https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/commit/4f763a779a47c74930ad7079c01f06e047228865
https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/commit/1c7bd861406ecf3fb26b5f69731c29b4ddef3000
https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql/commit/dab0933568908c4c048e24c231318541a1eae6c1
