### ISSUE TITLE
Keycloak Docker image: Provide ENVs for HTTPS/SSL with a Reverse Proxy

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3141]
Provide ENVs for HTTPS/SSL with a Reverse Proxy:

#### `HTTP_PROXY_ADDRESS_FORWARDING`

If this is enabled then the X-Forwarded-For and X-Forwarded-Proto headers will be used to determine the peer address.
This allows applications that are behind a proxy to see the real address of the client, rather than the address
of the proxy.  (optional, default is `false`).

#### `REDIRECT_HTTPS_PORT`

HTTPS port to redirect requests that require security too. (optional, default is `8443`).
Have to be set different to `HTTPS_PORT`, if running behind a HTTPS/SSL reverse proxy listing on a different port.

Related #3140

**Comment by petrkalina** [comment]
seems HTTP_PROXY_ADDRESS_FORWARDING=true renders WILDFLY_RESOLVE_PEER_ADDRESS=true ineffective. Surprisingly, it becomes effective with adding a logging filter i.e. vua jboss-cli script:

```
batch
/subsystem=undertow/configuration=filter/custom-filter=request-logging-filter:add(class-name=io.undertow.server.handlers.RequestDumpingHandler, module=io.undertow.core)
/subsystem=undertow/server=default-server/host=default-host/filter-ref=request-logging-filter:add
run-batch
```

(only tested on archive wildfly, but likely applies on keycloak as well as this seems wildfly image issue)
