### ISSUE TITLE
S3 as storage: Working example

### ISSUE THREAD

**Issue by proteeti13** [dcm4che/dcm4chee-arc-light#3148]
Hello! I am trying to integrate S3 bucket as storage in my dcm4chee. I am now using the version 5.23.2 of dcm4chee.
### I did the following steps:

1. Installed dcm4chee from [here](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host). Got it running at http://localhost:8080/dcm4chee-arc/ui2.
2. Created an s3 bucket, made it public
3. In the dcm4chee ui, did these[ from here](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Generic-Storage)
- Went to Menu --> Configuration --> dcm4chee-arc --> Extensions --> Edit Extensions --> Edit Extensions of Archive Device --> Deleted [X] fs1 from the Storage Descriptor list --> Save
 - Went to Menu --> Configuration --> dcm4chee-arc --> Extensions --> Edit Extensions --> Edit Extensions of Archive Device --> Add new Storage Descriptor
 - Added the following attributes:
    Storage ID:   proteeti1
    Storage URI : jclouds:s3:<bucket-url>
    Digest Algorithm: MD5
- In storage Property added the following [from here](https://github.com/dcm4che/dcm4chee-arc-light/wiki/S3-Storage)
    identity=<access-key>
    credential=<secret-key>
    container=<bucket-name>
    containerExists=true
    jclouds.trust-all-certs=true
    jclouds.relax-hostname=true
    jclouds.s3.virtual-host-buckets=true
    jclouds.strip-expect-header=true
* Associate the new Storage with the Archive Application Entity:
    Configuration --> dcm4chee-arc --> Child Objects -> Network AEs -> DCM4CHEE -> Network AE Extension --> Archive Network AE -> Attributes -> Object Storage ID
* Send CT images to the Archive with `docker run --rm --network=dcm4chee_default dcm4che/dcm4che-tools storescu -cDCM4CHEE@arc:11112 /opt/dcm4che/etc/testdata/dicom`

### **Result:**
```
E"ERROR: Received C-STORE-RSP with Status 0110H for /opt/dcm4che/etc/testdata/dicom/MR15.dcm"
(0000,0100) US [32769] CommandField
(0000,0120) US [15] MessageIDBeingRespondedTo
(0000,0800) US [257] CommandDataSetType
(0000,0900) US [272] Status
(0000,0902) LO [java.io.IOException: Upload failed] ErrorComment

09:42:39,163 INFO  - STORESCU->DCM4CHEE(1) >> 16:C-STORE-RSP[pcid=5, status=110H, errorComment=java.io.IOException: Upload failed
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian]
09:42:39,164 DEBUG - STORESCU->DCM4CHEE(1) >> 16:C-STORE-RSP Command:
(0000,0100) US [32769] CommandField
(0000,0120) US [16] MessageIDBeingRespondedTo
(0000,0800) US [257] CommandDataSetType
(0000,0900) US [272] Status
(0000,0902) LO [java.io.IOException: Upload failed] ErrorComment

E"ERROR: Received C-STORE-RSP with Status 0110H for /opt/dcm4che/etc/testdata/dicom/MR03.dcm"
(0000,0100) US [32769] CommandField
(0000,0120) US [16] MessageIDBeingRespondedTo
(0000,0800) US [257] CommandDataSetType
(0000,0900) US [272] Status
(0000,0902) LO [java.io.IOException: Upload failed] ErrorComment

09:42:39,166 INFO  - STORESCU->DCM4CHEE(1) << A-RELEASE-RQ
09:42:39,166 DEBUG - STORESCU->DCM4CHEE(1): enter state: Sta7 - Awaiting A-RELEASE-RP PDU
09:42:39,167 INFO  - STORESCU->DCM4CHEE(1) >> A-RELEASE-RP
09:42:39,167 INFO  - STORESCU->DCM4CHEE(1): close Socket[addr=arc/172.19.0.4,port=11112,localport=52241]
09:42:39,169 DEBUG - STORESCU->DCM4CHEE(1): enter state: Sta1 - Idle
Sent 0 objects (=0MB) in 6.235s (=0MB/s)
```

**Comment by vrindanayak** [comment]
Discussion for the same exists - https://github.com/dcm4che/dcm4chee-arc-light/discussions/3146
