### ISSUE TITLE
Extend Link Instances with MWL service also for external MWL SCPs

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#3158]
Rationale : [MWL-RS is extended to query also external MWL SCPs](https://github.com/dcm4che/dcm4chee-arc-light/issues/3135) which are queried over DICOM proxy; these web applications currently have only `MWL_RS` as web service class and do not contain `DCM4CHEE_ARC_AET` web service class which is used by [Link Instances with MWL](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/IOCM-RS/LinkInstancesWithMWLEntry) service. 
As user may choose these web applications to also link instances with MWL, it currently results in invocation of following service  which does not exist
````
POST /dcm4chee-arc/aets/DCM4CHEE/dimse/EXT_AET/mwlitems/{StudyUID}/{SPSID}/move/113038%5EDCM
````

**Comment by gunterze** [comment]
Should fail with HTTP status: 409 Conflict, if multiple MWL items are returned for given Study Instance UID and Scheduled Procedure Step ID from external MWL SCP
