### ISSUE TITLE
UI Configuration: Cloning a device shall also take care of cloning associated vendor data

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3228]
Cloning a device shall also take care of cloning associated vendor data, by
- download the vendor data of the Source Device by [`GET /dcm4chee-arc​/devices​/{source-device}​/vendordata`](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/CONFIG-RS/getDeviceVendorData)
- upload the vendor data to the new Device by [`PUT ​/dcm4chee-arc/devices​/{new-device}​/vendordata`](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/CONFIG-RS/updateDeviceVendorData)

**Comment by vrindanayak** [comment]
`application/zip` not sent as `Content-type` in [`PUT ​/dcm4chee-arc/devices​/{new-device}​/vendordata`](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/CONFIG-RS/updateDeviceVendorData) request causing `415 - Unsupported Media Type` error
