### ISSUE TITLE
UI Configuration - Devices : Deleting a device fails with 409-Conflict - javax.naming.directory.InvalidSearchFilterException

### ISSUE THREAD

**Issue by afurkan** [dcm4che/dcm4chee-arc-light#3322]
**Describe the bug**
An error occurs while deleting device from devices tab on UI.

> Message : {"errorMessage":"javax.naming.directory.InvalidSearchFilterException: Unbalanced parenthesis; remaining name 'dicomDeviceName=oldarchive,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org'"}

**To Reproduce**
1. Create or clone devices
2. try to delete newly created/cloned device
3. See error

**Expected behavior**
remove device from system.

**Information**
 - OS: Debian 10
 - Browser : firefox/chrome
 - Version : 5.24.0 (Docker with minimum req. ldap,keycloak,archive and external PostgreSQL)

**Comment by vrindanayak** [comment]
Shall be solved by https://github.com/dcm4che/dcm4che/issues/1018
