### ISSUE TITLE
UI: Allow download of study/series as ZIP

### ISSUE THREAD

**Issue by moloney** [dcm4che/dcm4chee-arc-light#340]
It would be nice to have this functionality which existed in dcm4chee 2.X. Currently we can only download individual DICOM objects.

Requires  #1460, #1461

Provide two controls for each Study/Series entry, to download all instances of the Study/Series either uncompressed or as stored at the archive, by 

- [GET
/dcm4chee-arc/aets/{aet}/rs/studies/{StudyInstanceUID}?accept=application/zip](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger-dicom.json#/WADO-RS/RetrieveStudy) - Retrieve Study uncompressed
- [GET
/dcm4chee-arc/aets/{aet}/rs/studies/{StudyInstanceUID}?accept=application/zip;transfer-syntax=*](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger-dicom.json#/WADO-RS/RetrieveStudy) - Retrieve Study as stored at the archive
- [GET
/dcm4chee-arc/aets/{aet}/rs/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}?accept=application/zip](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger-dicom.json#/WADO-RS/RetrieveSeries) - Retrieve Series uncompressed
- [GET
/dcm4chee-arc/aets/{aet}/rs/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}?accept=application/zip;transfer-syntax=*](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger-dicom.json#/WADO-RS/RetrieveSeries) - Retrieve Series as stored at the archive

**Comment by bohsen** [comment]
This was added in the latest release, but I can't find the new buttons anywhere. Is it something that you have to enable anywhere?

I'm using Docker Compose for running my server and just updated the docker-compose.yaml file with the new version tags.
