### ISSUE TITLE
UI Navigation: Failed to load Encapsulated PDF imported by STOW  

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3409]
Failed to load Encapsulated PDF imported by STOW.

WADO-URI request, e.g.:
```
GET /dcm4chee-arc/aets/DCM4CHEE/wado?requestType=WADO&studyUID=2.25.21247174983562121574725994726958549190&seriesUID=2.25.240940521870579691600897781420927250961&objectUID=2.25.247761500128235951110999618543330805801&contentType=application/pdf
```

does not get invoked!

**Comment by vrindanayak** [comment]
No longer reproducible

![image](https://user-images.githubusercontent.com/15785031/185627658-f748712f-0338-474d-b634-e26ca128bf32.png)

![image](https://user-images.githubusercontent.com/15785031/185627923-1554f3b0-feca-4e18-9545-d53c70663415.png)

Perhaps the pop-up blocker was set on `Block`
