### ISSUE TITLE
UI: Navigation/Patients/add MWL: populate Accession Number from configurable ID Generator

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3420]
If no Accession Number is provided and selected Web Application has property
```
MWLAccessionNumberGenerator={name}
```
configured, pass the ID returned by `POST /dcm4chee-arc/ids/{name}/nextval` as Accession Number in the payload of [`POST
/dcm4chee-arc/aets/{aet}/rs/mwlitems`](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/MWL-RS/CreateUpdateSPS).

Requires #3418

**Comment by vrindanayak** [comment]
Verified fix

![image](https://user-images.githubusercontent.com/15785031/141968565-8ad4a2b3-f185-401c-aa6f-e03c7a769f93.png)

Requires new UI Configuration `dcmuiCreateDialogTemplate`
````
dn: dcmuiTemplateName=MWL default,dcmuiConfigName=default,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
objectClass: top
objectClass: dcmuiCreateDialogTemplate
dcmTemplateTag: 00401001
dcmTemplateTag: 00080050
dcmTemplateTag: 00400009
dcmTemplateTag: 0020000D
dcmTemplateTag: 00400001
dcmuiTemplateName: MWL default
````
