### ISSUE TITLE
Test generalized Attribute Coercions

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3473]
Related  #2967

#### Test different attribute coercions on receiving/sending datasets individually 

❏ | DIMSE | Role | SOP Class | URI scheme | Parameters 
-- | -- | -- | -- | -- | --
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `xslt:` | Other Coercion Parameter : <br>`xsl-no-keyword = true`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-attrs:` | DICOM Attribute Coercion Parameter : <br>`PatientID={PatientID,slice,3}`<br>`IssuerOfPatientID=Red`<br>`IssuerOfPatientIDQualifiersSequence.UniversalEntityID=1.2.3.4.5`<br>`IssuerOfPatientIDQualifiersSequence.UniversalEntityIDType=ISO`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-mwl:` | Other Coercion Parameter : <br>`match-by=StudyInstanceUID`<br>`local-mwl-scp=DCM4CHEE`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-mwl:<path-to-merge-mwl.xsl>` | Other Coercion Parameter : <br>`match-by=AccessionNumber`<br>`local-mwl-scp=DCM4CHEE`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-mwl:` | Other Coercion Parameter : <br>`match-by=PatientID`<br>`mwl-scp=<external-mwl-scp-aet>`<br>`filter-by-scu=true`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `sup-from-dev:` | Device Name Coercion Parameter : `storescu`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `trim-ISO2022:` | 
✅ | `C_STORE_RQ`  | `SCU` | Storage | `use-calling-aet-as:SendingApplicationEntityTitleOfSeries` | 
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-attrs:` | (Legacy) Nullify Attributes <br>DICOM Attribute Coercion Parameter : `AccessionNumber=`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-attrs:` | (Legacy) ALWAYS Nullify Issuer of Patient ID <br>DICOM Attribute Coercion Parameter : `IssuerOfPatientID=`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-attrs:` | (Legacy) Nullify Issuer of Patient ID for MATCHING Issuer of Patient ID <br>DICOM Attribute Coercion Parameter : `IssuerOfPatientID=` <br>Condition : `IssuerOfPatientID=JMS`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-attrs:` | (Legacy) Nullify Issuer of Patient ID  for NOT_MATCHING Issuer of Patient ID <br>DICOM Attribute Coercion Parameter : `IssuerOfPatientID=` <br>Condition : `IssuerOfPatientID!=JMS`
✅ | `C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-attrs:` | (Legacy) Issuer of Patient ID Format <br>DICOM Attribute Coercion Parameter : `IssuerOfPatientID={00100010,hash}-{00100030}`
❏ |✅ `C_STORE_RQ` (WADO)  | `SCP` | Storage | `xslt:` |  Other Coercion Parameter : <br>`xsl-no-keyword = true`
| |❏ `XDS-I RAD-69`  |  |  |  | |
❏ |✅ `C_STORE_RQ` (WADO) | `SCP` | Storage | `merge-attrs:` | DICOM Attribute Coercion Parameter : <br>`PatientID=JMS{PatientID}`<br>`IssuerOfPatientID=`
| |❏  `XDS-I RAD-69`  |  |  |  | |
❏ |✅ `C_STORE_RQ` (WADO) | `SCP` | Storage | `leading-arc:<LEADING_ARC_AET>` |  
| |❏  `XDS-I RAD-69`  |  |  |  | |
❏ |✅ `C_STORE_RQ` (WADO) | `SCP` | Storage | `retrieve-as-received:` |  
| |❏ `XDS-I RAD-69`  |  |  |  | |
❏ |✅ `C_STORE_RQ` | `SCP` | Storage | `nullify-pixel-data:` |  
| |❏ `WADO`  |  |  |  | |
| |❏ `XDS-I RAD-69`  |  |  |  | |
❏ |✅ `C_STORE_RQ` (WADO) | `SCP` | Storage | `deidentify:` |  
| |❏ `XDS-I RAD-69`  |  |  |  | |
✅ | `C_FIND_RQ`<br>(QIDO)  | `SCU` | Comp. Query | `sup-from-dev:` | Device Name Coercion Parameter : `findscu`
✅ | `C_FIND_RSP`<br>(QIDO)  | `SCU` | Comp. Query  | `leading-arc:<LEADING_ARC_AET>`
✅ | `C_FIND_RQ`  | `SCU` | Comp. Query <br>MWL | `merge-attrs:` | DICOM Attribute Coercion Parameter : <br>`PatientID={PatientID,slice,3}`
✅ | `C_FIND_RQ`  | `SCU` | MWL Query | `use-calling-aet-as:ScheduledStationAETitle` | 
✅ | `C_FIND_RSP`  | `SCU` | Comp. Query <br>MWL  | `merge-attrs:` | DICOM Attribute Coercion Parameter : <br>`PatientID=JMS{PatientID}`
✅ | `C_FIND_RQ`  | `SCP` | Comp. Query <br>MWL  | `merge-attrs:` | DICOM Attribute Coercion Parameter : <br>`PatientID=JMS{PatientID}`
✅ | `C_FIND_RSP`  | `SCP` | Comp. Query <br>MWL  | `merge-attrs:` | DICOM Attribute Coercion Parameter : <br>`PatientID={PatientID,slice,3}`
✅ | `N_CREATE_RQ`  | `SCU` | MPPS | `sup-from-dev:` | Device Name Coercion Parameter : `mppsscu`

#### Test different attribute coercions on receiving/sending datasets in combination, in dependence of  Archive Attribute Coercion attributes

Name | Type | Description (LDAP Attribute)
-- | -- | --
Attribute Coercion Sufficient | Boolean | Do not apply other matching Attribute Coercions of lesser priority,  if this Attribute Coercion was applied effectively.  (dcmCoercionSufficient)
Attribute Coercion on Failure | String | Behavior on failure applying this Attribute Coercion. RETHROW (=  propagate failure to operation applying this Attribute Coercion),  CONTINUE (= continue to apply other matching Attribute Coercions of  lesser priority) or SUFFICIENT (= do not apply other matching Attribute  Coercions of lesser priority). (dcmCoercionOnFailure)
Attribute Coercion Priority | Integer | Rule Priority. (dcmRulePriority)

E.g.:

DIMSE | Role | SOP Class | URI scheme | Parameters
-- | -- | -- | -- | --
`C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-mwl:` | `match-by = PatientID`
`C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-attrs:` | `PatientID=`

with

❏ | Priority (merge-mwl:) | Priority (merge-attrs:) | Sufficient (merge-mwl: ) | on Failure  (merge-mwl: )
-- | -- | -- | -- | --
✅ | 2 | 1 | `true` | `RETHROW`
✅ | 2 | 1 | `false` | `RETHROW`
✅ | 2 | 1 | `false` | `CONTINUE`
✅ | 2 | 1 | `false` | `SUFFICIENT`
✅ | 1 | 2 | `false` | `RETHROW`

#### Ensure higher priority coercion is not overridden by lower priority coercion

DIMSE | Role | SOP Class | URI scheme | Parameters
-- | -- | -- | -- | --
`C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-mwl:` | `match-by = PatientID`
`C_STORE_RQ` (STOW)  | `SCU` | Storage | `merge-attrs:` | `PatientID=`

with

❏ | Priority (merge-mwl:) | Priority (merge-attrs:) | Sufficient (merge-mwl: ) | on Failure  (merge-mwl: )
-- | -- | -- | -- | --
❏ | 2 | 1 | `false` | `RETHROW`
❏ | 1 | 2 | `false` | `RETHROW`

**Comment by vrindanayak** [comment]
Remaining open points will be retested on closure of #3810 / #3830
