### ISSUE TITLE
Wiki: how to use utility stowrs to measure STOW-RS upload performance

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3480]
how to use utility `stowrs` to measure STOW-RS upload performance (MB/s) in dependence of
- number of objects per request (1,2,3,...)
- request size (object size * number of objects)
- modality wise (MR, CT, CR, DX)
- number of parallel TCP connections (1,2,3,...)

Requires https://github.com/dcm4che/dcm4che/issues/1063

**Comment by vrindanayak** [comment]
[STOW RS Upload Performance Measurements](https://github.com/dcm4che/dcm4chee-arc-light/wiki/STOW-RS-Upload-Performance-Measurements)
