### ISSUE TITLE
RESTful Service to List Registered Application Entity Titles

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#349]
[List Registered Application Entity Titles](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#!/CONFIG-RS/listRegisteredAETs)

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4che/commit/0217c45726ecd87bea49fc718b4c1f5d05b258e0
