### ISSUE TITLE
dcm-arc 5.25 erro: cannot into the web when I changed the language

### ISSUE THREAD

**Issue by fanxting** [dcm4che/dcm4chee-arc-light#3504]
**Describe the bug**
When I change the language, the web keep freshing 

**To Reproduce**
1. switch the language
![image](https://user-images.githubusercontent.com/15911131/147333524-c16a29ec-fd50-44e4-bcc7-40950642b1ce.png)

2. Then I can't open the main page
![image](https://user-images.githubusercontent.com/15911131/147333604-7cd62477-0edc-421f-990e-abf0fcba89be.png)

**Comment by kocmoc1** [comment]
I have the same screen on fresh installed dcm4chee-arc

**Comment by qiangkeming** [comment]
hi teacher:
      i want to kown what's angularJs and nodejs version in dcm4chee-arc-light 5.25.1 , tks a lot!

**Comment by shral** [comment]
I don't know if the problem is still remaining in 5.28, but what I found is that in zh.json there are some square bracket ( [, ]) which are not allowed in language json. I replaced square brackets through round brackets and is working again.
