### ISSUE TITLE
RESTful service to get server time zone

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3519]
RESTful service to get server time zone:

**Request:**
`GET /dcm4chee-arc/monitor/serverTimeZone`

**Response:**
`Content-Type: application/json`
```json
{
   "timeZone": "Europe/Vienna",
   "offset": 3600000
}
```
returning values of
-  [`java.util.TimeZone.getDefault().getID()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/TimeZone.html#getID()) 
-  [`java.util.TimeZone.getDefault().getOffset(System.currentTimeMillis())`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/TimeZone.html#getOffset(long))

.
 
_Rationale_:
Used by UI to (optionally) display timestamps in server time zone.

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/a9bd7f5fc4bfd6bb7a38c5f9f5e3b39275743ab0
