### ISSUE TITLE
On using webapp / AE specific to IOCM Q/R views rejected studies count differs with displayed rejected studies

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#3574]
![image](https://user-images.githubusercontent.com/15785031/155689002-34b2adc2-90da-46d2-aa81-8018b4c1e2c7.png)

![image](https://user-images.githubusercontent.com/15785031/155690552-db64b2ea-d620-419f-8e92-a3b32a926721.png)

Rationale : It is confusing for the user, and he has to select each IOCM web app view and keep navigating till the end to determine the rejected studies count for each of the IOCM reasons

Recommended : 
- Either the count and displayed results should match (server side changes) 
- Or the Count button should be removed for these IOCM views (UI changes)
- Or any other enhancement to bypass this behavior and which is not misleading(?)

**Comment by gunterze** [comment]
Caused by https://github.com/dcm4che/dcm4chee-arc-light/issues/3615
