### ISSUE TITLE
UPS on Store/HL7/UPS Completed: Mulitple Scheduled Station (Name/Class/Geographic Location) Codes and Scheduled Human Performer Codes

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3576]
Support to configure **multiple** values for

Name | Type | Description (LDAP Attribute)
-- | -- | --
Scheduled Station Name Code(s) | string | Item of Scheduled Station Name Code Sequence (0040,4025) in created UPS in format (CV, CSD, “CM”). (dcmUPSScheduledStationNameCode)
Scheduled Station Class Code(s) | string | Item of Scheduled Station Class Code Sequence (0040,4026) in created UPS in format (CV, CSD, “CM”). (dcmUPSScheduledStationClassCode)
Scheduled Station Geographic Location Code(s) | string | Item of Scheduled Station Geographic Location Code Sequence (0040,4027) in created UPS in format (CV, CSD, “CM”). (dcmUPSScheduledStationLocationCode)
Scheduled Human Performer Code(s) | string | Item of Human Performer Code Sequence (0040,4009) in Item of  Scheduled Human Performers Sequence (0040,4034) in created UPS in format  (CV, CSD, “CM”). (dcmUPSScheduledHumanPerformerCode)

of [UPS on Store](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/upsOnStore.html), [UPS on HL7](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/upsOnHL7.html) and [UPS on UPS Completed](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/upsOnUPSCompleted.html).

Related  #3567

**Comment by vrindanayak** [comment]
Multi-valued  
- Scheduled Station Name Code(s)
- Scheduled Station Class Code(s)
- Scheduled Station Geographic Location Code(s)
- Scheduled Human Performer Code(s)

supported for [UPSOnStore](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/upsOnStore.html), [UPSOnHL7](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/upsOnHL7.html) and [UPSOnUPSCompleted](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/upsOnUPSCompleted.html) rules.

Known limitation : It is currently not possible to support multiple `Scheduled Human Performer Code(s)` together with multiple `Scheduled Human Performer Name(s)` / `Scheduled Human Performer Organizations(s)` in a `Scheduled Human Performers Sequence`. The intended use cases supported by archive for this sequence are to : 
- Either configure multiple `Scheduled Human Performer Code(s)` : To identify multiple human performers working on a single UPS 
- Or configure the rules to have a single `Scheduled Human Performer Name` : To identify a single human performer working on a single UPS
