### ISSUE TITLE
Support OpenLDAP N-Way Multi-Master replication by docker image dcm4che/slapd

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#361]
s.  [OpenLDAP Software 2.4 Administrator's Guide, N-Way Multi-Master replication](http://www.openldap.org/doc/admin24/replication.html#N-Way%20Multi-Master%20replication)

Environment Variable *LDAP_REPLICATION_HOSTS* specifies URLlist of all LDAP server which must contain the own container host name. Other host names of other servers must be resolvable by the container. E.g.:
```
docker run --name=ldap1 -p 389:389 -e LDAP_REPLICATION_HOSTS="ldap://ldap1/ ldap://ldap2/" --hostname=ldap1 --add-host=ldap2:<ip-of-ldap2> -d dcm4che/slapd-dcm4chee
```

After startup you have to invoke
```
docker exec <ldap-container-name> prepare-replication
```
on each container, before actual activating the replication by
```
docker exec <ldap-container-name> enable-replication
```
on each container. There is als a script available for deactiving the replication by
```
docker exec <ldap-container-name> disable-replication
```
You may change the default parameters for the replication by Environment Variable
```
LDAP_REPLICATION_DB_SYNCPROV='binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ROOTPASS searchbase="$LDAP_BASE_DN" type=refreshOnly interval=00:00:00:10 retry="5 5 300 +" timeout=1'
```

**Comment by petrkalina** [comment]
example setting up 

docker-compose service definitions

server 1 :

<pre>
  ldap:
    image: docker.j4care.com/slapd-dcm4chee:2.4.40-7.1.Final
    container_name: ldap
    hostname: ldap1
    restart: unless-stopped
    ports:
      - "389:389"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /tmp/data/ldap/ldap:/var/lib/ldap
      - /tmp/data/ldap/slapd.d:/etc/ldap/slapd.d
      - /tmp/data/ldap/import:/etc/ldap/import
    extra_hosts:
      - ldap2:192.168.100.253
    environment:
      LDAP_REPLICATION_HOSTS: "ldap://ldap1/ ldap://ldap2/"
      LDAP_BASE_DN: dc=dcm4che,dc=org
      LDAP_ROOTPASS: ssaptoor
      LDAP_CONFIGPASS: ssaptoor
      SKIP_INIT_CONFIG: "true"
      IMPORT_LDIF: /etc/ldap/import/config.ldif
</pre>

server 2:

<pre>
  ldap:
    image: docker.j4care.com/slapd-dcm4chee:2.4.40-7.1.Final
    container_name: ldap
    hostname: ldap2
    restart: unless-stopped
    ports:
      - "389:389"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /tmp/data/ldap/ldap:/var/lib/ldap
      - /tmp/data/ldap/slapd.d:/etc/ldap/slapd.d
      - /tmp/data/ldap/import:/etc/ldap/import
    extra_hosts:
      - ldap1:192.168.100.245
    environment:
      LDAP_REPLICATION_HOSTS: "ldap://ldap1/ ldap://ldap2/"
      LDAP_BASE_DN: dc=dcm4che,dc=org
      LDAP_ROOTPASS: ssaptoor
      LDAP_CONFIGPASS: ssaptoor
      SKIP_INIT_CONFIG: "true"
      IMPORT_LDIF: /etc/ldap/import/config.ldif
</pre>

start the services and set-up replication

<pre>
server1#: docker-compose up -d ldap
server1#: docker exec ldap prepare-replication
</pre>
<pre>
server2#: docker-compose up -d ldap
server2#: docker exec ldap prepare-replication
</pre>
<pre>
server1#: docker exec ldap enable-replication
server2#: docker exec ldap enable-replication
</pre>

verify the config:

<pre>
server1# docker exec ldap1 sh -c 'ldapsearch -xw $LDAP_CONFIGPASS -D cn=admin,cn=config -b olcDatabase={1}hdb,cn=config'
</pre>

<pre>
..
olcSyncrepl: {0}rid=101 provider=ldap://ldap1/ binddn="cn=admin,dc=dcm4che,dc=
 org" bindmethod=simple credentials=ssaptoor searchbase="dc=dcm4che,dc=org" ty
 pe=refreshOnly interval=00:00:00:10 retry="5 5 300 +" timeout=1
olcSyncrepl: {1}rid=102 provider=ldap://ldap2/ binddn="cn=admin,dc=dcm4che,dc=
 org" bindmethod=simple credentials=ssaptoor searchbase="dc=dcm4che,dc=org" ty
 pe=refreshOnly interval=00:00:00:10 retry="5 5 300 +" timeout=1
olcMirrorMode: TRUE
...
</pre>

you can test the replication now. you can also make sure the replication works even after restart of the services:

<pre>
server1#: docker-compose restart ldap
server2#: docker-compose restart ldap
</pre>

test again
