### ISSUE TITLE
Running on Docker (docker-compose) reports 404 on Archive UI

### ISSUE THREAD

**Issue by michaelonken** [dcm4che/dcm4chee-arc-light#363]
Following the [docker running description](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Running-on-Docker) using the docker-compose approach, Docker pulls and runs the containers without any errors.

However, I get a 404 in the browser when accessing http://localhost:8080/dcm4chee-arc/ui . The Wildfly interface, for example, seems to be functional though. Also, the DICOM server is reachable on port 11112.

I tried within a Debian 8 Virtual Machine as well on a current Ubuntu 16.04 (no VM) system, both 64 bit.

Any ideas? Thanks!
Michael

**Comment by gunterze** [comment]
Check Wildfly server.log for
```
2016-09-16 10:33:15,087 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 78) WFLYUT0021: Registered web context: /dcm4chee-arc
2016-09-16 10:33:15,089 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 72) WFLYUT0021: Registered web context: /dcm4chee-arc/ui
```

**Comment by michaelonken** [comment]
Thank you for looking into this. I cannot find that lines but in server.log I see a postgres-related error and one regarding '${env.DEVICE_NAME}'. Here is [the full log](https://github.com/dcm4che/dcm4chee-arc-light/files/476512/server.log.txt).

**Comment by gunterze** [comment]
Have you linked the postgres container with the archive by
```
    links:
      - slapd:ldap
      - postgres:db
```
?
Is the postgres container running?

**Comment by michaelonken** [comment]
I used the docker-compose file and the related configuration file posted in the wiki. Do I have to change something inside? Sorry, not too familiar with docker...

**Comment by gunterze** [comment]
Guess you already run a container for v5.6.0 with a staled dcm4chee-arc-ear-5.5.2-psql-secure-ui.ear in  /var/local/dcm4chee-arc/wildfly/deployment/.

- stop and remove all containers (e.g. by `>docker-compose down`)
- remove the archive docker images for 5.6.0 (`docker rmi dcm4che/dcm4chee-arc-psql:5.6.0-logstash-secure-ui`) which may not yet contain the final version.
- `sudo rm /var/local/dcm4chee-arc/wildfly/deployment/`
- use the updated samples for `docker-compose.yml` and `docker-compose.yml` from the [wiki page](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Running-on-Docker)

If the problem remains, post it at https://groups.google.com/forum/#!forum/dcm4che
