### ISSUE TITLE
Links to diagrams in the wiki are broken

### ISSUE THREAD

**Issue by fleetwoodfc** [dcm4che/dcm4chee-arc-light#3642]
In the dcm4chee-arc-light Wiki the links to many of the diagrams are broken i.e. uri is displayed but not the actual svg. Example:
<img width="957" alt="Screen Shot 2022-04-11 at 9 34 27 AM" src="https://user-images.githubusercontent.com/8560225/162751403-4f1af81d-3b39-487a-8546-9e14a305bdcb.png">

**Comment by gunterze** [comment]
Broken by github.com.

Workaround:
Replace
```
[[//uml/forward-stgcmt.svg]]
```
by
```
```
![](https://raw.githubusercontent.com/wiki/dcm4che/dcm4chee-arc-light/uml/forward-stgcmt.svg)
```

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/wiki/_compare/13254abaf22e30e59497d559270f5ca2c061aa7b...a20f8c1816ebc6cabfecf8ba343f2eb6f78393a5

https://github.com/dcm4che/dcm4chee-arc-light/wiki/_compare/c963ee01c7cbf7d0d6ab60efe218c723b86f64c5...1f6d74fc756770cbd4e6c82d15278179f34e56a1

**Comment by vrindanayak** [comment]
Fixed images links for pages
````
grep -iRl --include \*.md "\[\[/images/" .
./Deploy-Docker-Images-to-Kubernetes.md
./howTos/misc/Predict-the-size-of-database-growth.md
./howTos/troubleshooting/Monitor-Archive-on-remote-host-or-docker-container-by-VisualVM.md
./howTos/archiveFeatures/configuration/Keycloak-Realm-Management.md
./howTos/archiveFeatures/auditLogging/Secure-Kibana-using-OAuth2-Proxy.md
./howTos/mesaTests/Test-IHE-SWF-using-dcm4che-tools.md
./howTos/securedArchive/Getting-OIDC-Access-Token-using-curl.md
./docker/Run-secured-archive-services-and-Elastic-Stack-on-a-single-host.md
./docker/Run-minimum-set-of-archive-services-on-a-single-host.md
./docker/Distribute-secured-archive-services-and-Elastic-Stack-over-several-hosts-without-Docker-Swarm.md
./docker/Run-secured-archive-services-on-a-single-host.md
./docker/Distribute-secured-archive-services-and-Elastic-Stack-over-several-hosts-using-Docker-Swarm.md
````
