### ISSUE TITLE
Wiki: How do upgrade Keycloak to Keycloak.X 18.0.0

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3671]
How do upgrade Keycloak to Keycloak.X 18.0.0, particularly if the configuration of Keycloak clients in an external DB shall be preserved.

Related: #3658 #3319

**Comment by vrindanayak** [comment]
[Upgrade Keycloak on Docker](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Upgrade-Keycloak-on-Docker)
