### ISSUE TITLE
LDAP Docker image: enable to customize command used for importing LDIF files specified by `LDAP_INIT_CONFIG` at first LDAP startup

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3684]
Configurable by [Environment Variable](https://github.com/dcm4che-dockerfiles/slapd-dcm4chee#environment-variables):

### `LDAP_INIT_CONFIG_CMD`

Specifies the command invoked for importing LDIF files specified by `LDAP_INIT_CONFIG` at first LDAP startup.
`sed+ldapadd` by default.

_Rationale_: enables to replace additional Environment Variables in customized LDIF files

**Comment by petrkalina** [comment]
it would be better to separate the sed and ldapadd i.e.:
