### ISSUE TITLE
QIDO-RS : Search for Series / Instances of Study and Search for Instances of Series returns '204 No Content' if instance purging as well as returning last modified time / ETag is enabled

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#3719]
### Steps to simulate

- Configure series metadata creation and instance purging
- Configure [Qido ETag](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveDevice.html#dcmqidoetag) to `true`
- After instances have been purged, invoke either of the following services

Affects
- [Search for Series of Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/QIDO-RS/SearchForStudySeries)
````
11:41:17,158 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-1) Process GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.2.840.113674.1140.196.200/series from null@127.0.0.1
11:41:17,179 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-1) Last Modified date for Study[uid=1.2.840.113674.1140.196.200] Series[uid=null] is unavailable.
````

- [Search for Instances of Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/QIDO-RS/SearchForStudyInstances)
````
11:41:34,018 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-1) Process GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.2.840.113674.1140.196.200/instances from null@127.0.0.1
11:41:34,036 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-1) Last Modified date for Study[uid=1.2.840.113674.1140.196.200] Series[uid=null] is unavailable.
````

- [Search for Instances of Series of Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/QIDO-RS/SearchForStudySeriesInstances)
````
11:42:09,746 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-1) Process GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.2.840.113674.1140.196.200/series/1.2.840.113674.1140.196.181.300/instances from null@127.0.0.1
11:42:09,760 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-1) Last Modified date for Study[uid=1.2.840.113674.1140.196.200] Series[uid=1.2.840.113674.1140.196.181.300] is unavailable.
````

Related #3210, #470

Verify that the returned `ETag` and `Last Modified Header` by QIDO-RS services:

- [x] [Search for Series of Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/QIDO-RS/SearchForStudySeries)
- [x] [Search for Instances of Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/QIDO-RS/SearchForStudyInstances) - Requires #3725 before testing 
- [x] [Search for Instances of Series of Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/QIDO-RS/SearchForStudySeriesInstances)

does not change after Purging of Instance Records
- with and without `If-Modified-Since` and/or `If-None-Match` Header in the request
- with and without Query Parameter `includefield=all` (with updated Patient information to provoke that different values are returned dependent on providing Query Parameter `includefield=all` or not)

Verify that the returned `ETag` and `Last Modified Header` by WADO-RS services:

- [x] [Retrieve Study Metadata](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveStudyMetadata)
- [x] [Retrieve Series Metadata](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveSeriesMetadata)
- [x] [Retrieve Instance Metadata](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveInstanceMetadata)
- [x] [Retrieve Rendered Study](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveRenderedStudy)
- [x] [Retrieve Rendered Series](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveRenderedSeries)
- [x] [Retrieve Rendered Instance](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveRenderedInstance)
- [x] [Retrieve Study Thumbnail](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveStudyThumbnail)
- [x] [Retrieve Series Thumbnail](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveSeriesThumbnail)
- [x] [Retrieve Instance Thumbnail](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-RS/RetrieveInstanceThumbnail)

does not change after Purging of Instance Records
- with and without `If-Modified-Since` and/or `If-None-Match` Header in the request

Verify that the returned `ETag` and `Last Modified Header` by WADO-URI service:

- [x] [Retrieve Instance by WADO-URI](https://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/openapi.json#/WADO-URI/RetrieveInstanceByWADOURI)
does not change after Purging of Instance Records
- with and without `If-Modified-Since` and/or `If-None-Match` Header in the request

**Comment by gunterze** [comment]
Caused by query for instances to determine last modified time:
```sql
select patient3_.updated_time       as col_0_0_,
       study2_.modified_time        as col_1_0_,
       max(series1_.updated_time)   as col_2_0_,
       max(instance0_.updated_time) as col_3_0_
from instance instance0_
         inner join series series1_ on instance0_.series_fk = series1_.pk
         inner join study study2_ on series1_.study_fk = study2_.pk
         inner join patient patient3_ on study2_.patient_fk = patient3_.pk
where study2_.study_iuid = ?
group by patient3_.pk, study2_.pk
```
Fetching the instance update time instead from the series metadata will harm performance.
Additionally `series.update_time` will be updated on purge, so using it for calculating last modified time / ETag would invalidate cached previous responses by the purging of DB records.

One possible solution is to add an other column `series.modified_time` which
- is considered instead of `series.update_time` for the calculation of the last modified time / ETag
- is set to the current time on creation of the Series on update of Series attributes 
- is set to max(instance_.updated_time) on purging the instance records
