### ISSUE TITLE
Broken Link on Installation Wiki

### ISSUE THREAD

**Issue by halilaksu** [dcm4che/dcm4chee-arc-light#3734]
On installation wiki page, Secured Archive Installation (Secure-Archive-UI-and-RESTful-Services-using-Keycloak) link is broken at to bottom of the page. When you click it, it redirects you on homepage of wiki. I think, that page seems empty.

**Comment by gunterze** [comment]
Seems to be an issue of GitHubs Wiki service. Reported it by https://github.com/orgs/github-community/discussions/21059

**Comment by gunterze** [comment]
Solved by removing db schema files older than 5.12. Seems  the number of files GitHub Wiki can handle is limited,,,

**Comment by halilaksu** [comment]
thanks for ultra fast solution....
