### ISSUE TITLE
UI: If a value in the attribute-list is too long, it destroys the structure of the attribute list

### ISSUE THREAD

**Issue by shral** [dcm4che/dcm4chee-arc-light#3740]
![image](https://user-images.githubusercontent.com/7990614/180777371-9b162da9-e547-4d83-a27a-8dee28473117.png)

**Comment by vrindanayak** [comment]
fixed by https://github.com/dcm4che/dcm4chee-arc-light/commit/a425debc7911583dbb906b5741d3dab0316e4083#diff-085fc926771590150d9e3ae050b1ace60dbc3ed34b0b2867518b55bacbbbf252R17
