### ISSUE TITLE
Restrict access to RESTful services with target URL /dcm4chee-arc/aets/{aet}/... to authenticated users with one of configured Keycloak realm roles

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3754]
Restrict access to RESTful services with target URL `/dcm4chee-arc/aets/{aet}/...` for 

- [x] [QIDO-RS](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#qido_rs)
- [x] [WADO-RS](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#wado_rs)
- [x] [WADO-URI](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#wado_uri)
- [x] [STOW-RS](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#stow_rs)
- [x] [UPS-RS](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#ups_rs)
- [x] [UPS-DIMSE-RS](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#ups_rs)
- [x] [MWL-RS](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#mwl_rs)
- [x] [ECHO-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/ECHO-RS)
- [x] [FIND-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/FIND-RS)
- [x] [MOVE-RS](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#move)
- [x] [DIFF-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/DIFF-RS)
- [x] [EXPORT-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/EXPORT-RS)
- [x] [IMPORT-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IMPORT-RS)
- [x] [IAN-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IAN-RS)
- [x] [IOCM-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IOCM-RS)
- [x] [PAM-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS)
- [x] [MPPS-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/MPPS-RS)
- [x] [STGCMT-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/STGCMT-RS)
- [x] [STGVER-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/STGVER-RS)
- [x] [Import Reports of Study](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IMPAX-REPORT-RS/importReportsOfStudy)
- [x] [PDQ-RS : Compare / Update Patient Demographics](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PDQ-RS)
- [x] [ACCESS-RS](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/ACCESS-RS)
- [x] [STAT-RS : Count / Size services](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services#qido_count)

to authenticated users with one of Keycloak realm roles configured by [Archive Network AE](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/dcmNetworkAE.html) Attribute

Name | Type | Description (LDAP Attribute)
-- | -- | --
Accepted User Role(s) | string | Roles of users from which web requests are accepted; any if absent.. (dcmAcceptedUserRole)

If restricted access to RESTful services is configured, requests from authenticated users with none of the specified roles shall be rejected with _HTTP Error Status 403 Forbidden_.

If the request URL does not contain an Other AE Title of an Application Entity and if there is a [Web Application configuration](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/webApplication.html) in the Archive Device configuration with matching _Web Service Path_:
- if it does **not** provide the [Web Service Class of the RESTful service](https://github.com/dcm4che/dcm4chee-arc-light/wiki/RESTful-Services), reject the service request with HTTP Status 404 Not Found.

Refactor #2400, to use  [Archive Network AE](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/dcmNetworkAE.html) Attribute **Accepted User Role**, instead Web Application property `roles=<accepted-user-role>[,...]`.

_Rationale_: Works also for clustered archive nodes using **Other AE Title** in the path parameter, and for DIMSE Web services configured on the device of the external DICOM Archive.

Related  #3752, #2896

**Comment by vrindanayak** [comment]
Web service class check not required for ECHO-RS, as C-ECHO should be possible with any external AET independent of DIMSE web applications' configuration
