### ISSUE TITLE
UI : Enable to show Studies with created time between <datetime1>-<datetime2>

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#379]
Enable to show Studies created between _<datetime1>_-_<datetime2>_ using query parameter `StudyReceiveDateTime`=_<datetime1>_-_<datetime2>_ of [Search for Studies](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger-dicom.json#!/QIDO-RS/SearchForStudies) implemented by  #378

**Comment by shral** [comment]
Implemented in Angular 2 version of the UI!
