### ISSUE TITLE
New / legacy archive attribute coercion - coerce C_FIND_RSP dataset from `leading-arc` : For Patient / MWL queries, leading archive is incorrectly queried for study

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#3816]
**Describe the bug**

On invocation of Patient / MWL C-FIND queries to coerce C_FIND_RSP dataset from [Leading C-FIND SCP](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveAttributeCoercion.html#dcmleadingcfindscp), [new](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-coerce-impl/src/main/java/org/dcm4chee/arc/coerce/impl/LeadingArchiveCoercionProcessor.java#L89) / [legacy](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-query-scu/src/main/java/org/dcm4chee/arc/query/scu/CFindSCUAttributeCoercion.java#L92) leading archive coercion always defaults to Study level query to external leading archive, causing incorrectly applied attributes in returned dataset.

**To Reproduce**

- Start 2 archives acting as local and leading archives
- Store studies and  create MWLs for the same patients in both archives with differing attribute values on Patient / MWL level
- Configure new / legacy archive attribute coercions on local archive as
````
dn: cn=new-attr-coerce-c-find-rsp-role-scu-leading-arc,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
objectClass: dcmArchiveAttributeCoercion2
cn: new-attr-coerce-c-find-rsp-role-scu-leading-arc
dcmDIMSE: C_FIND_RSP
dcmURI: leading-arc:DCM4CHEE2
dicomTransferRole: SCU
dcmSOPClass: 1.2.840.10008.5.1.4.31
dcmSOPClass: 1.2.840.10008.5.1.4.1.2.1.1
dcmProperty: SendingApplicationEntityTitle=LEADING_ARC
````
and
````
dn: cn=legacy-attr-coerce-c-find-rsp-role-scu-leading-arc,dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
objectClass: dcmArchiveAttributeCoercion
cn: legacy-attr-coerce-c-find-rsp-role-scu-leading-arc
dcmDIMSE: C_FIND_RSP
dcmLeadingCFindSCP: DCM4CHEE2
dicomTransferRole: SCU
dcmSOPClass: 1.2.840.10008.5.1.4.31
dcmSOPClass: 1.2.840.10008.5.1.4.1.2.1.1
dcmProperty: SendingApplicationEntityTitle=LEADING_ARC_LGCY
````
- Invoke Patient / MWL level C-FIND queries using findscu
- Attributes in returned dataset are from local archive (MWL query) or incorrectly applied (Patient query). 
  - For Patient level C-FIND, if there are multiple patients / studies in leading archive, the last returned study match attributes are applied on returned dataset, as local archive queries for all studies (as StudyUID=null in C-FIND-RQ) in leading archive

**Expected Behavior**

Attributes in returned Patient / MWL C-FIND-RSP dataset should be from leading archive

Related #3473

**Comment by gunterze** [comment]
Leading Archive coercion was/is not intended for coercion of responses of Patient / MWL queries

**Comment by vrindanayak** [comment]
LOG message instead of applying leading C-FIND coercion on Patiient / MWL queries, thereby avoiding misleading responses sent back to clients.
