### ISSUE TITLE
UI Navigation: Provide Widget to recreate DB records for a particular Study from stored objects with original attribute values as received

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3823]
Provide Widget to recreate DB records for a particular Study from stored objects with original attribute values as received, invoking RESTful service:

- [`POST /dcm4chee-arc/aets/{aet}/rs/studies/{study}/reimport`](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IOCM-RS/ReimportStudy)

Activating the widget shall open a dialog box to enable to enter values for optional Query Parameters:

- _\<attribute>_=_\<value>_
- `updatePolicy=SUPPLEMENT|MERGE|OVERWRITE`
- `reasonForModification=COERCE|CORRECT`
- `sourceOfPreviousValues=`_\<source>_

The icon for the widget may look like an underscored U with an arrow at the end of one of its arms, to symbolize a combination of download+upload.

Related  #3822

**Comment by shral** [comment]
How should I interpret the result @gunterze , should I show the object coming from server or is it enough to show that the request was successful?
