### ISSUE TITLE
RESTful Service to List/Delete Storage Commitment Results

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#385]
RESTful Service to List/Delete Results of Storage Commitments triggered by Exporters 
- [List Storage Commitment Results](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#!/EXPORT-RS/listStgCmts)
- [Delete Storage Commitment Results](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#!/EXPORT-RS/deleteStgCmts)
- [Delete Storage Commitment Result](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui/src/main/webapp/schema/swagger.json#!/EXPORT-RS/deleteStgCmt)

**Comment by vrindanayak** [comment]
NullPointerException thrown by JsonGenerator.write(..) if storage commit done on Study level
