### ISSUE TITLE
Attribute Coercion: Use LDAP attribute "dcmSupplementFromDeviceReference" instead "dicomDeviceName" to persist DN of Device configuration referenced by Device Name Coercion Parameter

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#3925]
Use LDAP attribute `dcmSupplementFromDeviceReference` instead `dicomDeviceName` to persist DN of [Attribute Coercion](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveAttributeCoercion2.html) attribute:

Name | Type | Description (LDAP Attribute)
-- | -- | --
Device Name Coercion Parameter | string | Device Name Coercion Parameter. Only effective for particular Attribute Coercions. (dcmSupplementFromDeviceReference)

Rationale: `dicomDeviceName` is defined as
```
# 3.1 dicomDeviceName               string      Single
# 
#    This attribute stores the unique name (within the scope of the LDAP database) 
#    for a DICOM Device.
#
#    It is a single-valued attribute. 
#    This attribute's syntax is 'Directory String'.
#    Its case is not significant for equality and substring matches.
# 

attributetype ( 1.2.840.10008.15.0.3.1
   NAME 'dicomDeviceName'
   DESC 'The unique name for the device'
   EQUALITY caseIgnoreMatch
   SUBSTR caseIgnoreSubstringsMatch
   SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
   SINGLE-VALUE )
```
and should therefore not be used to store the full DN of a Device configuration.

**Comment by vrindanayak** [comment]
- [ ] Incorporate `dicomDeviceName` to `dcmSupplementFromDeviceReference` changes also to JSON serializations for new archive attribute coercion
- [ ] Rectify incorrect [attribute reference](https://github.com/dcm4che/dcm4chee-arc-light/commit/772062c377d48bcace07df74482a224c20d4dbe2#diff-107142008cdeb4615a98feb4728f69984c4fdd040f156b2c2353afaef2185cff) from `dcmSupplementFromDeviceName` to `dcmSupplementFromDeviceReference` in JSON serializations for legacy archive attribute coercion
