### ISSUE TITLE
create-mysql.sql: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#399]
SQL create (and update) scripts for MySQL fails with

```
ERROR 1071 (42000) at line 7: Specified key was too long; max key length is 767 bytes
```

with Maria DB 10.x on Ubuntu

**Comment by mikivan1980** [comment]
Problem in:
create index UK_twtj9t0jbl07buyisdtvqrpy on series (failed_iuids);
create index UK_btfu9p1kwhrr444muytvxguci on study (failed_iuids);

field -> failed_iuids varchar(4000)  -> the excess above the norm!!!

from MySQL 5.6 Reference Manual:
system variables -> innodb_large_prefix
Enable this option to allow index key prefixes longer than 767 bytes (up to 3072 bytes) for InnoDB tables that use the DYNAMIC and COMPRESSED row formats. (Creating such tables also requires the option values innodb_file_format=barracuda and innodb_file_per_table=true.) See Section 14.8.8, “Limits on InnoDB Tables” for the relevant maximums associated with index key prefixes under various settings.

**Comment by gunterze** [comment]
I know, I just did not take the time to provide a patch of the create script - created by hibernate -  for mysql into the maven build.
