### ISSUE TITLE
UI Configuration : Allow descriptions for enums

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4040]
Extend configuration fields defined as `enum` in `.schema.json` files to contain possibility for description

**Comment by shral** [comment]
One can no add label and description in the enum values in the schemas like for example:
```
        ...
        "enum":[
              "ARCHIVE|Test Description|Test label",
              "COMP|Only description",
              "CAD||Only label",
              "DSS"
              ...
          ]
          ...
```

**Comment by vrindanayak** [comment]
`Archive Device Extension` configuration no longer opens up

![image](https://github.com/dcm4che/dcm4chee-arc-light/assets/15785031/31f84398-afb2-4861-a657-9f320941b86f)
