### ISSUE TITLE
Support multiple Patient IDs in path parameter of RESTful services

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#4161]
Support multiple Patient IDs separated by `~` in _Path Parameters_ of RESTful services:

 - [x] [PUT  /dcm4chee-arc/aets/{aet}/rs/patients/{patientID}](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/UpdatePatient) - Update, Create, Merge or Change Patient ID of patient
 - [x] [DELETE /dcm4chee-arc/aets/{aet}/rs/patients/{patientID}](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/DeletePatient) - Delete Patient Permanently
 - [x] [POST /dcm4chee-arc/aets/{aet}/rs/patients/{patientID}/merge](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/MergePatients) - Merge Patients
 - [x] [POST /dcm4chee-arc/aets/{aet}/rs/patients/{priorPatientID}/merge/{patientID}](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/MergePatient) - Merge Patient
 - [x] [POST /dcm4chee-arc/aets/{aet}/rs/patients/{priorPatientID}/changeid/{patientID}](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/ChangePatientID) - Change Patient ID
 - [x] [POST /dcm4chee-arc/aets/{aet}/rs/patients/{patientID}/unmerge](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/UnmergePatient) - Unmerge Patient
 - [x] [POST /dcm4chee-arc/hl7apps/{hl7AppNameWithFacility}/hl7/{externalHL7AppNameWithFacility}/patients/{priorPatientID}/merge](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/MergePatientExternalLegacy) - Merge Patients in external archive Legacy
 - [x] [POST /dcm4chee-arc/hl7apps/{hl7AppNameWithFacility}/hl7/{externalHL7AppNameWithFacility}/patients/{priorPatientID}/changeid](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/ChangePatientIDExternalLegacy) - Change Patient ID in external archive Legacy
 - [x] [PUT /dcm4chee-arc/hl7apps/{hl7AppNameWithFacility}/hl7/{externalHL7AppNameWithFacility}/patients/{PatientID}](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PAM-RS/UpdatePatientExternal) - Update, Merge or Change Patient ID of Patient in external archive
 - [x] [POST /dcm4chee-arc/aets/{aet}/rs/patients/{patientID}/pdq/{PDQServiceID}](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PDQ-RS/updatePatientDemographics) - Update Patient Demographics
 - [x] [GET /dcm4chee-arc/pdq/{pdqServiceID}/patients/{patientID}](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/PDQ-RS/queryPatientDemographics) - Query Patient Demographics
 - [x] [GET /dcm4chee-arc/xroad/RR441/{patientID}](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/X-ROAD-RS/xroadRR441) - x-road RR441
 
and
- [x]  return 400 Bad Request, if one of  [Archive Device attributes](https://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveDevice.html):
  
  Name | Type | Description (LDAP Attribute)
  -- | -- | --
  Trusted Issuer of Patient ID(s) | string |  Trusted Assigning Authority of Patient IDs in received DICOM objects and HL7 messages. If both, this field and **Trusted Issuer of Patient ID Pattern** are configured, Patient IDs not qualified by trusted Assigning Authority matching the pattern specified in **Trusted Issuer of Patient ID Pattern**, will be checked against one of the specified Assigning Authorities in this field. If Patient IDs are not qualified by either of these fields, they won't be used for identifying the Patient. If neither this field nor **Trusted Issuer of Patient ID Pattern** is configured, all Patient IDs in received DICOM Objects and HL7 messages will be used for identifying the Patient. Format: `{Issuer of Patient ID}[&{UniversalEntityID}&{UniversalEntityIDType}]`.  (dcmTrustedIssuerOfPatientID)
  Trusted Issuer of Patient ID Pattern | string |  Regular Expression identifying trusted Assigning Authority of Patient IDs in received DICOM objects and HL7 messages. If both, this field and **Trusted Issuer of Patient ID** are configured, Patient IDs not qualified by trusted Assigning Authority matching the specified pattern, will be checked against one of the specified Assigning Authorities in **Trusted Issuer of Patient ID** field. If Patient IDs are not qualified by either of these fields, they won't be used for identifying the Patient. If neither this field nor **Trusted Issuer of Patient ID** is configured, all Patient IDs in received DICOM Objects and HL7 messages will be used for identifying the Patient.(dcmTrustedIssuerOfPatientIDPattern)
   
  is configured and none of the Patient IDs are qualified by a trusted Issuer of Patient ID.

**Attention** : For PDQ and XRoad RS services above, only the first patient identifier in trusted patient identifiers collection is considered for processing.

 #4053, #4146, #4160

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/c1840599bd36078d51e03486803dcf1e86a54659
https://github.com/dcm4che/dcm4chee-arc-light/commit/f52a10c5d4fc9e155f828eff54271cef855a967a
https://github.com/dcm4che/dcm4chee-arc-light/commit/e0559cbbc0d926913536ba4b989f121732e3c2d9
