### ISSUE TITLE
UI Monitoring tabs : Extend `Status` dropdown filter to include `SCHEDULED FOR RETRY`

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4164]
Requires #4141

**Comment by petrkalina** [comment]
Testing:

- configure i.e.
```
dn: dcmExporterID=TESTSTORESCP,dicomDeviceName=j4c-arc1,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
objectClass: dcmExporter
dcmExporterID: TESTSTORESCP
dcmQueueName: Export
dcmURI: dicom:TESTSTORESCP
dicomAETitle: ARC1
dicomDescription: Export to TESTSTORESCP
```
- prepare test data
```
j4care@test-arc:~$ docker run --rm docker.j4care.com/j4c-tools tests/task-mgt/send-data.sh ARC1@test-arc.lan.j4care.com:11112 https://test-arc.lan.j4care.com:8843 https://test-arc.lan.j4care.com:8443/dcm4chee-arc/aets/ARC1 admin changeit
```
- delete on file on filesystem for some stgver tasks to fail
```
sudo rm /data-dcm-multipass/dcm1/2023/09/07/C80ED83B/55D220DE/55D220DF-14945808
```
- reschedule all stgver tasks in the UI

Results in `Export Tasks`:

- [ ] New status does not fit into the box for task counts by status
<img width="168" alt="Screenshot" src="https://github.com/dcm4che/dcm4chee-arc-light/assets/1150350/e5a96a10-9298-4f82-aafe-9befa39b111c">

- [ ] When `Batch ID grouped` is checked, the view of the batch does not show SCHEDULED FOR RETRY tasks.
<img width="1248" alt="Screenshot" src="https://github.com/dcm4che/dcm4chee-arc-light/assets/1150350/10332301-c756-4503-b656-02eb89739bea">

- [ ] When `Batch ID grouped` is checked and `Status=SCHEDULED FOR RETRY` is selected, no batches are displayed, even if there are matching tasks and batch present
<img width="1633" alt="Screenshot" src="https://github.com/dcm4che/dcm4chee-arc-light/assets/1150350/c7f4dfbc-b926-49a9-bf94-6489edca03e9">

- [ ] When `Batch ID` and `Status=*` filters is set, the box for task counts by status shows SCHEDULED FOR RETRY=0, even if there exist SCHEDULED FOR RETRY tasks
<img width="1616" alt="Screenshot" src="https://github.com/dcm4che/dcm4chee-arc-light/assets/1150350/28f519d9-2509-4f8b-a20b-508b6d91f99d">

- [ ] When `Batch ID` and `Status=SCHEDULED FOR RETRY` (or any other status) filters is set, the box for task counts does not display any numbers
<img width="1666" alt="Screenshot" src="https://github.com/dcm4che/dcm4chee-arc-light/assets/1150350/687b7f04-1538-40ed-8ec9-492f55523345">

Results in `Storage Verification`:

- [ ] New status does not fit into the box for task counts by status - also applies

- [ ] When `Batch ID grouped` is checked, the view of the batch does not show SCHEDULED FOR RETRY tasks - also applies

- [ ] When `Batch ID grouped` is checked and `Status=SCHEDULED FOR RETRY` is selected error 400 occurs
<img width="1674" alt="Screenshot" src="https://github.com/dcm4che/dcm4chee-arc-light/assets/1150350/f7bcc19a-ddbc-45d9-b38a-5fb83da3db75">

```
https://test-arc.lan.j4care.com:8443/dcm4chee-arc/monitor/stgver/batch?limit=21&offset=0&orderby=-updatedTime&status=SCHEDULED%20FOR%20RETRY
...
{"exception":null,"propertyViolations":[{"constraintType":"PROPERTY","path":"status","message":"must match \"SCHEDULED|IN PROCESS|COMPLETED|WARNING|FAILED|CANCELED\"","value":"SCHEDULED FOR RETRY"}],"classViolations":[],"parameterViolations":[],"returnValueViolations":[]}
```

Results in `Monitoring / queues`:

- [ ] New status does not fit into the box for task counts by status - also applies

- [ ] `Batch ID grouped` checkbox is not available - that is also a possible improvement to make..

- [ ] Status dropdown does not contain the SCHEDULED FOR RETRY
<img width="1372" alt="Screenshot" src="https://github.com/dcm4che/dcm4chee-arc-light/assets/1150350/0733a832-21b2-41cf-8225-631c48011794">

- [ ] Due both above points, it is not possible to test display with (i) Batch ID grouped and (ii) with Batch ID=xxx and Status=SCHEDULED FOR RETRY is set
