### ISSUE TITLE
DB2 backend : Storing DICOM objects to archive fails

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4217]
Related
- #4209 
- https://github.com/dcm4che/dcm4chee-arc-light/commit/85b0a9b099bd1ab65b8bc485d6eb97425188e23a

[db2-dicom-cstore.log](https://github.com/dcm4che/dcm4chee-arc-light/files/12597286/db2-dicom-cstore.log)

Reference for

> Caused by: [com.ibm.db2.jcc.am](http://com.ibm.db2.jcc.am/).SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-134, SQLSTATE=42907, SQLERRMC=ATTRS, DRIVER=4.23.42

can be found in https://www.cs.gordon.edu/courses/cps352/2015-spring/resources/db2m2e90.pdf#page=25

**Comment by gunterze** [comment]
Fixed by #4221
