### ISSUE TITLE
UI: Navigation Study: Replace checkbox by dropdown to filter for Studies containing Series of any or all of specified Modalities 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#4256]
Replace
![Screenshot from 2023-10-12 13-29-22](https://github.com/dcm4che/dcm4chee-arc-light/assets/400095/ac4336b4-79e7-49fb-b0da-0109767f1b1e)
by
![image](https://github.com/dcm4che/dcm4chee-arc-light/assets/15785031/abe76252-d525-4f47-9da2-bd4aea747dfc)
to filter for Studies containing Series of any or all of specified Modalities .

**Comment by shral** [comment]
@gunterze what should be send as a filter in the background, for each selection?
