### ISSUE TITLE
UI: Monitoring / Storage commitments -> Flush Before fails with 400 Bad Request

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#4261]
UI: Monitoring / Storage commitments -> Flush Before fails with `400 Bad Request`, caused by missing dashes in value of _Query Parameter_  `updatedBefore`, invoking [`DELETE dcm4chee-arc/stgcmt`](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/STGCMT-RS/deleteStgCmts)

See also no need for modal window to enter the date value - why not including the date field directly in the Storage commitments Tab?

**Comment by vrindanayak** [comment]
> See also no need for modal window to enter the date value - why not including the date field directly in the Storage commitments Tab?

`updatedBefore` query filter is used only for [Delete Storage Commitment Results](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/STGCMT-RS/deleteStgCmts) service and not for [List Storage Commitment Results](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/STGCMT-RS/listStgCmts) service. 
Including the filter directly in the Tab would be misleading to the user on using `SUBMIT` - with the filter being unused and redundant in this case.
