### ISSUE TITLE
Copy / Move Instances to Study RS service : Series IUID not generated on copying / moving to target study, if Series IUID and Study IUID values are equal in source study 

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4335]
Case 1 : Source and target studies both have identical values for Series IUID & Study IUID in their attributes respectively and each consist only one DICOM instance - [case1-testdata.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/13850112/case1.zip)
Steps to reproduce :
- Store both studies to archive
- Invoke [Copy Instances to Study](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IOCM-RS/CopyInstances) / [Move Instances to Study](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IOCM-RS/MoveInstances) of one study to other **target study**
- Copies instances of source study to target study's series instead of creating a new series in target study

  ![image](https://github.com/dcm4che/dcm4chee-arc-light/assets/15785031/ce4fe6b3-1228-4806-b6ee-815c40f4995d)

Case 2 : Source study have identical values for Series IUID & Study IUID in its attributes and consist only one DICOM instance. Target study has different values for Series IUID & Study IUID and consist only one DICOM instance - [case2-testdata.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/13850129/case2.zip)
Steps to reproduce :
- Store both studies to archive
- Invoke [Copy Instances to Study](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IOCM-RS/CopyInstances)  / [Move Instances to Study](https://petstore.swagger.io/index.html?url=https://dcm4che.github.io/dcm4chee-arc-light/swagger/openapi.json#/IOCM-RS/MoveInstances) of one study to **target study** (`US` modality)
- Creates new series in target study, however the value for Series IUID is not generated

  ![image](https://github.com/dcm4che/dcm4chee-arc-light/assets/15785031/f2a5e943-e0d9-44bc-9bae-b0721edd3a80)

  ![image](https://github.com/dcm4che/dcm4chee-arc-light/assets/15785031/50502ded-0490-4da3-88bd-f0056dcb3109)

Caused by : https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-retrieve/src/main/java/org/dcm4chee/arc/retrieve/impl/RetrieveServiceImpl.java#L464-L465

**Comment by gunterze** [comment]
[DICOM PS 3.5](https://dicom.nema.org/medical/dicom/current/output/html/part05.html#chapter_9):
> 9 Unique Identifiers (UIDs)
>
>Unique Identifiers (UIDs) provide the capability to uniquely identify a wide variety of items. They guarantee uniqueness across multiple countries, sites, vendors and equipment. Different classes of objects, instance of objects and information entities can be distinguished from one another across the DICOM universe of discourse irrespective of any semantic context.
>
>Note:
>
>For example the same UID cannot be used to identify both a study instance (Study Instance UID) and a series instance (Series Instance UID) within that study or a different study. Implementers also need to be cautioned against building new UIDs by derivation (for example by adding a suffix) from a UID assigned by another implementation.
