### ISSUE TITLE
ecs jboss module not found in binary 

### ISSUE THREAD

**Issue by ph73nt** [dcm4che/dcm4chee-arc-light#437]
Tested with dcm4chee-arc-5.7.0-mysql
Installation requests ecs module as described, but not found in the binary install zip file.

Setup WildFly
...
7. Install ecs-object-client 3.0.0 libraries as JBoss modules:
> cd  $WILDFLY_HOME
> unzip $DCM4CHEE_ARC/jboss-module/ecs-object-client-jboss-modules.zip

**Comment by gunterze** [comment]
It was added in 5.7.1:
```
unzip -l ~/Downloads/dcm4chee-arc-5.7.1-mysql.zip | grep ecs
   748368  2016-10-31 11:00   dcm4chee-arc-5.7.1-mysql/jboss-modules/ecs-object-client-jboss-modules-3.0.0.zip
```
