### ISSUE TITLE
Enable `realm-management` - `manage-users` role by default to `admin` / `user` users

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4417]
**Attention** : Assigning `realm-management` - `manage-users` role to `admin` / `user` users neither provides these users access to Keycloak Administration Console nor does it allow changing settings of any other users!

Related #4416

**Comment by njiddasalifu** [comment]
hello @vrindanayak @gunterze i'm reaching out regarding the running of dcm4chee arc 5. using docker compose. I am facing an issue that the sldap container is not running. where can we discuss this.
