### ISSUE TITLE
Installation - Wildfly cli scripts throw error/warning

### ISSUE THREAD

**Issue by ph73nt** [dcm4che/dcm4chee-arc-light#443]
Tested with 5.7.1 and wildfly-10.1.0.Final

For the deployment cli scripts

$WILDFLY_HOME/bin/jboss-cli.sh -c -f $DCM4CHEE_ARC/cli/add-data-source-<db>.cli

I get the warning/error:

'/opt/dcm4chee/dcm4chee-arc-5.7.1-mysql/cli/add-data-source-mysql.cli' is assumed to be a command(s) but the commands to execute have been specified by another argument: [-f]

and 

$WILDFLY_HOME/bin/jboss-cli.sh -c -f $DCM4CHEE_ARC/cli/add-jms-queues.cli

gives

'/opt/dcm4chee/dcm4chee-arc-5.7.1-mysql/cli/add-jms-queues.cli' is assumed to be a command(s) but the commands to execute have been specified by another argument: [-f]

The command contained within do not seem to have been executed (if I execute them manually there is no complaint of duplication from the console). Naturally leads to errors when I deploy: 

[standalone@localhost:9990 /] /opt/dcm4chee/dcm4chee-arc-5.7.1-mysql/deploy/dcm4chee-arc-ear-5.7.1-mysql.ear

I get the error:

{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"WFLYCTL0412: Required services that are not installed:" => ["jboss.naming.context.java.PacsDS"],"WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.persistenceunit.\"dcm4chee-arc-ear-5.7.1-mysql.ear#dcm4chee-arc\" is missing [jboss.naming.context.java.PacsDS]","jboss.persistenceunit.\"dcm4chee-arc-ear-5.7.1-mysql.ear#dcm4chee-arc\".__FIRST_PHASE__ is missing [jboss.naming.context.java.PacsDS]"]}}}

**Comment by gunterze** [comment]
The -f short option was removed by Wildfly 10, you have to use the long option --file instead.  The other error seems related to your DB setup. Please post questions about the installation at [dcm4che google group](https://groups.google.com/forum/#!forum/dcm4che) . Github issues are reserved for reporting bugs and feature requests.
