### ISSUE TITLE
Using UI date selection widgets populates field with wrong date (one day prior)

### ISSUE THREAD

**Issue by isolovey** [dcm4che/dcm4chee-arc-light#4469]
**Describe the bug**

When selecting a date in the dcm4chee-arc UI, you can select a date with a widget by clicking the calendar icon. The date selected there should populate the field, but instead a date one day before the selected one ends up in the field. I.e. selecting April 1 populates the field with `20240331`, selecting April 3-6 populates it with `20240402-20240405`, etc.

**To Reproduce**

Select a date using calendar widget in any date field, whether it accepts a range (`Study Date` on `Studies` tab) or a single date only (`Birth Date` on `Patients` tab).

**Environment**

Can be replicated in a [docker-compose environment](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host#use-docker-compose) accessed in Firefox or Chrome in MacOS, Android, Linux.

**Comment by shral** [comment]
Pleas pull and try again ( If you are using a code version ) otherwise you have to wait until the next release.
