### ISSUE TITLE
UI Navigation - Upload files : The widget does not allow selecting files, instead provides option to select a directory

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#4556]
![image](https://github.com/user-attachments/assets/6620fb1b-0d8f-4ba4-bd16-170cd5967e20)

**Comment by shral** [comment]
Since it is currently not technically possible to allow the simultaneous selection of folders and files in the browser's file picker, I will add a checkbox so that the user can first decide what he wants to upload.
