### ISSUE TITLE
Location of files for C-GET

### ISSUE THREAD

**Issue by kamal-1984** [dcm4che/dcm4chee-arc-light#48]
I am using the GetSCU class to get the dicom objects from DICOM server,i am getting status 0H.but i am unable to find the location where exactly file(Dicom object) is stored.

Where will the configuration for strorage location for C-GET service,

I can see the configuration for Storage (C-STORE) in default-config.ldif(dcmURI: file:///var/local/dcm4chee-arc/fs1)

**Comment by gunterze** [comment]
C-GET is working:
```
$ getscu -cDCM4CHEE@localhost:11112 -mStudyInstanceUID=1.2.840.113564.3.1.2.149.98.80.58.20041008160233013120
18:44:46,239 INFO  - Initiate connection from 0.0.0.0/0.0.0.0:0 to localhost:11112
18:44:46,245 INFO  - Established connection Socket[addr=localhost/127.0.0.1,port=11112,localport=44187]
18:44:46,253 INFO  - GETSCU->DCM4CHEE(1) << A-ASSOCIATE-RQ
18:44:46,255 INFO  - GETSCU->DCM4CHEE(1) >> A-ASSOCIATE-AC
18:44:46,260 INFO  - GETSCU->DCM4CHEE(1) << 1:C-GET-RQ[pcid=1, prior=0
  cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
18:44:46,325 INFO  - GETSCU->DCM4CHEE(1) >> 1:C-GET-RSP[pcid=1, remaining=1, completed=0, failed=0, warning=0, status=ff00H
  cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
18:44:46,326 INFO  - GETSCU->DCM4CHEE(1) >> 1:C-STORE-RQ[pcid=33, prior=0
  cuid=1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
  iuid=1.2.840.113564.10.1.370394648520266171791512273258241104425 - ?
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian
18:44:46,326 INFO  - GETSCU->DCM4CHEE(1): M-WRITE ./1.2.840.113564.10.1.370394648520266171791512273258241104425
18:44:46,353 INFO  - GETSCU->DCM4CHEE(1) << 1:C-STORE-RSP[pcid=33, status=0H
  cuid=1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
  iuid=1.2.840.113564.10.1.370394648520266171791512273258241104425 - ?
  tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian
18:44:46,356 INFO  - GETSCU->DCM4CHEE(1) >> 1:C-GET-RSP[pcid=1, completed=1, failed=0, warning=0, status=0H
  cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET
  tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
18:44:46,356 INFO  - GETSCU->DCM4CHEE(1) << A-RELEASE-RQ
18:44:46,356 INFO  - GETSCU->DCM4CHEE(1) >> A-RELEASE-RP
18:44:46,356 INFO  - GETSCU->DCM4CHEE(1): close Socket[addr=localhost/127.0.0.1,port=11112,localport=44187]
```

**Comment by kamal-1984** [comment]
can you give me the location of files where it is storing in local machine.

On Wed, Mar 2, 2016 at 11:16 PM, Gunter Zeilinger <notifications@github.com>
wrote:

> C-GET is working:
>
> $ getscu -cDCM4CHEE@localhost:11112 -mStudyInstanceUID=1.2.840.113564.3.1.2.149.98.80.58.20041008160233013120
> 18:44:46,239 INFO  - Initiate connection from 0.0.0.0/0.0.0.0:0 to localhost:11112
> 18:44:46,245 INFO  - Established connection Socket[addr=localhost/127.0.0.1,port=11112,localport=44187]
> 18:44:46,253 INFO  - GETSCU->DCM4CHEE(1) << A-ASSOCIATE-RQ
> 18:44:46,255 INFO  - GETSCU->DCM4CHEE(1) >> A-ASSOCIATE-AC
> 18:44:46,260 INFO  - GETSCU->DCM4CHEE(1) << 1:C-GET-RQ[pcid=1, prior=0
>   cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 18:44:46,325 INFO  - GETSCU->DCM4CHEE(1) >> 1:C-GET-RSP[pcid=1, remaining=1, completed=0, failed=0, warning=0, status=ff00H
>   cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 18:44:46,326 INFO  - GETSCU->DCM4CHEE(1) >> 1:C-STORE-RQ[pcid=33, prior=0
>   cuid=1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
>   iuid=1.2.840.113564.10.1.370394648520266171791512273258241104425 - ?
>   tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian
> 18:44:46,326 INFO  - GETSCU->DCM4CHEE(1): M-WRITE ./1.2.840.113564.10.1.370394648520266171791512273258241104425
> 18:44:46,353 INFO  - GETSCU->DCM4CHEE(1) << 1:C-STORE-RSP[pcid=33, status=0H
>   cuid=1.2.840.10008.5.1.4.1.1.1 - Computed Radiography Image Storage
>   iuid=1.2.840.113564.10.1.370394648520266171791512273258241104425 - ?
>   tsuid=1.2.840.10008.1.2.1 - Explicit VR Little Endian
> 18:44:46,356 INFO  - GETSCU->DCM4CHEE(1) >> 1:C-GET-RSP[pcid=1, completed=1, failed=0, warning=0, status=0H
>   cuid=1.2.840.10008.5.1.4.1.2.2.3 - Study Root Query/Retrieve Information Model - GET
>   tsuid=1.2.840.10008.1.2 - Implicit VR Little Endian
> 18:44:46,356 INFO  - GETSCU->DCM4CHEE(1) << A-RELEASE-RQ
> 18:44:46,356 INFO  - GETSCU->DCM4CHEE(1) >> A-RELEASE-RP
> 18:44:46,356 INFO  - GETSCU->DCM4CHEE(1): close Socket[addr=localhost/127.0.0.1,port=11112,localport=44187]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcm4che/dcm4chee-arc-light/issues/48#issuecomment-191346459>
> .
>



-- 
Kamalakar,
Senior Software Engineer,
OSI Systems,
Hyderabad,
Phone-9490602175.

**Comment by gunterze** [comment]
Please do not use the issue tracker for questions about dcm4che/dccm4chee-arc. Post it at https://groups.google.com/forum/#!forum/dcm4che

**Comment by kamal-1984** [comment]
Apologies from my side, i am new to DICOM & DCM4CHEE ARCHIVE server,


i have setup DCM4CHEE server in my local machine, so now i am trying to
explore on different services like C-STORE , C-GET & C-MOVE.

so out of curiosity i posted it in wrong location.

On Thu, Mar 3, 2016 at 10:21 AM, Gunter Zeilinger <notifications@github.com>
wrote:

> Please do not use the issue tracker for questions about
> dcm4che/dccm4chee-arc. Post it at
> https://groups.google.com/forum/#!forum/dcm4che
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcm4che/dcm4chee-arc-light/issues/48#issuecomment-191582324>
> .
>



-- 
Kamalakar,
Senior Software Engineer,
OSI Systems,
Hyderabad,
Phone-9490602175.
