### ISSUE TITLE
Missing Configuration for Device 'dcm4chee-arc'

### ISSUE THREAD

**Issue by xchz** [dcm4che/dcm4chee-arc-light#487]
hi @gunterze , i have some problem when install dcm4chee-arc-light5.x
error info :
Missing Configuration for Device 'dcm4chee-arc' - you may change the Device name by System Property 'dcm4chee-arc.DeviceName'
i use Apache DS 2.0.0 , and configure it with 
 $DCM4CHEE_ARC/ldap/apacheds/dicom.ldif
$DCM4CHEE_ARC/ldap/apacheds/dcm4che.ldif
$DCM4CHEE_ARC/ldap/apacheds/dcm4chee-archive.ldif
[Apache DS 2.0.0](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#apache-ds-200)  
it works. 
but when i deploy, occur error : Missing Configuration for Device 'dcm4chee-arc' - you may change the Device name by System Property 'dcm4chee-arc.DeviceName'
so i need to configure with [Import default configuration into LDAP Server](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#import-default-configuration-into-ldap-server)?
thanks

**Comment by gunterze** [comment]
See https://groups.google.com/forum/#!searchin/dcm4che/Missing$20Configuration$20for$20Device|sort:relevance/dcm4che/_mOJUo7Etm4/B8NgEDDaCAAJ

Please use the forum for asking questions.
