### ISSUE TITLE
Restrict C-MOVE Destinations to a configurable list of AE Titles for each Archive AE

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#498]
Configurable by [Archive Network AE](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveNetworkAE.html#archive-network-ae) Parameter

| Name | Description |
| -- | -- |
| Accepted Move Destination(s) | Accepted Move Destination in C-MOVE requests; any if absent. |

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4che/commit/23ab117a071a2f873e5f101c83d3baf49280db6f
