### ISSUE TITLE
Enable to configure several Audit Loggers to send Audit Messages to several Audit Record Repositories

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#501]
Make `commonName` of Audit Logger configurable, so an Device may contain several Audit Loggers,

Each Audit Logger shall use a different spool directory for Audit Messages to be emitted (e.g. by using `<commonName>.replace(' ','_')` in the directory path)

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/5ddac0dbd8d977a81200e48b4262b11a40f2220a
