### ISSUE TITLE
Docker-compose not working on Windows

### ISSUE THREAD

**Issue by Davio** [dcm4che/dcm4chee-arc-light#521]
I try to use a basic stack (no ELK) on Windows 10 (with the official Docker for Windows https://docs.docker.com/docker-for-windows/) and get the following errors:

ERROR: for postgres  Cannot start service postgres: invalid header field value "oci runtime error: container_linux.go:24
7: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\
\\\"/etc/timezone\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/fe120cbdad1d9c0ff0b18395b8899a5e53fe3a6e678f16e8132
c2122223c00b2\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/fe120cbdad1d9c0ff0b18395b8899a5e53fe3a6e678f16e8132c2122223c00
b2/etc/timezone\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"

ERROR: for slapd  Cannot start service slapd: invalid header field value "oci runtime error: container_linux.go:247: sta
rting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/e
tc/timezone\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/078cd4b0ec24e5ddcbde65e74c8c8895d92bfe0e8d7b035a0737508db
ce54cb6\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/078cd4b0ec24e5ddcbde65e74c8c8895d92bfe0e8d7b035a0737508dbce54cb6/etc
/timezone\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
ERROR: Encountered errors while bringing up the project.

I'm running docker-compose up from an elevated PowerShell

**Comment by gunterze** [comment]
You have to adjust the volumes mappings for Windows. Remove
- /etc/timezone:/etc/timezone
- /etc/localtime:/etc/localtime

and replace /var/local/.. by a windows path. You also have to share the
drive (s.
https://docs.docker.com/docker-for-windows/#docker-settings#shared-drives )

**Comment by vrindanayak** [comment]
Docker-compose works with Docker Toolkit for Windows as well as Docker for Windows. 

The only thing which doesn't work is volume mappings of host containers to windows location. 
- Docker toolkit for Windows : Volume mappings do not work for slapd and postgres
- Docker for Windows : Volume mappings does not work for postgres
