### ISSUE TITLE
No entry for "dn: dicomDeviceName=unknown,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org" in default-config.ldif

### ISSUE THREAD

**Issue by embaker** [dcm4che/dcm4chee-arc-light#535]
When installing dcm4chee-arc-5.8.1-psql-secure with OpenLDAP, [importing the default configuration into ldap](https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#import-default-configuration-into-ldap-server):
 
`ldapadd ... -f default-config.ldif`

will fail on the entries for

- `dn: cn=dicom,dicomDeviceName=unknown,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org`
- `dn: dicomAETitle=UNKNOWN,dicomDeviceName=unknown,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org`

because there is no entry for

- `dn: dicomDeviceName=unknown,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org`

**Comment by gunterze** [comment]
```
dn: dicomDeviceName=unknown,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
dicomInstalled: TRUE
dicomDeviceName: unknown
objectClass: dicomDevice
objectClass: dcmDevice
```
was missing in default-config.ldif. Fixed version for 3.8.1 in attached ZIP
[default-config.ldif.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/738505/default-config.ldif.zip)
