### ISSUE TITLE
can't deploy dcm4chee-arc-ear-5.x-psql-secure-ui.ear

### ISSUE THREAD

**Issue by Alexander12x** [dcm4che/dcm4chee-arc-light#554]
Hi,
**There is a problem deploying dcm4chee-arc-ear-5.x-psql-secure-ui.ear**
page https://github.com/dcm4che/dcm4chee-arc-light/wiki/How-to-Install-secured-version-of-DCM4CHEE-Archive-%28Secure-UI-and-Secure-RESTful%29---Wildfly-and-Keycloak
step 18

Error with authorizing in LDAP
.....
Caused by: javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]"},"WFLYCTL0412: Required services that are not installed:" => ["jboss.deployment.subunit.\"dcm4chee-arc-ear-5.8.1-psql-secure.ear\".\"dcm4chee-arc-service-5.8.1.jar\".component.ArchiveServiceImpl.START"],"WFLYCTL0180: Services with missing/unavailable dependencies" => undefined}}}

machine: centos 6,  Linux pacs 2.6.32-642.13.1.el6.x86_64 #1 SMP Wed Jan 11 20:56:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I complete all steps from secured and default instructions:
(default: https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation)

additionally 
- corrected /etc/hosts:  "[realIP] pacs pacs.dcm4che.org"
- rsyslog.conf

Could you show where is the mistake?

Files:

[dcm4chee-arc.xml.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/763542/dcm4chee-arc.xml.zip) 
(dcm4chee-arc.xml with corrections: localhost->pacs, webservices: 0.0.0.0 to 127.0.0.1 and dcm4che's changes)
[slapd_ldap.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/763516/slapd_ldap.zip)
(slapd.conf and ldap.conf:    no TLS, corrected BASE, rootdn, rootpw,....  commented some indexes due to errors)
[slapd.d.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/763517/slapd.d.zip)
this is the LDAP DB after installation, corrected olcSuffix,olcRootDN (bdb), olcAccess(monitor)

[logWildFly.txt](https://github.com/dcm4che/dcm4chee-arc-light/files/763496/logWildFly.txt)
log of the WildFly with error
**[dcm4che-instuction.xlsx](https://github.com/dcm4che/dcm4chee-arc-light/files/763526/dcm4che-instuction.xlsx)**
All steps in sequence from secure to default and back

**Comment by vrindanayak** [comment]
Wildfly Log indicates invalid credentials of LDAP. Updated Step 3 in [How to Install secured version of DCM4CHEE Archive (Secure UI and Secure RESTful) - Wildfly and Keycloak](https://github.com/dcm4che/dcm4chee-arc-light/wiki/How-to-Install-secured-version-of-DCM4CHEE-Archive-%28Secure-UI-and-Secure-RESTful%29---Wildfly-and-Keycloak)

Please retry and post further questions regarding Installation/Upgrade in forum : [dcm4che google group](https://groups.google.com/forum/?hl=en#!forum/dcm4che)
