### ISSUE TITLE
MWL Feed from HL7 Order Message: optionally extract Scheduled Station AE Title from ORC-18

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#599]
Configurable on  [Archive Device](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveDevice.html) level or [Archive HL7 Application](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/archiveHL7Application.html) level by Parameters

| Name | Description | LDAP attribute |
| -- | -- | -- |
| HL7 Scheduled Station AE Title  in Order | Specifies location of Scheduled Station AE Title in received HL7 Order message. Enumerated values: ORC_18. Not effective for HL7 v2.5.1 OMI^O23 with IPC segment. If absent or no value is provided in the configured field, the Scheduled Station AE Title is selected according configured rules.  | hl7ScheduledStationAETInOrder |

Related: #480, #478

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/8321a9382088926565b3ace429451cb8c7cd5d15
