### ISSUE TITLE
 SQL Server 14 gets the SQL Server 2000 Dialect by Default

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#606]
When running the dcm4chee-arc-ear-5.9.3-sqlserver.ear against microsoft/mssql-server-linux:cpt1-4 the wildfly logs show erros related to the syntax of generated sql commands i.e.

`2017-03-28 07:55:41,816 WARN  [org.dcm4chee.arc.ian.scu.impl.IANScheduler] (EE-ManagedScheduledExecutorService-default-Thread-8) execute throws Exception: javax.ejb.EJBException: javax.persistence.Persist
enceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
...
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '@P0'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
`

this might be due to the previous warning in the logs:

`2017-03-28 07:56:11,874 WARN  [org.hibernate.engine.jdbc.dialect.internal.StandardDialectResolver] (ServerService Thread Pool -- 73) HHH000385: Unknown Microsoft SQL Server major version [14] using SQL Server 2000 dialect`

I verified the persistence.xml configuration, but it shows version 11 is configured.

<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence" version="2.1">
  <persistence-unit name="dcm4chee-arc">
    <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
    <jta-data-source>java:/PacsDS</jta-data-source>
    <mapping-file>META-INF/orm-identity.xml</mapping-file>
    <properties>
      <property name="javax.persistence.database-product-name" value="Microsoft SQL Server"/>
      <property name="javax.persistence.database-major-version" value="11"/>
      <property name="javax.persistence.database-minor-version" value="0"/>
    </properties>
  </persistence-unit>
</persistence>

my dcm4chee-arc.xml configuration is attached:

[dcm4chee-arc.xml.zip](https://github.com/dcm4che/dcm4chee-arc-light/files/874791/dcm4chee-arc.xml.zip)

Also note that according to https://en.wikipedia.org/wiki/Microsoft_SQL_Server the latest release is 13.0.1601.5

**Comment by petrkalina** [comment]
Verified that adding:

`<property name="hibernate.dialect" value="org.hibernate.dialect.SQLServer2012Dialect"/>`

to the `persistence.xml` of the `dcm4chee-arc-entity-5.9.3-sqlserver.jar` solves the problem

**Comment by gunterze** [comment]
But `org.hibernate.dialect.SQLServer2012Dialect` will be selected by https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/engine/jdbc/dialect/internal/StandardDialectResolver.java with
```xml
    <properties>
      <property name="javax.persistence.database-product-name" value="Microsoft SQL Server"/>
      <property name="javax.persistence.database-major-version" value="11"/>
    </properties>
```
anyway!?

**Comment by petrkalina** [comment]
As mentioned above, it seems that unless the dialect is set explicitly, the major version from `persistence.xml` is not correctly read and instead an information obtained from elsewhere is used - see the warning:

`2017-03-28 07:56:11,874 WARN [org.hibernate.engine.jdbc.dialect.internal.StandardDialectResolver] (ServerService Thread Pool -- 73) HHH000385: Unknown Microsoft SQL Server major version [14] using SQL Server 2000 dialect`

and compare it to the known issue 

https://hibernate.atlassian.net/browse/HHH-9570

Apparently the `[14]` is actually the version that the server sees .. and which the `StandardDialectResolver.java` fails to recognise. 

Also note, that the latest SQL Server release is 13.xxx. I used the latest technology preview SQL Server version - cannot the version 14 passed onto the `StandardDialectResolver.java` somehow coincide with this?

**Comment by vrindanayak** [comment]
https://hibernate.atlassian.net/browse/HHH-9570 was fixed to support Major version 12
https://hibernate.atlassian.net/browse/HHH-11220 was fixed to support Major version 13

Opened issue : https://hibernate.atlassian.net/browse/HHH-11604 to support Major Version 14
