### ISSUE TITLE
Simplify configuration for DICOM Export

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#617]
Instead of having a particular [Exporter Descriptor](http://dcm4chee-arc-cs.readthedocs.io/en/latest/networking/config/exporter.html) configured for each DICOM AE Title, to which objects shall be exported by DICOM C-STORE,  it should be possible to send objects to any known DICOM AE Title without additional configuration.

- extend the default configuration with a generic DICOM Exporter Descriptor:
  Exporter ID: `dicom:`
  URI: `dicom`
  Queue Name: `Export1`
  Exporter Description: `Generic DICOM Exporter`
  Application Entity (AE) title: 'DCM4CHEE`
- extend the RESTful Services:
   - POST /aets/{aet}/rs/studies/{studyUID}/export/{exporterID}
   - POST /aets/{aet}/rs/studies/{studyUID}/series/{seriesUID}/export/{exporterID}
   - POST  /aets/{aet}/rs/studies/{studyUID}/series/{seriesUID}/instances/{objectUID}/export/{exporterID}

   to handle export IDs with the pattern `dicom:{DestinationAET}` different, by using the configuration for the generic  DICOM Exporter Descriptor with Exporter ID: `dicom:` as template, with  `dicom:{DestinationAET}` as URI.
- extend/simplify export based on export rules (on store of objects) to be consistent with the above requirement.
- in the UI, give the user the option to choose between DICOM and non-DICOM export. In case of DICOM, provide a list of all configured AETs for selection, for non-dicom, the list of configured exporters, execpt the Generic DICOM Exporter `dicom:`

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/8abb4ad815c54387c4802eceb9d42efbd3a79fdb
