### ISSUE TITLE
How to purge instance records for existing studies?

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#623]
The HOWTO explaining purging instance records (see: https://github.com/dcm4che/dcm4chee-arc-light/wiki/Purge-instance-records-from-DB) refers only to the situation when the data is received after the feature has already been set up.

Is it possible to trigger the feature also for already existing records?

**Comment by gunterze** [comment]
You need to set
- `series.metadata_update_time` // triggers #454
- `series.inst_purge_time` // triggers #470 
by SQL

**Comment by vrindanayak** [comment]
Updated wiki
