### ISSUE TITLE
Error importing dcm4chee-archive.ldif in Apache DS

### ISSUE THREAD

**Issue by marciofar** [dcm4che/dcm4chee-arc-light#630]
error importing dcm4chee-archive.ldif and default-config.ldif using ApacheDS, Apache Directory Studio, Mysql and Ubuntu 16.04LTS. Sorry my english is weak

**Erro dcm4chee-archive.ldif:**

Error while importing LDIF
 - [LDAP: error code 53 - UNWILLING_TO_PERFORM: failed for MessageType : MODIFY_REQUES
java.lang.Exception: [LDAP: error code 53 - UNWILLING_TO_PERFORM: failed for MessageType : MODIFY_REQUEST
Message ID : 34
    Modify Request
        Object : 'ou=attributetypes,cn=dcm4chee-archive,ou=schema'
            Modification[0]
                Operation :  replace
                Modification
objectclass: organizationalUnit
objectclass: top            Modification[1]
                Operation :  replace
                Modification
ou: attributetypesorg.apache.directory.api.ldap.model.message.ModifyRequestImpl@799f2232: null]
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkResponse(DirectoryApiConnectionWrapper.java:1268)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.access$9(DirectoryApiConnectionWrapper.java:1236)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper$4.run(DirectoryApiConnectionWrapper.java:716)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.runAndMonitor(DirectoryApiConnectionWrapper.java:1163)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkConnectionAndRunAndMonitor(DirectoryApiConnectionWrapper.java:1099)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.modifyEntry(DirectoryApiConnectionWrapper.java:738)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.importLdifRecord(ImportLdifRunnable.java:475)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.importLdif(ImportLdifRunnable.java:272)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.run(ImportLdifRunnable.java:218)
	at org.apache.directory.studio.connection.core.jobs.StudioConnectionJob.run(StudioConnectionJob.java:109)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

[LDAP: error code 53 - UNWILLING_TO_PERFORM: failed for MessageType : MODIFY_REQUEST
Message ID : 34
    Modify Request
        Object : 'ou=attributetypes,cn=dcm4chee-archive,ou=schema'
            Modification[0]
                Operation :  replace
                Modification
objectclass: organizationalUnit
objectclass: top            Modification[1]
                Operation :  replace
                Modification
ou: attributetypesorg.apache.directory.api.ldap.model.message.ModifyRequestImpl@799f2232: null]

**Error importing default-config.ldif:**

Error while importing LDIF
 - [LDAP: error code 54 - LOOP_DETECT: failed for MessageType : ADD_REQUES
java.lang.Exception: [LDAP: error code 54 - LOOP_DETECT: failed for MessageType : ADD_REQUEST
Message ID : 41
    Add Request :
Entry
    dn[n]: dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
    objectClass: dicomDevice
    objectClass: dcmDevice
    objectClass: dcmArchiveDevice
    objectClass: pkiUser
    dcmHideSPSWithStatusFromMWL: STARTED
    dcmHideSPSWithStatusFromMWL: DEPARTED
    dcmHideSPSWithStatusFromMWL: CANCELLED
    dcmHideSPSWithStatusFromMWL: DISCONTINUED
    dcmHideSPSWithStatusFromMWL: COMPLETED
    dcmRejectExpiredStudiesAETitle: DCM4CHEE
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.40
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.65
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.34
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.67
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.11
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.22
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.33
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.69
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.35
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.68
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.70
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.50
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.71
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.79.1
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.59
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.78.6
    dcmXDSiImagingDocumentSourceAETitle: DCM4CHEE
    dcmLeadingCFindSCPQueryCacheStaleTimeout: PT5M
    dcmKeyStoreURL: ${jboss.server.config.url}/dcm4chee-arc/key.jks
    dcmPurgeQueueMessagePollingInterval: PT1H
    dcmStorageID: fs1
    dcmQueryRetrieveViewID: hideRejected
    dicomThisNodeCertificateReference: dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
    dicomPrimaryDeviceType: ARCHIVE
    hl7PatientUpdateTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/hl7-adt2dcm.xsl
    dcmKeyStorePin: 0x73 0x65 0x63 0x72 0x65 0x74 
    dcmFuzzyAlgorithmClass: org.dcm4che3.soundex.ESoundex
    dcmUnzipVendorDataToURI: ${jboss.server.temp.url}/dcm4chee-arc
    dcmAECacheStaleTimeout: PT5M
    hl7ScheduleProcedureTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/hl7-order2dcm.xsl
    dcmQidoMaxNumberOfResults: 1000
    dcmRejectExpiredStudiesFetchSize: 10
    userCertificate;binary: 0x30 0x82 0x03 0x75 0x30 0x82 0x02 0x5D 0xA0 0x03 0x02 0x01 0x02 0x02 0x04 0x1F ...
    dcmExportTaskPollingInterval: PT1M
    dcmRejectExpiredSeriesFetchSize: 10
    hl7ImportReportTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/hl7-oru2dsr.xsl
    dicomInstalled: TRUE
    dcmSendPendingCMoveInterval: PT5S
    dicomManufacturerModelName: dcm4chee-arc
    dicomDeviceName: dcm4chee-arc
    dcmWadoSR2HtmlTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/dsr2html.xsl
    dicomSoftwareVersion: 5.10.0
    dcmAuditSpoolDirectory: ${jboss.server.data.dir}/audit-spool
    dcmIanTaskPollingInterval: PT1M
    dcmAuditRecordRepositoryURL: http://kibana:5601
    dcmAuditAggregateDuration: PT1M
    dcmPurgeStgCmtPollingInterval: PT1H
    dcmRejectExpiredStudiesPollingStartTime: 00:00
    dcmRejectExpiredStudiesPollingInterval: P1D
    dcmAuditPollingInterval: PT1M
    dcmExternalRetrieveAEDestination: DCM4CHEE
    dicomManufacturer: dcm4che.org
    dcmKeyStoreType: JKS
    dcmSendPendingCGet: TRUE
    dcmOverwritePolicy: SAME_SOURCE
    dcmDeleteRejectedPollingInterval: PT5M
    dcmPurgeStoragePollingInterval: PT5M
    dcmWadoSR2TextTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/dsr2text.xsl
    dcmPurgeStgCmtCompletedDelay: P1D
: ERR_04269 OBJECT_CLASS for OID dcmarchivedevice does not exist!]
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkResponse(DirectoryApiConnectionWrapper.java:1268)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.access$9(DirectoryApiConnectionWrapper.java:1236)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper$6.run(DirectoryApiConnectionWrapper.java:918)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.runAndMonitor(DirectoryApiConnectionWrapper.java:1163)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkConnectionAndRunAndMonitor(DirectoryApiConnectionWrapper.java:1099)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.createEntry(DirectoryApiConnectionWrapper.java:940)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.importLdifRecord(ImportLdifRunnable.java:465)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.importLdif(ImportLdifRunnable.java:272)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.run(ImportLdifRunnable.java:218)
	at org.apache.directory.studio.connection.core.jobs.StudioConnectionJob.run(StudioConnectionJob.java:109)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

[LDAP: error code 54 - LOOP_DETECT: failed for MessageType : ADD_REQUEST
Message ID : 41
    Add Request :
Entry
    dn[n]: dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
    objectClass: dicomDevice
    objectClass: dcmDevice
    objectClass: dcmArchiveDevice
    objectClass: pkiUser
    dcmHideSPSWithStatusFromMWL: STARTED
    dcmHideSPSWithStatusFromMWL: DEPARTED
    dcmHideSPSWithStatusFromMWL: CANCELLED
    dcmHideSPSWithStatusFromMWL: DISCONTINUED
    dcmHideSPSWithStatusFromMWL: COMPLETED
    dcmRejectExpiredStudiesAETitle: DCM4CHEE
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.40
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.65
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.34
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.67
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.11
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.22
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.33
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.69
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.35
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.68
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.70
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.50
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.71
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.79.1
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.88.59
    dcmWadoSupportedSRClasses: 1.2.840.10008.5.1.4.1.1.78.6
    dcmXDSiImagingDocumentSourceAETitle: DCM4CHEE
    dcmLeadingCFindSCPQueryCacheStaleTimeout: PT5M
    dcmKeyStoreURL: ${jboss.server.config.url}/dcm4chee-arc/key.jks
    dcmPurgeQueueMessagePollingInterval: PT1H
    dcmStorageID: fs1
    dcmQueryRetrieveViewID: hideRejected
    dicomThisNodeCertificateReference: dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
    dicomPrimaryDeviceType: ARCHIVE
    hl7PatientUpdateTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/hl7-adt2dcm.xsl
    dcmKeyStorePin: 0x73 0x65 0x63 0x72 0x65 0x74 
    dcmFuzzyAlgorithmClass: org.dcm4che3.soundex.ESoundex
    dcmUnzipVendorDataToURI: ${jboss.server.temp.url}/dcm4chee-arc
    dcmAECacheStaleTimeout: PT5M
    hl7ScheduleProcedureTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/hl7-order2dcm.xsl
    dcmQidoMaxNumberOfResults: 1000
    dcmRejectExpiredStudiesFetchSize: 10
    userCertificate;binary: 0x30 0x82 0x03 0x75 0x30 0x82 0x02 0x5D 0xA0 0x03 0x02 0x01 0x02 0x02 0x04 0x1F ...
    dcmExportTaskPollingInterval: PT1M
    dcmRejectExpiredSeriesFetchSize: 10
    hl7ImportReportTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/hl7-oru2dsr.xsl
    dicomInstalled: TRUE
    dcmSendPendingCMoveInterval: PT5S
    dicomManufacturerModelName: dcm4chee-arc
    dicomDeviceName: dcm4chee-arc
    dcmWadoSR2HtmlTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/dsr2html.xsl
    dicomSoftwareVersion: 5.10.0
    dcmAuditSpoolDirectory: ${jboss.server.data.dir}/audit-spool
    dcmIanTaskPollingInterval: PT1M
    dcmAuditRecordRepositoryURL: http://kibana:5601
    dcmAuditAggregateDuration: PT1M
    dcmPurgeStgCmtPollingInterval: PT1H
    dcmRejectExpiredStudiesPollingStartTime: 00:00
    dcmRejectExpiredStudiesPollingInterval: P1D
    dcmAuditPollingInterval: PT1M
    dcmExternalRetrieveAEDestination: DCM4CHEE
    dicomManufacturer: dcm4che.org
    dcmKeyStoreType: JKS
    dcmSendPendingCGet: TRUE
    dcmOverwritePolicy: SAME_SOURCE
    dcmDeleteRejectedPollingInterval: PT5M
    dcmPurgeStoragePollingInterval: PT5M
    dcmWadoSR2TextTemplateURI: ${jboss.server.temp.url}/dcm4chee-arc/dsr2text.xsl
    dcmPurgeStgCmtCompletedDelay: P1D
: ERR_04269 OBJECT_CLASS for OID dcmarchivedevice does not exist!]

**Comment by gunterze** [comment]
`OBJECT_CLASS for OID dcmarchivedevice does not exist`
=>
Did you [ Import LDAP schema files for Apache DS]( https://github.com/dcm4che/dcm4chee-arc-light):
> $DCM4CHEE_ARC/ldap/apacheds/dicom.ldif
> $DCM4CHEE_ARC/ldap/apacheds/dcm4che.ldif
> $DCM4CHEE_ARC/ldap/apacheds/dcm4chee-archive.ldif
?!

See [dcm4che User group](https://groups.google.com/forum/#!forum/dcm4che) before open an issuer about installation problems

**Comment by marciofar** [comment]
Yes. I imported following the order of the tutorial.
$ DCM4CHEE_ARC / ldap / apacheds / dicom.ldif ---> OK
$ DCM4CHEE_ARC / ldap / apacheds / dcm4che.ldif ---> OK
$ DCM4CHEE_ARC / ldap / apacheds / dcm4chee-archive.ldif ---> failed

**Comment by gunterze** [comment]
Fixed by #644. [Fixed dcm4chee-archive.ldif](https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/36b0e47fa7dc0245a7c601f7622cfa5b04130c7b/dcm4chee-arc-assembly/src/main/resources/ldap/apacheds/dcm4chee-archive.ldif)
