### ISSUE TITLE
STGCMT-RS: adjust returned content type from application/json to application/dicom+json

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#638]
Effected services:
- POST /aets/{aet}/rs/studies/{StudyInstanceUID}/stgcmt
- POST /aets/{aet}/rs/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/stgcmt
- POST /aets/{aet}/rs/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/instances/{SOPInstanceUID}/stgcmt

Related: #637 #636

**Comment by vrindanayak** [comment]
Support extended on server side for `application/json` as well.
