### ISSUE TITLE
Refactor STOW-RS tool

### ISSUE THREAD

**Issue by vrindanayak** [dcm4che/dcm4chee-arc-light#651]

**Comment by hczedik** [comment]
@vrindanayak @gunterze Can you also open such changes as pull requests for the master branch, so that everybody in the community can benefit from toolkit improvements?

**Comment by hczedik** [comment]
Would be good to base these changes on all the changes that have already happened on the master branch:
https://github.com/dcm4che/dcm4che/commits/master/dcm4che-tool/dcm4che-tool-stowrs/src/main/java/org/dcm4che3/tool/stowrs/StowRS.java

e.g. 7d524103
