### ISSUE TITLE
dcm4che-tool-stow: Failed to extract Image Pixel Attributes from JPEG header

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#756]
Failed to extract Image Pixel Attributes from JPEG header with more than 16K data before SOS marker.

related: #754

**Comment by hczedik** [comment]
Hi Vrinda,
pull request https://github.com/dcm4che/dcm4che/pull/92 has now been merged into the master. Can you also port over changes done for this issue to the master please?
