### ISSUE TITLE
Spaces in storage path breaks upload

### ISSUE THREAD

**Issue by tedl0** [dcm4che/dcm4chee-arc-light#774]
In my configuration I have the storage path in a format that is human readable, specifically using the Patient ID (00100020) as a part of the storage path. If the user enters the Patient ID with a space it breaks upload and gives a "Failed to parse" error when sent into dcm4chee. This is pretty much the same problem if there are any special characters in the path.

For reference I'm using:  pathFormat={00080022}/{00100020}-{00080060}/{0020000D}
See error message below at "PN 108776-DX":

2017-06-09 11:57:49,595 WARN  [org.dcm4chee.arc.store.impl.StoreServiceImpl] (EE-ManagedExecutorService-default-Thread-6) DCM4CHEE<-PACSUSER-PC(16): Failed to parse received object:
: java.lang.IllegalArgumentException: Illegal character in path at index 11: 20170609/**PN 108776-DX**/124.13.1115.162.1211.159.20170609113927

**Comment by gunterze** [comment]
Use {00100020,urlencoded}. Please post further questions to https://groups.google.com/forum/#!forum/dcm4che
