### ISSUE TITLE
Installation guide - Import config to LDAP - Point 6

### ISSUE THREAD

**Issue by ph73nt** [dcm4che/dcm4chee-arc-light#79]
In section [(https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#import-default-configuration-into-ldap-server)]

Point 6 does not really make sense: 

> 6\. Import $DCM4CHEE_ARC/ldap/add-vendor-data.ldif using the LDIF import function of Apache Directory Studio LDAP Browser to import $DCM4CHEE_ARC/ldap/dcm4chee-arc-conf-data-<version>.zip...

Reads as if importing the LDIF imports the zip. It's not actually clear how this step is done.

**Comment by vrindanayak** [comment]
Rectified the text to be more clearer.
