### ISSUE TITLE
dcm4che-tool-dcmdir: enable to customize included record attributes by option --record-config 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#790]
Option | Description
-- | --
--record-config <file\|url>  |  file path or URL to configuration of directory record attributes. At default only mandatory directory record attributes are included.

Required by #736

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4che/commit/439808d67ce28fc89b2a7cf62a5ff3fc32134412

**Comment by hczedik** [comment]
Hi Vrinda,
has this already been pulled over to the master branch already?

**Comment by vrindanayak** [comment]
Hi Hermann, this is already pulled/merged as part of
https://github.com/dcm4che/dcm4che/pull/133   and 
https://github.com/dcm4che/dcm4che/pull/120

**Comment by hczedik** [comment]
Thanks!
