### ISSUE TITLE
Invalid docker images dcm4che/dcm4chee-arc-psql with logstash option since 5.10.1

### ISSUE THREAD

**Issue by ghetolay** [dcm4che/dcm4chee-arc-light#840]
There is a problem with docker images up to 5.10.0 version.
The problem is that dcm4chee-arr-proxy is only published for version 5.10.0 so on this line on Dockerfile : 

```
 && curl -O http://www.dcm4che.org/maven2/org/dcm4che/dcm4chee-arc/dcm4chee-arr-proxy/${DCM4CHEE_ARC_VERSION}/dcm4chee-arr-proxy-${DCM4CHEE_ARC_VERSION}-secure.war
```

curl returns a 404 page but it's still being saved as a valid file, so `dcm4chee-arr-proxy-secure.war` ends up being a text file instead of the intended war.

I think you should add the `-f` flag to all curl commands to make the docker build fail when there is an error retrieving a file. I was about to submit a PR but seems like Dockerfile is not public, couldn't find it.

Now about the real problem, the missing of dcm4chee-arr-proxy up to version 5.10.0, I don't know if its should be published or if there should be a new variable for dcm4chee-arr-proxy version on the dockerfile.

**Comment by gunterze** [comment]
I pushed the fixed docker images dcm4che/dcm4chee-arc-psql[5.10.x-logstash[-secure[-ui]] to dockerhub.

**Comment by ghetolay** [comment]
That was fast ! Thank you.
