### ISSUE TITLE
build    dcm4che-tool-probetc is error  

### ISSUE THREAD

**Issue by dhanzhang** [dcm4che/dcm4chee-arc-light#85]
[INFO] Building dcm4che-tool-probetc dcm4chee-arc-light-5.2.0
[INFO] ------------------------------------------------------------------------
Downloading: http://repository.jboss.org/nexus/content/groups/public/org/dcm4che/dcm4che-conf-prefs/dcm4chee-arc-light-5.2.0/dcm4che-conf-prefs-dcm4chee-arc-light-5.2.0.pom

this url is error ! 
![qq20160411170844](https://cloud.githubusercontent.com/assets/457633/14422159/d9592fe0-0007-11e6-9166-092765c0d851.png)

**Comment by dhanzhang** [comment]
![qqc2](https://cloud.githubusercontent.com/assets/457633/14422207/0ac2cbcc-0008-11e6-84f1-9901c4fb54eb.png)

**Comment by tehcpu** [comment]
Have the same error.
I follow this guide https://github.com/dcm4che/dcm4chee-arc-light#build

**Comment by dhanzhang** [comment]
@tehcpu     @gunterze   ,  we 　build success  
  from     https://github.com/dcm4che/dcm4che.git  -v 5.1.0
and  modify the pom.xml  <version>dcm4chee-arc-light-5.2.0</version> as  <version>dcm4chee-arc-light-5.1.0</version>   ,  is there have  ghost-error ?

**Comment by gunterze** [comment]
Fixed by removing modules with dependencies to conf-prefs
