### ISSUE TITLE
Cannot move study to another patient

### ISSUE THREAD

**Issue by dbortolz** [dcm4che/dcm4chee-arc-light#860]
Hello to everybody.

First of all thank you for the great job you are doing on this brand new version of dcm4chee.

I don't know how to move a study from one patient to another. The UI seems to do nothing, I tried the following steps:

1. select a study and click on the _cut_ icon:
![move_to_pat-1](https://user-images.githubusercontent.com/10025418/28203767-5a63d8ec-687b-11e7-94f9-7ad24ea9d11b.jpg)
2. select target patient and click on the _paste_ icon:
![move_to_pat-2](https://user-images.githubusercontent.com/10025418/28203766-5a63ba06-687b-11e7-90c7-ce134b15ccc9.jpg)
3. select rejection type and confirm
![move_to_pat-3](https://user-images.githubusercontent.com/10025418/28203768-5a6a9d3a-687b-11e7-9713-3772278e0168.jpg)

The operation result looks good: HTTP 200 response and some JSON data
![move_to_pat-4](https://user-images.githubusercontent.com/10025418/28203826-972e514e-687b-11e7-8ed0-60a04dc772a3.jpg)

No error appears in logs:

```
2017-07-14 09:37:07,465 INFO  [org.dcm4chee.arc.iocm.rs.IocmRS] (default task-11) Process POST /dcm4chee-arc/aets/OUR_PACS/rs/studies from 08f8af44-587f-4669-83d8-f27d8bbc5648@10.0.0.76
```

I have tried to edit the study the REST API way and it fails explicitly. I can find some error in the log file:

```
2017-07-13 15:42:19,031 INFO  [org.dcm4chee.arc.iocm.rs.IocmRS] (default task-12) Process POST /dcm4chee-arc/aets/OUR_PACS/rs/studies from 579a5fdc-f3ed-4c65-849a-83e77282b506@10.0
.2.23
2017-07-13 15:42:19,084 ERROR [org.jboss.as.ejb3.invocation] (default task-12) WFLYEJB0034: EJB Invocation failed on component StudyServiceEJB for method public void org.dcm4chee.arc.s
tudy.impl.StudyServiceEJB.updateStudy(org.dcm4chee.arc.study.StudyMgtContext): javax.ejb.EJBException: org.dcm4chee.arc.patient.PatientMismatchException: Patient[pk=15, id=PatientID[pk
=15, id=654654XXXX, issuer=EMA_RIS], name=CANÀ^ORONZO] does not match Patient[pk=13, id=PatientID[pk=13, id=1573836, issuer=null], name=BORTOLUZZI^DANIELE] in existing Study[pk=39,
 uid=1.3.76.8.2180.1416429.7561252, id=*]
[...] snip [...]
2017-07-13 15:42:19,095 ERROR [io.undertow.request] (default task-12) UT005023: Exception handling request to /dcm4chee-arc/aets/OUR_PACS/rs/studies: org.jboss.resteasy.spi.Unhandl
edException: javax.ejb.EJBException: org.dcm4chee.arc.patient.PatientMismatchException: Patient[pk=15, id=PatientID[pk=15, id=654654XXXX, issuer=EMA_RIS], name=CANÀ^ORONZO] does no
t match Patient[pk=13, id=PatientID[pk=13, id=1573836, issuer=null], name=BORTOLUZZI^DANIELE] in existing Study[pk=39, uid=1.3.76.8.2180.1416429.7561252, id=*]
```
Looking at the code in [StudyServiceEJB.java](https://github.com/dcm4che/dcm4chee-arc-light/blob/dfd37730b131194d31ecfc1c469c1ba5695569a5/dcm4chee-arc-study/src/main/java/org/dcm4chee/arc/study/impl/StudyServiceEJB.java) this should be the expected result:

```java
if (study.getPatient().getPk() != ctx.getPatient().getPk())
    throw new PatientMismatchException("" + ctx.getPatient() + " does not match " +
        study.getPatient() + " in existing " + study);
```

so how can I move a study to another patient?

**Comment by shral** [comment]
Hello,
Thank you for reporting the Bug!
I pushed a fix for that Bug, if you don't want to upgrade and want to wait for the next official docker release you can use the "copy" function from the UI instead (Copy study to another patient, reject -> delete study from the first one).
Best Regards
Shefki

**Comment by dbortolz** [comment]
Dear Shefki,

thank you for the quick response.
I would like to test the _bleeding edge_ version but I have a couple of problems at compiling master (@76e30393):
* compiling fails on HL7-related stuff: wrong compiling dependency and maybe missing dcm4che.* maven artifacts
* there is no documentation about deploying compiled sources, so I should "study" the content of the binary package and try to understand what I need to deploy a custom build.

I know I have gone OT but if you want we can continue this discussion elsewhere.

Thank you.

**Comment by dbortolz** [comment]
I've upgraded to recompiled sources (master @45e053df) and the behavior is exactly the same.

**Comment by shral** [comment]
I have tested the process on my Installation again, I don't see any unexpected behavior, and you are saying that you see the post request from the UI in the log. 
So I think your study was moved successfully and the UI is doing that what it should. Note that if you choose as Rejection type "Patient Safety" (Unlike for example "Retention Expired") you will see in that patient (Where the study previously was) a "study" with one instance with the Modality "KO" (so you can see that this study was rejected, in case that the study is somewhere else cashed).
