### ISSUE TITLE
DialectResolutionInfo cannot be null when hibernate.dialect not set

### ISSUE THREAD

**Issue by hungctt** [dcm4che/dcm4chee-arc-light#895]
Hi All,

I am new to DCM4CHE, when I tried install follow guide  https://github.com/dcm4che/dcm4chee-arc-light/wiki/Installation#Download-and-extract-binary-distribution-package 

I tried deploy but it was not successful.

[standalone@localhost:9990 /] deploy /opt/dcm4chee/dcm4chee-arc-5.10.4-psql/deploy/dcm4chee-arc-ear-5.10.4-psql.ear
{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"dcm4chee-arc-ear-5.10.4-psql.ear#dcm4chee-arc\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"dcm4chee-arc-ear-5.10.4-psql.ear#dcm4chee-arc\": org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
    Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
    Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set"},"WFLYCTL0412: Required services that are not installed:" => ["jboss.persistenceunit.\"dcm4chee-arc-ear-5.10.4-psql.ear#dcm4chee-arc\""],"WFLYCTL0180: Services with missing/unavailable dependencies" => undefined}}}

[standalone@localhost:9990 /] version
JBoss Admin Command-line Interface
JBOSS_HOME: /opt/jboss/wildfly-10.1.0.Final
JBoss AS release: 2.2.0.Final "Kenny"
JBoss AS product: WildFly Full 10.1.0.Final
JAVA_HOME: null
java.version: 1.8.0_141
java.vm.vendor: Oracle Corporation
java.vm.version: 25.141-b16
os.name: Linux
os.version: 2.6.32-696.6.3.el6.x86_64

Please help!
Thanks.

**Comment by gunterze** [comment]
Check your DB connection!

**Comment by zorbao** [comment]
Hi,

Similar situation as @hungctt. I am trying to find the solution... in vain.

[standalone@localhost:9990 /] deploy C:\dcm4chee\deploy\dcm4chee-arc-ear-5.11.0-mysql.ear
{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"dcm4chee-arc-ear-5.11.0-mysql.ear#dcm4chee-arc\"" => "org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
    Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
    Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set"}}}}

[standalone@localhost:9990 /] version
JBoss Admin Command-line Interface
JBOSS_HOME: C:\wildfly
Release: 3.0.8.Final "Kenny"
Product: WildFly Full 11.0.0.Final
JAVA_HOME: C:\Program Files\Java\jdk1.8.0_151
java.version: 1.8.0_151
java.vm.vendor: Oracle Corporation
java.vm.version: 25.151-b12
os.name: Windows 10
os.version: 10.0

Modules used during install on a Windows 10 Professional (x64) French - with all latest Windows updates:
- jdk-8u151-windows-x64.exe
- dcm4chee-arc-5.11.0-mysql.zip
- wildfly-11.0.0.Final.zip
- mariadb-10.0.33-winx64.msi
- apacheds-2.0.0-M20.exe
- ApacheDirectoryStudio-2.0.0.v20150606-M9-win32.win32.x86_64.zip

Could you, please help me, I am getting out of ideas.
Tell me what other information is needed to investigate.
Thank you in advance.
