### ISSUE TITLE
Include proposed UserTypeCode and UserIDTypeCode in emitted Audit Messages

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#912]
s.
- [cp-xxxx_AddUserTypetoAudit.doc](https://docs.google.com/document/d/1f777aFlr04-kvhMHjtcI3F1-odE8xUqLR4065OmpzJ0/edit?usp=sharing)
- [cp1640_02_AddUserIDTypetoAudit.doc](https://docs.google.com/document/d/1R-AOPH8VgdrvE3B5NkqwUT8J1vf27PdFM4fhsKnE1Tg/edit?usp=sharing)

**Comment by vrindanayak** [comment]
- `UserTypeCode` currently limited to have just 2 values : 
       - `Person` : value as `1`
       - `Application` : value as `2`

**Comment by vrindanayak** [comment]
- Added `EV (113877, DCM, "Device Name")` to identify archive device name and `EV (113871, DCM, "Person ID")` to identify secured user id in list of `UserIdTypeCode`.
- Replaced ; separated AE titles of archive device with the archive device name in UserID fields of audit messages
