### ISSUE TITLE
UI2: sort AET list lexicographically

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#918]
the AETs should be ordered in lexicographical order, otherwise it is difficult to find a particular AET in larger environments.

refer to the screenshot for details:

![screen shot 2017-08-15 at 13 46 29](https://user-images.githubusercontent.com/1150350/29316501-2f601c56-81c0-11e7-9a4a-690cc44a6a45.png)

**Comment by shral** [comment]
Diff tab is not part of the open source version of the UI, therefore, I'm closing this issue (Ther is a Redmine issue for the diff).
