### ISSUE TITLE
UI: Propagate authentication to REST layer

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#923]
- [x] change configuration of Java Adapter for REST services (dcm4chee-arc-war-VERSION-secure.war) to [bearer-only](https://keycloak.gitbooks.io/documentation/securing_apps/topics/oidc/java/java-adapter-config.html).

- [x] return bearer token by [REALM-RS service](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/REALM-RS/realm) (property: `"token"`), obtained from [KeycloakSecurityContex](http://www.keycloak.org/docs-api/3.2/javadocs/org/keycloak/KeycloakSecurityContext.html) by `getTokenString()`.

- [x] return lifetime in seconds of the bearer token by [REALM-RS service](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/REALM-RS/realm) (property: `"expiration"`), obtained from [KeycloakSecurityContex](http://www.keycloak.org/docs-api/3.2/javadocs/org/keycloak/KeycloakSecurityContext.html) by `getIdToken().getExpiration()`. 

- [x] return system current time in seconds by [REALM-RS service](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/REALM-RS/realm) (property: `"systemCurrentTime"`).

- [x] request a new bearer token by the REALM-RS service if it is already expired, before invoking any request to RS Services by UI

- [x] add HTTP Header `"Authorization: Bearer  {token}"` in requests to RS Services by UI

Related: #919

**Comment by shral** [comment]
Test result:
- When you get the token from the service on UI load, after some time, the token is not valid anymore and the services stopped working.
- If you get the token from the archive every time before firing a service, the token is always valid.
Solution:
Best solution is that the UI gets/refreshes the token while communicating directly with keycloak, without using the server for that (see [angular 2 example from keycloak](https://github.com/keycloak/keycloak/tree/fc6d6ff7f7dae7fb25edf052659d18cd8de55a5f/examples/demo-template/angular2-product-app/src/main/webapp)

**Comment by gunterze** [comment]
Realm service is issued for each QIDO-RS request:
```
16:27:37,078 INFO  [org.dcm4chee.arc.realm.rs.RealmRS] (default task-94) Process GET org.dcm4chee.arc.realm.rs.RealmRS@9d89fea from null@127.0.0.1
16:27:37,080 INFO  [org.dcm4chee.arc.realm.rs.RealmRS] (default task-95) Process GET org.dcm4chee.arc.realm.rs.RealmRS@531b2971 from null@127.0.0.1
16:27:37,125 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-96) RESTEASY002142: Multiple resource methods match request "GET /aets/DCM4CHEE/rs/studies/count". Selecting one. Matching methods: [public void org.dcm4chee.arc.wado.WadoRS.retrieveStudyBulkdata(java.lang.String,javax.ws.rs.container.AsyncResponse), public javax.ws.rs.core.Response org.dcm4chee.arc.qido.QidoRS.countStudies() throws java.lang.Exception, public void org.dcm4chee.arc.wado.WadoRS.retrieveStudy(java.lang.String,javax.ws.rs.container.AsyncResponse)]
16:27:37,126 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-96) Process GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies/count?includefield=all&offset=0&limit=21&orderby=-StudyDate%2C-StudyTime from null@127.0.0.1
16:27:37,134 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-97) RESTEASY002142: Multiple resource methods match request "GET /aets/DCM4CHEE/rs/studies". Selecting one. Matching methods: [public javax.ws.rs.core.Response org.dcm4chee.arc.qido.QidoRS.searchForStudiesJSON() throws java.lang.Exception, public javax.ws.rs.core.Response org.dcm4chee.arc.qido.QidoRS.searchForStudiesXML() throws java.lang.Exception]
16:27:37,136 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-97) Process GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies?includefield=all&offset=0&limit=21&orderby=-StudyDate%2C-StudyTime from null@127.0.0.1
16:27:37,183 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-97) SearchForStudies: 21 Matches
16:27:43,481 INFO  [org.dcm4chee.arc.realm.rs.RealmRS] (default task-99) Process GET org.dcm4chee.arc.realm.rs.RealmRS@4bd62191 from null@127.0.0.1
16:27:43,481 INFO  [org.dcm4chee.arc.realm.rs.RealmRS] (default task-98) Process GET org.dcm4chee.arc.realm.rs.RealmRS@41c551f3 from null@127.0.0.1
16:27:43,488 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-100) RESTEASY002142: Multiple resource methods match request "GET /aets/DCM4CHEE/rs/studies/count". Selecting one. Matching methods: [public void org.dcm4chee.arc.wado.WadoRS.retrieveStudyBulkdata(java.lang.String,javax.ws.rs.container.AsyncResponse), public javax.ws.rs.core.Response org.dcm4chee.arc.qido.QidoRS.countStudies() throws java.lang.Exception, public void org.dcm4chee.arc.wado.WadoRS.retrieveStudy(java.lang.String,javax.ws.rs.container.AsyncResponse)]
16:27:43,490 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-100) Process GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies/count?includefield=all&offset=0&limit=21&orderby=-StudyDate%2C-StudyTime from null@127.0.0.1
16:27:43,495 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-101) RESTEASY002142: Multiple resource methods match request "GET /aets/DCM4CHEE/rs/studies". Selecting one. Matching methods: [public javax.ws.rs.core.Response org.dcm4chee.arc.qido.QidoRS.searchForStudiesJSON() throws java.lang.Exception, public javax.ws.rs.core.Response org.dcm4chee.arc.qido.QidoRS.searchForStudiesXML() throws java.lang.Exception]
16:27:43,496 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-101) Process GET /dcm4chee-arc/aets/DCM4CHEE/rs/studies?includefield=all&offset=0&limit=21&orderby=-StudyDate%2C-StudyTime from null@127.0.0.1
16:27:43,531 INFO  [org.dcm4chee.arc.qido.QidoRS] (default task-101) SearchForStudies: 21 Matches

```
