### ISSUE TITLE
Retrieving imaging issues with Inteleviewer

### ISSUE THREAD

**Issue by leoliyuanduo** [dcm4che/dcm4chee-arc-light#941]
We are currently using old version of dcm4chee. My manager would like to upgrade to dcm4chee-arc-light. It has been installed on ubuntu according to instruction. The version number is 5.10.4  . The AE titles have been added in configuration. All devices can be echoed in Application Entities list, which means the connection has been verified. I am able to send studies from verified data source to this server and queue studies on the server. 
However, I cannot retrieve images from this server by using Inteleviewer. The queue manager shows 'activity' is pending and 'progress' is waiting for the first imaging... I also tried other medical image viewer like HOROS on the mac. It can retrieve studies and images. It doesn't have this problem.
It will be much appreciated, if anyone can advise me on how to solve it.

**Comment by shral** [comment]
Please post your question in the [dcm4che forum](https://groups.google.com/forum/#!forum/dcm4che).
