### ISSUE TITLE
UI2: In configuration view, sort devices, application entities and HL7 applications lexicographically

### ISSUE THREAD

**Issue by petrkalina** [dcm4che/dcm4chee-arc-light#945]
when many devices are defined, the navigation is not comfortable when they are not sorted properly

![screen shot 2017-08-25 at 15 49 24](https://user-images.githubusercontent.com/1150350/29719173-0759468e-89ad-11e7-9228-5278cbc28236.png)

**Comment by gunterze** [comment]
I propose to return the list of devices sorted by device name by the RESTful service [/dcm4chee-arc/devices - List Devices](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/CONFIG-RS/listDevices).

**Comment by vrindanayak** [comment]
- return the list of HL7 Applications sorted by HL7 Application Name by the RESTful service [/dcm4chee-arc/hl7Apps - List HL7 Applications](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/CONFIG-RS/listHL7Applications)
