### ISSUE TITLE
UI: Merge two Patients in external Archives 

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#960]
Utilizing [/hl7apps/{appName}/hl7/{externalAppName}/patients/{priorPatientID}/merge
Merge Patient external](http://petstore.swagger.io/index.html?url=https://raw.githubusercontent.com/dcm4che/dcm4chee-arc-light/master/dcm4chee-arc-ui2/src/swagger/swagger.json#/HL7-RS/MergePatientExternal)

Use HL7Application Name associated with with local and remote AE as Sending and Receiving Application Name. s. #957

**Comment by shral** [comment]
Rest URL is prepared, but we should send to the server the whole DICOM object not the object with custom defined fields like we have for internal patient merge.

**Comment by vrindanayak** [comment]
- Target Patient ID being sent in URL instead of Prior Patient ID
- Request body contains json in format mentioned for Internal merge causing JsonParsingException
