### ISSUE TITLE
Audit Configuration Changes

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#963]
Audit Configuration Changes by [Security Alert](http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_A.5.3.11) Audit Message with
- EventOutcomeIndicator: 0 (=Success)
- EventTypeCode: (110131, DCM, "Software Configuration")
- ParticipantObjectIDTypeCode: (113877, DCM, "Device Name")
- ParticipantObjectID: _\<Device Name>_
- ParticipantObjectDetail: "Alert Description"=_\<Rendered Configuration Changes>_, e.g.:
  ```
  U dicomDeviceName=dcm4chee-arc,cn=Devices,cn=DICOM Configuration,dc=dcm4che,dc=org
    dicomSoftwareVersion: [5.10.5]=>[5.10.6]
  ```

Make include of Child Objects and Attributes of created Objects configurable by `boolean` Archive Device property `AuditSoftwareConfigurationVerbose` (default: `false`).

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/a414a7d3d25e58bcbef66dcdf249fec4d381062c
