### ISSUE TITLE
Consider configured HL7SendingCharacterSet for sending HL7 Messages

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#971]
- According  [IHE ITI TF-2x, C.2.2 Message Control](https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_TF_Vol2x.pdf?page=21), Field _MSH-18 - Character Set_ shall only be valued if the message utilizes character sets other than ISO IR-6, also known as ASCII.
- It's not sufficient to set Field _MSH-18 - Character Set_ with the configured value. You also have to apply the character set for encoding the Java `String` to `byte[]`

requires dcm4che/dcm4che#169

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/c45ac6f4333c077756bda74df418bc2a8201d243
