### ISSUE TITLE
Help for choose pacs server

### ISSUE THREAD

**Issue by mohamadrezax** [dcm4che/dcm4chee-arc-light#972]
Hi . Recently i am looking for open source pacs server and i am impressed by dcm4chee's features. I am wondering that is this a mature software and its service is stable or not?
Is dcm4chee extensible for addind other features?
Thanx

**Comment by vrindanayak** [comment]
Please post queries at https://groups.google.com/forum/#!forum/dcm4che . This issue tracker is intended for bug reports and feature requests.
