### ISSUE TITLE
Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by rschiec** [dcm4che/dcm4chee-arc-light#973]
I'm having troubles with creating the OIDC client.  I entered https://hostname:8443/dcm4chee-arc/ui2 as the root value and http://hostname:8080/dcm4chee-arc/ui2/* as the Valid Redirect URI in the admin console.

When I try to access http://hostname:8080/dcm4chee-arc/ui2 a page is displayed that just says "We're sorry...  Invalid parameter: redirect_uri"

In the keycloak logfile it reports:

2017-09-21 18:04:31,995 WARN  [org.keycloak.events] (default task-2) type=LOGIN_ERROR, realmId=dcm4che, clientId=dcm4chee-arc-ui, userId=null, ipAddress=162.5.36.86, error=invalid_redirect_uri, redirect_uri=https://hostname:8443/dcm4chee-arc/ui2/

I am using a valid, resolvable hostname and I am completely stuck here.

Any ideas?

**Comment by gunterze** [comment]
Are you sure that you configured `http://hostname:8080/dcm4chee-arc/ui2/*` **and**  `https://hostname:8443/dcm4chee-arc/ui2/*` as Valid Redirect URIs?

Please post problems with the installation/setup at https://groups.google.com/forum/#!forum/dcm4che . This issue tracker is intended for bug reports and feature requests.
