### ISSUE TITLE
All RESTful Services shall log received requests in server.log

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#986]
Ensure that all RESTful Services  log received requests in server.log.
List RESTful service, which did not log the request before below:
-  **GET /devices/{deviceName}/vendordata**  get Device Vendor Data
-  **PUT /devices/{deviceName}/vendordata** Update Device Vendor Data
-  **DELETE /devices/{deviceName}/vendordata** Delete Device Vendor Data
- **GET /devices/{deviceName}** Get Device
- **GET /devices** List Devices
- **GET /aes** List Application Entities
- **GET /hl7apps** List HL7 Applications
- **GET /unique/aets** List Registered Application Entity Titles
- **GET /unique/hl7apps** List Registered HL7 Applications and Facility Names 
- **GET /aets** List Archive AE Titles
- **GET /attribute-filter/{entity}** Get Attribute Filter
- **GET /attribute-set/{type}** Get Attribute Set
- **GET /export** List Exporters
- **GET /reject** List Rejection Notes
- **GET /storage** List Storage Systems
- **GET /devicename** Get Archive Device Name
- **GET /elasticsearch** Get Access URL of Elastic Search
- **GET /ctrl/status** Get Archive Status
- **GET /monitor/associations** List Open Associations
- **GET /queue/{queueName}** List Tasks in Queue
- **DELETE /queue/{queueName}** Delete Tasks in Queue
- **POST /aets/{aet}/dimse/{externalAET}** Verify DICOM connection
- **GET /monitor/export** List Export Tasks
- **GET /queue** List Configured Queues
- **GET /ui2/rs/realm** Show Realm of Logged-in User
- **GET /stgcmt** List Storage Commitment Results
- **POST /aets/{aet}/rs/studies/{StudyInstanceUID}/stgcmt** Request Storage Commitment of Study
- **POST /aets/{aet}/rs/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/stgcmt** Request Storage Commitment of Series
- **POST /aets/{aet}/rs/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}/instances/{SOPInstanceUID}/stgcmt** Request Storage Commitment of Instance

**Comment by gunterze** [comment]
- GET /ui2/rs/realm Show Realm of Logged-in User
does not get logged:
```
16:21:53,099 INFO  [org.dcm4chee.arc.realm.rs.RealmRS] (default task-91) Process GET org.dcm4chee.arc.realm.rs.RealmRS@e5d3afa from null@127.0.0.1
```

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/331bd02ba1d36b8793f86d68aec4e43c0d02035c
