### ISSUE TITLE
HL7: Process HL7 v2 null values (|""|) in incoming messages

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#998]
|""| shall be mapped to empty value of correspondent  DICOM Attribute
|| shall not cause that the correspondent DICOM Attribute of an already existing entity get removed 

HL7 v2.5 CH02.pdf p.8:
> HL7 does not care how systems actually store data within an application. When fields are transmitted, they are sent as character strings. Except where noted, HL7 data fields may take on the null value. Sending the null value, which is transmitted as two double quote marks (""), is different from omitting an optional data field. The difference appears when the contents of a message will be used to update a record in a database rather than create a new one. If no value is sent, (i.e., it is omitted) the old value should remain unchanged. If the null value is sent, the old value should be changed to null. 

s.o.
- [ProtoGen/HL7 - On the null value](http://amisha.pragmaticdata.com/~gunther/ProtoGen/doc/ProtoGen_18.html)
- [HAPI mailing list - handling of HL7-null](https://sourceforge.net/p/hl7api/mailman/message/3794596/)

**Comment by vrindanayak** [comment]
Not handled currently for order messages and ORU messages

**Comment by vrindanayak** [comment]
Not needed for HL7 ORU messages as the whole object is replaced
