### ISSUE TITLE
HL7: Use HL7 v2 null values (|""|) in sent  ADT^A31 messages

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4chee-arc-light#999]
- Use HL7 v2 null values (|""|) in sent  ADT^A31 messages to communicate that the correspondent DICOM Attribute is absent or has no value. 
- Configurable by `boolean` Archive Device and/or Archive HL7 Application Extension property `hl7UseNullValue` (default: `false`)

Related: #998

**Comment by vrindanayak** [comment]
https://github.com/dcm4che/dcm4chee-arc-light/commit/ce5b2089a81970d9a9998637cf24d3f2b67ea269
